souffle: souffle::SCCGraph Class Reference
souffle::SCCGraph Class Reference
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
#include <PrecedenceGraph.h>
Public Member Functions
std::set< const AstRelation * > getInbound (const unsigned scc) const
Get all relations in a predecessor SCC that have a successor relation in the given SCC.
std::set< const AstRelation * > getInputs (const unsigned scc) const
Get all input relations in the given SCC.
std::set< const AstRelation * > getIns (const unsigned scc) const
Get all inbound and all input relations in the given SCC.
std::set< const AstRelation * > getOutbound (const unsigned scc) const
Get all relations in the given SCC that have a successor relation in another SCC.
std::set< const AstRelation * > getOutputs (const unsigned scc) const
Get all output relations in the given SCC.
std::set< const AstRelation * > getOuts (const unsigned scc) const
Get all outbound and all output relations in the given SCC.
bool isInSameSCC (const AstRelation *relation1, const AstRelation *relation2) const
True if both given relations are in the same SCC, false otherwise.
bool isRecursive (const unsigned scc) const
bool isRecursive (const AstRelation *relation) const
const std::set< unsigned > & predecessorSCCs (const unsigned scc) const
Get all predecessor SCCs of a specified scc.
void print (std::ostream &os, const std::string &format) const
void print (std::ostream &os) const override
Output strongly connected component graph in graphviz format.
const std::set< const
AstRelation * > relations (const unsigned scc) const
Get the relations for a given scc.
void run (const AstTranslationUnit &translationUnit) override
run analysis for a RAM translation unit
unsigned scc (const AstRelation *relation) const
Get the scc of a given relation.
size_t size () const
Return the number of strongly connected components in the SCC graph.
const std::set< unsigned > & successorSCCs (const unsigned scc) const
Get all successor SCCs of a specified scc.
Public Member Functions inherited from souffle::AstAnalysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "scc-graph"
Private Member Functions
void printDot (std::ostream &os) const
void printJson (std::ostream &os) const
void scR (const AstRelation *relation, std::map< const AstRelation *, int > &preOrder, unsigned &counter, std::stack< const AstRelation * > &S, std::stack< const AstRelation * > &P, unsigned &numSCCs)
Recursive scR method for computing SCC.
Private Attributes
PrecedenceGraph * precedenceGraph
std::vector< std::set< unsigned > > predecessors
Predecessor set for the SCC graph.
std::map< const AstRelation
*, int > relationToScc
Map from node number to SCC number.
std::vector< std::set< const
AstRelation * > > sccToRelation
Relations contained in a SCC.
std::vector< std::set< unsigned > > successors
Adjacency lists for the SCC graph.
Detailed Description
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
Definition at line 103 of file PrecedenceGraph.h.
Member Function Documentation
std::set<const AstRelation*> souffle::SCCGraph::getInbound (const unsigned scc) const inline
Get all relations in a predecessor SCC that have a successor relation in the given SCC.
Definition at line 196 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::graph(), precedenceGraph, relations(), relationToScc, and scc().
Referenced by getIns().
{
         std::set<const AstRelation*> inbound;
         for (const auto& rel : relations(scc)) {
             for (const auto& pred : precedenceGraph->graph().predecessors(rel)) {
                 if ((unsigned)relationToScc.at(pred) != scc) {
                     inbound.insert(pred);
                 }
             }
         }
         return inbound;
     }
std::set<const AstRelation*> souffle::SCCGraph::getInputs (const unsigned scc) const inline
Get all input relations in the given SCC.
Definition at line 174 of file PrecedenceGraph.h.
References relations().
Referenced by getIns().
{
         std::set<const AstRelation*> inputs;
         for (const auto& rel : relations(scc)) {
             if (rel->isInput()) {
                 inputs.insert(rel);
             }
         }
         return inputs;
     }
std::set<const AstRelation*> souffle::SCCGraph::getIns (const unsigned scc) const inline
Get all inbound and all input relations in the given SCC.
Definition at line 158 of file PrecedenceGraph.h.
References getInbound(), and getInputs().
Referenced by printJson().
{
         auto inbound = getInbound(scc);
         const auto inputs = getInputs(scc);
         inbound.insert(inputs.begin(), inputs.end());
         return inbound;
     }
std::set<const AstRelation*> souffle::SCCGraph::getOutbound (const unsigned scc) const inline
Get all relations in the given SCC that have a successor relation in another SCC.
Definition at line 209 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::graph(), precedenceGraph, relations(), relationToScc, and scc().
Referenced by getOuts().
{
         std::set<const AstRelation*> outbound;
         for (const auto& rel : relations(scc)) {
             for (const auto& succ : precedenceGraph->graph().successors(rel)) {
                 if ((unsigned)relationToScc.at(succ) != scc) {
                     outbound.insert(rel);
                     break;
                 }
             }
         }
         return outbound;
     }
std::set<const AstRelation*> souffle::SCCGraph::getOutputs (const unsigned scc) const inline
Get all output relations in the given SCC.
Definition at line 185 of file PrecedenceGraph.h.
References relations().
Referenced by getOuts().
{
         std::set<const AstRelation*> outputs;
         for (const auto& rel : relations(scc)) {
             if (rel->isOutput()) {
                 outputs.insert(rel);
             }
         }
         return outputs;
     }
std::set<const AstRelation*> souffle::SCCGraph::getOuts (const unsigned scc) const inline
Get all outbound and all output relations in the given SCC.
Definition at line 166 of file PrecedenceGraph.h.
References getOutbound(), and getOutputs().
Referenced by printJson().
{
         auto outbound = getOutbound(scc);
         const auto outputs = getOutputs(scc);
         outbound.insert(outputs.begin(), outputs.end());
         return outbound;
     }
bool souffle::SCCGraph::isInSameSCC (const AstRelation * relation1, const AstRelation * relation2) const inline
True if both given relations are in the same SCC, false otherwise.
Definition at line 223 of file PrecedenceGraph.h.
References relationToScc.
{
         return relationToScc.at(relation1) == relationToScc.at(relation2);
     }
bool souffle::SCCGraph::isRecursive (const unsigned scc) const inline
Definition at line 227 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::graph(), precedenceGraph, and sccToRelation.
Referenced by isRecursive(), and souffle::RelationSchedule::run().
{
         const std::set<const AstRelation*>& sccRelations = sccToRelation.at(scc);
         if (sccRelations.size() == 1) {
             const AstRelation* singleRelation = *sccRelations.begin();
             if (!precedenceGraph->graph().predecessors(singleRelation).count(singleRelation)) {
                 return false;
             }
         }
         return true;
     }
bool souffle::SCCGraph::isRecursive (const AstRelation * relation) const inline
Definition at line 238 of file PrecedenceGraph.h.
References isRecursive(), and scc().
{
         return isRecursive(scc(relation));
     }
const std::set<unsigned>& souffle::SCCGraph::predecessorSCCs (const unsigned scc) const inline
Get all predecessor SCCs of a specified scc.
Definition at line 143 of file PrecedenceGraph.h.
References predecessors.
{
         return predecessors.at(scc);
     }
void souffle::SCCGraph::print (std::ostream & os, const std::string & format) const
Definition at line 368 of file PrecedenceGraph.cpp.
References ERROR.
Referenced by print().
{
     if (format == "dot")
         printDot(os);
     else if (format == "json")
         printJson(os);
     else
         ERROR("unrecognised file format.");
 }
void souffle::SCCGraph::print (std::ostream & os) const override virtual
Output strongly connected component graph in graphviz format.
Reimplemented from souffle::AstAnalysis.
Definition at line 256 of file PrecedenceGraph.cpp.
References print().
{
     print(os, "dot");
 }
void souffle::SCCGraph::printDot (std::ostream & os) const private
Definition at line 260 of file PrecedenceGraph.cpp.
References souffle::Global::config(), souffle::AstRelation::getName(), souffle::join(), name, relations(), scc(), size(), and successorSCCs().
{
     const std::string& name = Global::config().get("name");
     /* Print SCC graph */
     os << "digraph {" << std::endl;
     /* Print nodes of SCC graph */
     for (unsigned scc = 0; scc < size(); scc++) {
         os << "\t" << name << "_" << scc << "[label = \"";
         os << join(relations(scc), ",\\n",
                 [](std::ostream& out, const AstRelation* rel) { out << rel->getName(); });
         os << "\" ];" << std::endl;
     }
     for (unsigned scc = 0; scc < size(); scc++) {
         for (unsigned succ : successorSCCs(scc)) {
             os << "\t" << name << "_" << scc << " -> " << name << "_" << succ << ";" << std::endl;
         }
     }
     os << "}";
 }
void souffle::SCCGraph::printJson (std::ostream & os) const private
Definition at line 279 of file PrecedenceGraph.cpp.
References souffle::baseName(), souffle::Global::config(), getIns(), souffle::AstRelation::getName(), getOuts(), souffle::join(), name, relations(), scc(), souffle::simpleName(), and size().
{
     // prefix the vertices by the 'name' of the program
     std::string name;
     if (Global::config().has("dl-program"))
         name = Global::config().get("dl-program");
     else if (Global::config().has("generate"))
         name = Global::config().get("generate");
     else
         name = Global::config().get("");
     name = simpleName(baseName(name));
     /*
      * {
      */
     os << "{" << std::endl;
     /*
      *  vertices: {
      *   scc_1: { on: [rel_1, rel_2, ..., rel_m1], out: ..., in: ... },
      *   scc_2: { on: [rel_1, rel_2, ..., rel_m2], out: ..., in: ... },
      *   ...
      *   scc_n: { on: [rel_1, rel_2, ..., rel_mn], out: ..., in: ... }
      *  }
      */
     os << "\t\"vertices\": {\n";
     for (unsigned scc = 0; scc < size(); scc++) {
         os << "\t\t\"" << name << "_" << scc << "\": {\n";
         std::map<std::string, std::set<const AstRelation*>> relSets;
         // "on" is all relations for this scc
         relSets["on"] = relations(scc);
         // "in" is all inbound relations + all input relations
         relSets["in"] = getIns(scc);
         // "out" is all outbound relations + all output relations
         relSets["out"] = getOuts(scc);
         size_t relCount = relSets.size();
         for (const auto& rels : relSets) {
             os << "\t\t\t\"" << rels.first << "\": [";
             if (!rels.second.empty()) {
                 os << "\n\t\t\t\t\"";
                 os << join(rels.second, "\",\n\t\t\t\t\"",
                         [](std::ostream& out, const AstRelation* rel) { out << rel->getName(); });
                 os << "\"\n";
                 os << "\t\t\t]";
             } else {
                 os << "]";
             }
             if (--relCount != 0) os << ",";
             os << "\n";
         }
         os << "\t\t}";
         if (scc != size() - 1) os << ",";
         os << "\n";
     }
     os << "\t},\n";
     /*
      *  edges: {
      *   scc_1: { scc_1-1, scc_1-2, ..., scc_1-k },
      *   scc_2: { scc_2-1, scc_2-2, ..., rel_2-k' },
      *   ...
      *   scc_n: { scc_n-1, scc_n-2, ..., scc_n-k'' }
      *  }
      */
     os << "\t\"edges\": {\n";
     for (unsigned scc = 0; scc < size(); scc++) {
         os << "\t\t\"" << name << "_" << scc << "\": [\n";
         const auto& succs = successorSCCs(scc);
         if (!succs.empty()) {
             os << "\t\t\t\"" + name + "_";
             os << join(succs, "\",\n\t\t\t\"" + name + "_",
                     [](std::ostream& out, const unsigned succ) { out << succ; });
             os << "\"\n";
         }
         os << "\t\t]";
         if (scc != size() - 1) os << ",";
         os << "\n";
     }
     os << "\t}\n";
     /*
      * }
      */
     os << "}" << std::endl;
 }
const std::set<const AstRelation*> souffle::SCCGraph::relations (const unsigned scc) const inline
Get the relations for a given scc.
Definition at line 148 of file PrecedenceGraph.h.
References sccToRelation.
Referenced by getInbound(), getInputs(), getOutbound(), getOutputs(), printDot(), printJson(), and run().
{
         return sccToRelation.at(scc);
     }
void souffle::SCCGraph::run (const AstTranslationUnit & translationUnit) override virtual
run analysis for a RAM translation unit
Implements souffle::AstAnalysis.
Definition at line 179 of file PrecedenceGraph.cpp.
References ASSERT, souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), souffle::PrecedenceGraph::graph(), precedenceGraph, predecessors, relations(), relationToScc, sccToRelation, scR(), and successors.
{
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraph>();
     sccToRelation.clear();
     relationToScc.clear();
     predecessors.clear();
     successors.clear();
     /* Compute SCC */
     std::vector<AstRelation*> relations = translationUnit.getProgram()->getRelations();
     unsigned counter = 0;
     unsigned numSCCs = 0;
     std::stack<const AstRelation*> S, P;
     std::map<const AstRelation*, int> preOrder;  // Pre-order number of a node (for Gabow's Algo)
     for (const AstRelation* relation : relations) {
         relationToScc[relation] = preOrder[relation] = -1;
     }
     for (const AstRelation* relation : relations) {
         if (preOrder[relation] == -1) {
             scR(relation, preOrder, counter, S, P, numSCCs);
         }
     }
     /* Build SCC graph */
     successors.resize(numSCCs);
     predecessors.resize(numSCCs);
     for (const AstRelation* u : relations) {
         for (const AstRelation* v : precedenceGraph->graph().predecessors(u)) {
             int scc_u = relationToScc[u];
             int scc_v = relationToScc[v];
             ASSERT(scc_u >= 0 && scc_u < int(numSCCs) && "Wrong range");
             ASSERT(scc_v >= 0 && scc_v < int(numSCCs) && "Wrong range");
             if (scc_u != scc_v) {
                 predecessors[scc_u].insert(scc_v);
                 successors[scc_v].insert(scc_u);
             }
         }
     }
     /* Store the relations for each SCC */
     sccToRelation.resize(numSCCs);
     for (const AstRelation* relation : relations) {
         sccToRelation[relationToScc[relation]].insert(relation);
     }
 }
unsigned souffle::SCCGraph::scc (const AstRelation * relation) const inline
Get the scc of a given relation.
Definition at line 153 of file PrecedenceGraph.h.
References relationToScc.
Referenced by getInbound(), getOutbound(), isRecursive(), printDot(), and printJson().
{
         return relationToScc.at(relation);
     }
void souffle::SCCGraph::scR (const AstRelation * relation, std::map< const AstRelation *, int > & preOrder, unsigned & counter, std::stack< const AstRelation * > & S, std::stack< const AstRelation * > & P, unsigned & numSCCs) private
Recursive scR method for computing SCC.
Definition at line 227 of file PrecedenceGraph.cpp.
References souffle::PrecedenceGraph::graph(), precedenceGraph, and relationToScc.
Referenced by run().
{
     preOrder[w] = counter++;
     S.push(w);
     P.push(w);
     for (const AstRelation* t : precedenceGraph->graph().predecessors(w)) {
         if (preOrder[t] == -1) {
             scR(t, preOrder, counter, S, P, numSCCs);
         } else if (relationToScc[t] == -1) {
             while (preOrder[P.top()] > preOrder[t]) {
                 P.pop();
             }
         }
     }
     if (P.top() == w) {
         P.pop();
     } else {
         return;
     }
     const AstRelation* v;
     do {
         v = S.top();
         S.pop();
         relationToScc[v] = numSCCs;
     } while (v != w);
     numSCCs++;
 }
size_t souffle::SCCGraph::size () const inline
Return the number of strongly connected components in the SCC graph.
Definition at line 133 of file PrecedenceGraph.h.
References sccToRelation.
Referenced by printDot(), and printJson().
{
         return sccToRelation.size();
     }
const std::set<unsigned>& souffle::SCCGraph::successorSCCs (const unsigned scc) const inline
Get all successor SCCs of a specified scc.
Definition at line 138 of file PrecedenceGraph.h.
References successors.
Referenced by printDot().
{
         return successors.at(scc);
     }
Field Documentation
constexpr const char* souffle::SCCGraph::name = "scc-graph" static
Definition at line 128 of file PrecedenceGraph.h.
Referenced by printDot(), and printJson().
PrecedenceGraph* souffle::SCCGraph::precedenceGraph private
Definition at line 105 of file PrecedenceGraph.h.
Referenced by getInbound(), getOutbound(), isRecursive(), run(), and scR().
std::vector<std::set<unsigned> > souffle::SCCGraph::predecessors private
Predecessor set for the SCC graph.
Definition at line 114 of file PrecedenceGraph.h.
Referenced by predecessorSCCs(), and run().
std::map<const AstRelation*, int> souffle::SCCGraph::relationToScc private
Map from node number to SCC number.
Definition at line 108 of file PrecedenceGraph.h.
Referenced by getInbound(), getOutbound(), isInSameSCC(), run(), scc(), and scR().
std::vector<std::set<const AstRelation*> > souffle::SCCGraph::sccToRelation private
Relations contained in a SCC.
Definition at line 117 of file PrecedenceGraph.h.
Referenced by isRecursive(), relations(), run(), and size().
std::vector<std::set<unsigned> > souffle::SCCGraph::successors private
Adjacency lists for the SCC graph.
Definition at line 111 of file PrecedenceGraph.h.
Referenced by run(), and successorSCCs().
The documentation for this class was generated from the following files:
PrecedenceGraph.h
PrecedenceGraph.cpp