souffle: souffle::ram::detail::AutoRelation< arity, Indices > Class Template Reference
souffle::ram::detail::AutoRelation< arity, Indices > Class Template Reference
The relation implementing the type if relation utilizing a mixture of different types of data structures for its representation.
#include <CompiledRamRelation.h>
Data Structures
struct covered
Public Types
typedef table_t::iterator iterator
typedef
indices_t::operation_context operation_context
typedef Table< tuple_type > table_t
typedef base::tuple_type tuple_type
Public Types inherited from souffle::ram::detail::RelationBase< arity, AutoRelation< arity, Indices...> >
typedef Tuple< RamDomain, arity > tuple_type
Public Member Functions
iterator begin () const
bool contains (const tuple_type &tuple, operation_context &context) const
operation_context createContext ()
bool empty () const
iterator end () const
template<typename Index >
range< typename
indices_t::template iter_type
< Index >::type > equalRange (const tuple_type &value) const
template<typename Index >
range< typename
indices_t::template iter_type
< Index >::type > equalRange (const tuple_type &value, operation_context &context) const
template<unsigned... Columns>
range< typename
indices_t::template iter_type
< index< Columns...> >::type > equalRange (const tuple_type &value) const
template<unsigned... Columns, typename Context >
range< typename
indices_t::template iter_type
< index< Columns...> >::type > equalRange (const tuple_type &value, Context &ctxt) const
template<typename Setup , typename... Idxs>
void extend (const Relation< Setup, arity, Idxs...> &other)
bool insert (const tuple_type &tuple, operation_context &context)
template<typename Setup , typename... Idxs>
void insertAll (const Relation< Setup, arity, Idxs...> &other)
auto partition () -> decltype(indices.partition(primary_index()))
std::ostream & printDescription (std::ostream &out=std::cout) const
void printHintStatistics (std::ostream &out, const std::string &prefix="") const
void purge ()
template<typename Index >
auto scan () const -> decltype(indices.scan(Index()))
std::size_t size () const
Public Member Functions inherited from souffle::ram::detail::RelationBase< arity, AutoRelation< arity, Indices...> >
bool contains (Args...args) const
bool contains (const tuple_type &tuple) const
std::string getDescription () const
bool insert (Args...args)
bool insert (const RamDomain *ramDomain)
bool insert (const tuple_type &tuple)
void printHintStatistics (std::ostream &out, const std::string &prefix="") const
Private Types
typedef RelationBase< arity,
AutoRelation< arity,
Indices...> > base
typedef std::conditional
< index_utils::contains_full_index
< arity, Indices...>::value,
index_utils::Indices
< tuple_type,
index_utils::index_factory,
Indices...>
, index_utils::Indices
< tuple_type,
index_utils::index_factory,
typename
index_utils::get_full_index
< arity >::type, Indices...>
>::type indices_t
typedef
index_utils::get_first_full_index
< arity, Indices..., typename
index_utils::get_full_index
< arity >::type >::type primary_index
Private Attributes
table_t data
indices_t indices
Lock insert_lock
Detailed Description
template<unsigned arity, typename... Indices>
class souffle::ram::detail::AutoRelation< arity, Indices >
The relation implementing the type if relation utilizing a mixture of different types of data structures for its representation.
The most generic implementation of a relation supporting arbitrary arities > 0 and consistent lists of indices.
The actual data structures are implementation dependent.
Template Parameters
arity .. the arity of the resulting relation
Indices .. the indices to be maintained on top
Definition at line 99 of file CompiledRamRelation.h.
Member Typedef Documentation
template<unsigned arity, typename... Indices> typedef RelationBase<arity, AutoRelation<arity, Indices...> > souffle::ram::detail::AutoRelation< arity, Indices >::base private
Definition at line 306 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> typedef std::conditional< index_utils::contains_full_index<arity, Indices...>::value, index_utils::Indices<tuple_type, index_utils::index_factory, Indices...>, index_utils::Indices<tuple_type, index_utils::index_factory, typename index_utils::get_full_index<arity>::type, Indices...> >::type souffle::ram::detail::AutoRelation< arity, Indices >::indices_t private
Definition at line 330 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> typedef table_t::iterator souffle::ram::detail::AutoRelation< arity, Indices >::iterator
Definition at line 319 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> typedef indices_t::operation_context souffle::ram::detail::AutoRelation< arity, Indices >::operation_context
Definition at line 353 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> typedef index_utils::get_first_full_index<arity, Indices..., typename index_utils::get_full_index<arity>::type>::type souffle::ram::detail::AutoRelation< arity, Indices >::primary_index private
Definition at line 334 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> typedef Table<tuple_type> souffle::ram::detail::AutoRelation< arity, Indices >::table_t
Definition at line 316 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> typedef base::tuple_type souffle::ram::detail::AutoRelation< arity, Indices >::tuple_type
Definition at line 313 of file CompiledRamRelation.h.
Member Function Documentation
template<unsigned arity, typename... Indices> iterator souffle::ram::detail::AutoRelation< arity, Indices >::begin () const inline
Definition at line 450 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< 0 >::equalRange(), souffle::ram::detail::AutoRelation< 0 >::iterator::operator!=(), souffle::ram::detail::AutoRelation< 0 >::iterator::operator++(), souffle::ram::detail::AutoRelation< 0 >::iterator::operator==(), souffle::ram::detail::AutoRelation< 0 >::partition(), and souffle::ram::detail::AutoRelation< 0 >::scan().
{
         return data.begin();
     }
template<unsigned arity, typename... Indices> bool souffle::ram::detail::AutoRelation< arity, Indices >::contains (const tuple_type & tuple, operation_context & context) const inline
Definition at line 373 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::insert().
{
         return indices.contains(tuple, primary_index(), context);
     }
template<unsigned arity, typename... Indices> operation_context souffle::ram::detail::AutoRelation< arity, Indices >::createContext () inline
Definition at line 361 of file CompiledRamRelation.h.
{
         return operation_context();
     }
template<unsigned arity, typename... Indices> bool souffle::ram::detail::AutoRelation< arity, Indices >::empty () const inline
Definition at line 365 of file CompiledRamRelation.h.
{
         return data.empty();
     }
template<unsigned arity, typename... Indices> iterator souffle::ram::detail::AutoRelation< arity, Indices >::end () const inline
Definition at line 454 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< 0 >::equalRange(), souffle::ram::detail::AutoRelation< 0 >::partition(), and souffle::ram::detail::AutoRelation< 0 >::scan().
{
         return data.end();
     }
template<unsigned arity, typename... Indices> template<typename Index > range<typename indices_t::template iter_type<Index>::type> souffle::ram::detail::AutoRelation< arity, Indices >::equalRange (const tuple_type & value) const inline
Definition at line 426 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::equalRange(), and souffle::ram::detail::AutoRelation< 0 >::equalRange().
{
         operation_context ctxt;
         return equalRange<Index>(value, ctxt);
     }
template<unsigned arity, typename... Indices> template<typename Index > range<typename indices_t::template iter_type<Index>::type> souffle::ram::detail::AutoRelation< arity, Indices >::equalRange (const tuple_type & value, operation_context & context) const inline
Definition at line 432 of file CompiledRamRelation.h.
{
         static_assert(covered<Index>::value, "Addressing uncovered index!");
         return indices.template equalRange<Index>(value, context);
     }
template<unsigned arity, typename... Indices> template<unsigned... Columns> range<typename indices_t::template iter_type<index<Columns...> >::type> souffle::ram::detail::AutoRelation< arity, Indices >::equalRange (const tuple_type & value) const inline
Definition at line 439 of file CompiledRamRelation.h.
{
         return equalRange<index<Columns...>>(value);
     }
template<unsigned arity, typename... Indices> template<unsigned... Columns, typename Context > range<typename indices_t::template iter_type<index<Columns...> >::type> souffle::ram::detail::AutoRelation< arity, Indices >::equalRange (const tuple_type & value, Context & ctxt) const inline
Definition at line 445 of file CompiledRamRelation.h.
{
         return equalRange<index<Columns...>>(value, ctxt);
     }
template<unsigned arity, typename... Indices> template<typename Setup , typename... Idxs> void souffle::ram::detail::AutoRelation< arity, Indices >::extend (const Relation< Setup, arity, Idxs...> & other) inline
Definition at line 406 of file CompiledRamRelation.h.
{
         data.extend(other.data);
     }
template<unsigned arity, typename... Indices> bool souffle::ram::detail::AutoRelation< arity, Indices >::insert (const tuple_type & tuple, operation_context & context) inline
Definition at line 377 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< 0 >::insert(), and souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::insertAll().
{
         // the pointer to the inserted tuple in the table
         const tuple_type* masterCopy = nullptr;
         // check primary index first
         {
             // acquire exclusive access to the primary index
             auto lease = insert_lock.acquire();
             // if already present => skip
             if (contains(tuple, context)) return false;
             // add value to table
             masterCopy = &data.insert(tuple);
             // add tuple to primary index
             indices.getIndex(primary_index()).insert(*masterCopy, context.getForIndex(primary_index()));
             // release lease (automatically)
         }
         // insert into remaining indices (and primary again but the context will make it quick)
         indices.insert(*masterCopy, context);
         // new element has been added
         return true;
     }
template<unsigned arity, typename... Indices> template<typename Setup , typename... Idxs> void souffle::ram::detail::AutoRelation< arity, Indices >::insertAll (const Relation< Setup, arity, Idxs...> & other) inline
Definition at line 411 of file CompiledRamRelation.h.
{
         operation_context context;
         for (const tuple_type& cur : other) {
             insert(cur, context);
         }
     }
template<unsigned arity, typename... Indices> auto souffle::ram::detail::AutoRelation< arity, Indices >::partition () -> decltype(indices.partition(primary_index())) inline
Definition at line 463 of file CompiledRamRelation.h.
{
         return indices.partition(primary_index());
     }
template<unsigned arity, typename... Indices> std::ostream& souffle::ram::detail::AutoRelation< arity, Indices >::printDescription (std::ostream & out = std::cout) const inline
Definition at line 468 of file CompiledRamRelation.h.
{
         out << "Relation of arity=" << arity << " with indices [ ";
         indices.printDescription(out);
         out << " ] where " << primary_index() << " is the primary index";
         return out;
     }
template<unsigned arity, typename... Indices> void souffle::ram::detail::AutoRelation< arity, Indices >::printHintStatistics (std::ostream & out, const std::string & prefix = "") const inline
Definition at line 476 of file CompiledRamRelation.h.
{
         indices.printHintStatistics(out, prefix);
     }
template<unsigned arity, typename... Indices> void souffle::ram::detail::AutoRelation< arity, Indices >::purge () inline
Definition at line 458 of file CompiledRamRelation.h.
                  {
         data.clear();
         indices.clear();
     }
template<unsigned arity, typename... Indices> template<typename Index > auto souffle::ram::detail::AutoRelation< arity, Indices >::scan () const -> decltype(indices.scan(Index())) inline
Definition at line 419 of file CompiledRamRelation.h.
{
         return indices.scan(Index());
     }
template<unsigned arity, typename... Indices> std::size_t souffle::ram::detail::AutoRelation< arity, Indices >::size () const inline
Definition at line 369 of file CompiledRamRelation.h.
{
         return data.size();
     }
Field Documentation
template<unsigned arity, typename... Indices> table_t souffle::ram::detail::AutoRelation< arity, Indices >::data private
Definition at line 337 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::begin(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::empty(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::end(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::extend(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::insert(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::purge(), and souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::size().
template<unsigned arity, typename... Indices> indices_t souffle::ram::detail::AutoRelation< arity, Indices >::indices private
Definition at line 340 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::contains(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::equalRange(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::insert(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::partition(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::printDescription(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::printHintStatistics(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::purge(), and souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::scan().
template<unsigned arity, typename... Indices> Lock souffle::ram::detail::AutoRelation< arity, Indices >::insert_lock private
Definition at line 343 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::insert().
The documentation for this class was generated from the following file:
CompiledRamRelation.h