souffle: souffle::BindingStore Class Reference
souffle::BindingStore Class Reference
#include <MagicSet.h>
Public Member Functions
void addBinding (std::string newVariableName, const AstArgument *arg)
void addVariableBoundComposite (std::string functorName)
AstArgument * cloneOriginalArgument (const std::string &argName) const
const std::set< std::string > & getVariableDependencies (const std::string &argName) const
bool isVariableBoundComposite (std::string functorName) const
Private Attributes
std::map< std::string,
std::unique_ptr< AstArgument > > originalArguments
std::map< std::string,
std::set< std::string > > varDependencies
std::set< std::string > variableBoundComposites
Detailed Description
Definition at line 123 of file MagicSet.h.
Member Function Documentation
void souffle::BindingStore::addBinding (std::string newVariableName, const AstArgument * arg) inline
Definition at line 138 of file MagicSet.h.
References souffle::AstArgument::clone(), souffle::AstVariable::getName(), originalArguments, varDependencies, and souffle::visitDepthFirst().
Referenced by souffle::bindComposites().
{
         originalArguments[newVariableName] = std::unique_ptr<AstArgument>(arg->clone());
         // find the variable dependencies
         std::set<std::string> dependencies;
         visitDepthFirst(*arg, [&](const AstVariable& var) { dependencies.insert(var.getName()); });
         varDependencies[newVariableName] = dependencies;
     }
void souffle::BindingStore::addVariableBoundComposite (std::string functorName) inline
Definition at line 147 of file MagicSet.h.
References variableBoundComposites.
Referenced by souffle::isBoundComposite().
{
         variableBoundComposites.insert(functorName);
     }
AstArgument* souffle::BindingStore::cloneOriginalArgument (const std::string & argName) const inline
Definition at line 130 of file MagicSet.h.
References originalArguments.
{
         return originalArguments.at(argName)->clone();
     }
const std::set<std::string>& souffle::BindingStore::getVariableDependencies (const std::string & argName) const inline
Definition at line 134 of file MagicSet.h.
References varDependencies.
Referenced by souffle::isBoundComposite().
{
         return varDependencies.at(argName);
     }
bool souffle::BindingStore::isVariableBoundComposite (std::string functorName) const inline
Definition at line 151 of file MagicSet.h.
References variableBoundComposites.
{
         return (variableBoundComposites.find(functorName) != variableBoundComposites.end());
     }
Field Documentation
std::map<std::string, std::unique_ptr<AstArgument> > souffle::BindingStore::originalArguments private
Definition at line 125 of file MagicSet.h.
Referenced by addBinding(), and cloneOriginalArgument().
std::map<std::string, std::set<std::string> > souffle::BindingStore::varDependencies private
Definition at line 126 of file MagicSet.h.
Referenced by addBinding(), and getVariableDependencies().
std::set<std::string> souffle::BindingStore::variableBoundComposites private
Definition at line 127 of file MagicSet.h.
Referenced by addVariableBoundComposite(), and isVariableBoundComposite().
The documentation for this class was generated from the following file:
MagicSet.h