souffle: souffle::InterpreterProgInterface Class Reference
souffle::InterpreterProgInterface Class Reference
Implementation of SouffleProgram interface for an interpreter instance.
#include <InterpreterInterface.h>
Public Member Functions
void dumpInputs (std::ostream &) override
Dump inputs: not implemented.
void dumpOutputs (std::ostream &) override
Dump outputs: not implemented.
void executeSubroutine (std::string name, const std::vector< RamDomain > &args, std::vector< RamDomain > &ret, std::vector< bool > &err) override
Run subroutine.
const SymbolTable & getSymbolTable () const override
Get symbol table.
InterpreterProgInterface (const RamTranslationUnit &tu, Interpreter &e, InterpreterEnvironment &r)
void loadAll (std::string) override
Load input data: not implemented.
void printAll (std::string) override
Print output data: not implemented.
void run () override
Run program instance: not implemented.
void runAll (std::string, std::string) override
Load data, run program instance, store data: not implemented.
virtual ~InterpreterProgInterface ()
Public Member Functions inherited from souffle::SouffleProgram
std::vector< Relation * > getAllRelations () const
std::vector< Relation * > getInputRelations () const
std::vector< Relation * > getInternalRelations () const
std::vector< Relation * > getOutputRelations () const
Relation * getRelation (const std::string &name) const
virtual ~SouffleProgram ()
Private Attributes
InterpreterEnvironment & env
Interpreter & exec
std::vector
< InterpreterRelInterface * > interfaces
const RamProgram & prog
SymbolTable & symTable
Additional Inherited Members
Protected Member Functions inherited from souffle::SouffleProgram
void addRelation (const std::string &name, Relation *rel, bool isInput, bool isOutput)
Detailed Description
Implementation of SouffleProgram interface for an interpreter instance.
Definition at line 201 of file InterpreterInterface.h.
Constructor & Destructor Documentation
souffle::InterpreterProgInterface::InterpreterProgInterface (const RamTranslationUnit & tu, Interpreter & e, InterpreterEnvironment & r) inline
Definition at line 210 of file InterpreterInterface.h.
References souffle::SouffleProgram::addRelation(), ASSERT, souffle::RamRelation::getArg(), souffle::RamRelation::getArgTypeQualifier(), souffle::RamRelation::getArity(), souffle::RamProgram::getMain(), souffle::RamRelation::getName(), souffle::InterpreterEnvironment::getRelationMap(), interfaces, map, name, prog, types, and souffle::visitDepthFirst().
             : prog(*tu.getProgram()), exec(e), env(r), symTable(tu.getSymbolTable()) {
         uint32_t id = 0;
         // Retrieve AST Relations and store them in a map
         std::map<std::string, const RamRelation*> map;
         visitDepthFirst(*(prog.getMain()), [&](const RamRelation& rel) { map[rel.getName()] = &rel; });
         // Build wrapper relations for Souffle's interface
         for (auto& rel_pair : r.getRelationMap()) {
             auto& name = rel_pair.first;
             auto& interpreterRel = *rel_pair.second;
             ASSERT(map[name]);
             const RamRelation& rel = *map[name];
             // construct types and names vectors
             std::vector<std::string> types;
             std::vector<std::string> attrNames;
             for (size_t i = 0; i < rel.getArity(); i++) {
                 std::string t = rel.getArgTypeQualifier(i);
                 types.push_back(t);
                 std::string n = rel.getArg(i);
                 attrNames.push_back(n);
             }
             InterpreterRelInterface* interface = new InterpreterRelInterface(interpreterRel, symTable,
                     rel.getName(), types, attrNames, rel.isInput(), rel.isOutput(), id);
             interfaces.push_back(interface);
             addRelation(rel.getName(), interface, rel.isInput(), rel.isOutput());
             id++;
         }
     }
virtual souffle::InterpreterProgInterface::~InterpreterProgInterface () inline virtual
Definition at line 242 of file InterpreterInterface.h.
References interfaces.
{
         for (auto* interface : interfaces) {
             delete interface;
         }
     }
Member Function Documentation
void souffle::InterpreterProgInterface::dumpInputs (std::ostream &) inline override virtual
Dump inputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 261 of file InterpreterInterface.h.
 {}
void souffle::InterpreterProgInterface::dumpOutputs (std::ostream &) inline override virtual
Dump outputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 264 of file InterpreterInterface.h.
 {}
void souffle::InterpreterProgInterface::executeSubroutine (std::string name, const std::vector< RamDomain > & args, std::vector< RamDomain > & ret, std::vector< bool > & err) inline override virtual
Run subroutine.
Reimplemented from souffle::SouffleProgram.
Definition at line 267 of file InterpreterInterface.h.
References env, exec, souffle::Interpreter::executeSubroutine(), souffle::RamProgram::getSubroutine(), and prog.
{
         exec.executeSubroutine(env, prog.getSubroutine(name), args, ret, err);
     }
const SymbolTable& souffle::InterpreterProgInterface::getSymbolTable () const inline override virtual
Get symbol table.
Implements souffle::SouffleProgram.
Definition at line 273 of file InterpreterInterface.h.
References symTable.
{
         return symTable;
     }
void souffle::InterpreterProgInterface::loadAll (std::string) inline override virtual
Load input data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 255 of file InterpreterInterface.h.
 {}
void souffle::InterpreterProgInterface::printAll (std::string) inline override virtual
Print output data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 258 of file InterpreterInterface.h.
 {}
void souffle::InterpreterProgInterface::run () inline override virtual
Run program instance: not implemented.
Reimplemented from souffle::SouffleProgram.
Definition at line 249 of file InterpreterInterface.h.
 {}
void souffle::InterpreterProgInterface::runAll (std::string , std::string) inline override virtual
Load data, run program instance, store data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 252 of file InterpreterInterface.h.
 {}
Field Documentation
InterpreterEnvironment& souffle::InterpreterProgInterface::env private
Definition at line 205 of file InterpreterInterface.h.
Referenced by executeSubroutine().
Interpreter& souffle::InterpreterProgInterface::exec private
Definition at line 204 of file InterpreterInterface.h.
Referenced by executeSubroutine().
std::vector<InterpreterRelInterface*> souffle::InterpreterProgInterface::interfaces private
Definition at line 207 of file InterpreterInterface.h.
Referenced by InterpreterProgInterface(), and ~InterpreterProgInterface().
const RamProgram& souffle::InterpreterProgInterface::prog private
Definition at line 203 of file InterpreterInterface.h.
Referenced by executeSubroutine(), and InterpreterProgInterface().
SymbolTable& souffle::InterpreterProgInterface::symTable private
Definition at line 206 of file InterpreterInterface.h.
Referenced by getSymbolTable().
The documentation for this class was generated from the following file:
InterpreterInterface.h