souffle: souffle::ram::detail::HashRelation< arity, Indices > Class Template Reference
souffle::ram::detail::HashRelation< arity, Indices > Class Template Reference
The relation type utilized to implement relations only utilizing a hash based data structure.
#include <CompiledRamRelation.h>
Data Structures
struct operation_context
Public Types
using iterator = decltype(std::declval< group_type >().template get< full_index >().begin())
Public Types inherited from souffle::ram::detail::RelationBase< arity, HashRelation< arity, Indices...> >
typedef Tuple< RamDomain, arity > tuple_type
Public Member Functions
iterator begin () const
bool contains (const tuple_type &tuple, operation_context &) const
operation_context createContext ()
bool empty () const
iterator end () const
template<typename I >
auto equalRange (const tuple_type &value, operation_context &ctxt) const -> decltype(indices.template equal_range< I >(value))
template<typename I >
auto equalRange (const tuple_type &value) const -> decltype(indices.template equal_range< I >(value))
template<unsigned... Columns>
auto equalRange (const tuple_type &value) const -> decltype(indices.template equal_range< index< Columns...>>(value))
template<unsigned... Columns>
auto equalRange (const tuple_type &value, operation_context &) const -> decltype(indices.template equal_range< index< Columns...>>(value))
bool insert (const tuple_type &tuple, operation_context &)
template<typename Setup , typename... Idxs>
void insertAll (const Relation< Setup, arity, Idxs...> &other)
std::vector< range< iterator > > partition () const
std::ostream & printDescription (std::ostream &out=std::cout) const
void purge ()
template<typename I >
range< iterator > scan () const
std::size_t size () const
Public Member Functions inherited from souffle::ram::detail::RelationBase< arity, HashRelation< arity, Indices...> >
bool contains (Args...args) const
bool contains (const tuple_type &tuple) const
std::string getDescription () const
bool insert (Args...args)
bool insert (const RamDomain *ramDomain)
bool insert (const tuple_type &tuple)
void printHintStatistics (std::ostream &out, const std::string &prefix="") const
Private Types
using base = RelationBase< arity, HashRelation< arity, Indices...>>
using full_index = typename index_utils::get_first_full_index< arity, Indices..., typename index_utils::get_full_index< arity >::type >::type
using group_type = typename std::conditional< index_utils::contains_full_index< arity, Indices...>::value, HashRelationGroup< arity, Indices...>, HashRelationGroup< arity, typename index_utils::get_full_index< arity >::type, Indices...>>::type
using main_index_type = typename std::remove_reference< decltype(std::declval< group_type >().template get< full_index >())>::type
using tuple_type = typename base::tuple_type
Private Member Functions
main_index_type & getMainIndex ()
const main_index_type & getMainIndex () const
Private Attributes
group_type indices
std::mutex lock
Detailed Description
template<unsigned arity, typename... Indices>
class souffle::ram::detail::HashRelation< arity, Indices >
The relation type utilized to implement relations only utilizing a hash based data structure.
Definition at line 206 of file CompiledRamRelation.h.
Member Typedef Documentation
template<unsigned arity, typename... Indices> using souffle::ram::detail::HashRelation< arity, Indices >::base = RelationBase<arity, HashRelation<arity, Indices...>> private
Definition at line 1184 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> using souffle::ram::detail::HashRelation< arity, Indices >::full_index = typename index_utils::get_first_full_index<arity, Indices..., typename index_utils::get_full_index<arity>::type>::type private
Definition at line 1195 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> using souffle::ram::detail::HashRelation< arity, Indices >::group_type = typename std::conditional<index_utils::contains_full_index<arity, Indices...>::value, HashRelationGroup<arity, Indices...>, HashRelationGroup<arity, typename index_utils::get_full_index<arity>::type, Indices...>>::type private
Definition at line 1191 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> using souffle::ram::detail::HashRelation< arity, Indices >::iterator = decltype(std::declval<group_type>().template get<full_index>().begin())
Definition at line 1207 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> using souffle::ram::detail::HashRelation< arity, Indices >::main_index_type = typename std::remove_reference<decltype(std::declval<group_type>().template get<full_index>())>::type private
Definition at line 1198 of file CompiledRamRelation.h.
template<unsigned arity, typename... Indices> using souffle::ram::detail::HashRelation< arity, Indices >::tuple_type = typename base::tuple_type private
Definition at line 1186 of file CompiledRamRelation.h.
Member Function Documentation
template<unsigned arity, typename... Indices> iterator souffle::ram::detail::HashRelation< arity, Indices >::begin () const inline
Definition at line 1277 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex().
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::partition().
{
         return getMainIndex().begin();
     }
template<unsigned arity, typename... Indices> bool souffle::ram::detail::HashRelation< arity, Indices >::contains (const tuple_type & tuple, operation_context &) const inline
Definition at line 1230 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex().
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::insert().
{
         return getMainIndex().contains(tuple);
     }
template<unsigned arity, typename... Indices> operation_context souffle::ram::detail::HashRelation< arity, Indices >::createContext () inline
Definition at line 1218 of file CompiledRamRelation.h.
{
         return {};
     }
template<unsigned arity, typename... Indices> bool souffle::ram::detail::HashRelation< arity, Indices >::empty () const inline
Definition at line 1222 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex().
{
         return getMainIndex().empty();
     }
template<unsigned arity, typename... Indices> iterator souffle::ram::detail::HashRelation< arity, Indices >::end () const inline
Definition at line 1281 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex().
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::partition().
{
         return getMainIndex().end();
     }
template<unsigned arity, typename... Indices> template<typename I > auto souffle::ram::detail::HashRelation< arity, Indices >::equalRange (const tuple_type & value, operation_context & ctxt) const -> decltype(indices.template equal_range<I>(value)) inline
Definition at line 1255 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::indices.
{
         return indices.template equal_range<I>(value);
     }
template<unsigned arity, typename... Indices> template<typename I > auto souffle::ram::detail::HashRelation< arity, Indices >::equalRange (const tuple_type & value) const -> decltype(indices.template equal_range<I>(value)) inline
Definition at line 1261 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::indices.
{
         return indices.template equal_range<I>(value);
     }
template<unsigned arity, typename... Indices> template<unsigned... Columns> auto souffle::ram::detail::HashRelation< arity, Indices >::equalRange (const tuple_type & value) const -> decltype(indices.template equal_range<index<Columns...>>(value)) inline
Definition at line 1266 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::indices.
{
         return indices.template equal_range<index<Columns...>>(value);
     }
template<unsigned arity, typename... Indices> template<unsigned... Columns> auto souffle::ram::detail::HashRelation< arity, Indices >::equalRange (const tuple_type & value, operation_context &) const -> decltype(indices.template equal_range<index<Columns...>>(value)) inline
Definition at line 1272 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::indices.
{
         return indices.template equal_range<index<Columns...>>(value);
     }
template<unsigned arity, typename... Indices> main_index_type& souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex () inline private
Definition at line 1318 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::indices.
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::begin(), souffle::ram::detail::HashRelation< arity, Indices >::contains(), souffle::ram::detail::HashRelation< arity, Indices >::empty(), souffle::ram::detail::HashRelation< arity, Indices >::end(), souffle::ram::detail::HashRelation< arity, Indices >::scan(), and souffle::ram::detail::HashRelation< arity, Indices >::size().
{
         return indices.template get<full_index>();
     }
template<unsigned arity, typename... Indices> const main_index_type& souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex () const inline private
Definition at line 1322 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::indices.
{
         return indices.template get<full_index>();
     }
template<unsigned arity, typename... Indices> bool souffle::ram::detail::HashRelation< arity, Indices >::insert (const tuple_type & tuple, operation_context &) inline
Definition at line 1234 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::contains(), souffle::ram::detail::HashRelation< arity, Indices >::indices, and souffle::ram::detail::HashRelation< arity, Indices >::lock.
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::insertAll().
{
         std::lock_guard<std::mutex> guard(lock);
         if (contains(tuple)) return false;
         indices.insert(tuple);
         return true;
     }
template<unsigned arity, typename... Indices> template<typename Setup , typename... Idxs> void souffle::ram::detail::HashRelation< arity, Indices >::insertAll (const Relation< Setup, arity, Idxs...> & other) inline
Definition at line 1242 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::insert().
{
         for (const tuple_type& cur : other) {
             insert(cur);
         }
     }
template<unsigned arity, typename... Indices> std::vector<range<iterator> > souffle::ram::detail::HashRelation< arity, Indices >::partition () const inline
Definition at line 1289 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::begin(), souffle::ram::detail::HashRelation< arity, Indices >::end(), and souffle::ram::detail::HashRelation< arity, Indices >::size().
{
         // split it up in 100 partitions
         auto n = size();
         auto s = n / 100;
         std::vector<range<iterator>> res;
         auto cur = begin();
         auto last = cur;
         int i = 0;
         while (cur != end()) {
             cur++;
             i++;
             if (i > s) {
                 res.push_back({last, cur});
                 last = cur;
             }
         }
         if (cur != last) {
             res.push_back({last, cur});
         }
         return res;
     }
template<unsigned arity, typename... Indices> std::ostream& souffle::ram::detail::HashRelation< arity, Indices >::printDescription (std::ostream & out = std::cout) const inline
Definition at line 1312 of file CompiledRamRelation.h.
References arity.
{
         out << "Hash-based Relation of arity=" << arity;
         return out;
     }
template<unsigned arity, typename... Indices> void souffle::ram::detail::HashRelation< arity, Indices >::purge () inline
Definition at line 1285 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::indices.
                  {
         indices.clear();
     }
template<unsigned arity, typename... Indices> template<typename I > range<iterator> souffle::ram::detail::HashRelation< arity, Indices >::scan () const inline
Definition at line 1249 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex().
{
         const auto& index = getMainIndex();
         return {index.begin(), index.end()};
     }
template<unsigned arity, typename... Indices> std::size_t souffle::ram::detail::HashRelation< arity, Indices >::size () const inline
Definition at line 1226 of file CompiledRamRelation.h.
References souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex().
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::partition().
{
         return getMainIndex().size();
     }
Field Documentation
template<unsigned arity, typename... Indices> group_type souffle::ram::detail::HashRelation< arity, Indices >::indices private
Definition at line 1201 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::equalRange(), souffle::ram::detail::HashRelation< arity, Indices >::getMainIndex(), souffle::ram::detail::HashRelation< arity, Indices >::insert(), and souffle::ram::detail::HashRelation< arity, Indices >::purge().
template<unsigned arity, typename... Indices> std::mutex souffle::ram::detail::HashRelation< arity, Indices >::lock private
Definition at line 1204 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::HashRelation< arity, Indices >::insert().
The documentation for this class was generated from the following file:
CompiledRamRelation.h