souffle: souffle::AstRecordType Class Reference
souffle::AstRecordType Class Reference
A record type aggregates a list of fields into a new type.
#include <AstType.h>
Data Structures
struct Field
The type utilized to model a field.
Public Member Functions
void add (const std::string &name, const AstTypeIdentifier &type)
Adds a new field to this record type.
AstRecordType ()
Creates a new record type.
AstRecordType * clone () const override
Creates a clone if this AST sub-structure.
const std::vector< Field > & getFields () const
Obtains the list of field constituting this record type.
void print (std::ostream &os) const override
Prints a summary of this type to the given stream.
Public Member Functions inherited from souffle::AstType
void apply (const AstNodeMapper &) override
Mutates this node.
AstType (const AstTypeIdentifier &name="")
Creates a new type.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const AstTypeIdentifier & getName () const
Obtains the name of this type.
void setName (const AstTypeIdentifier &name)
Updates the name of this type.
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
AstSrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const AstSrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Private Attributes
std::vector< Field > fields
The list of fields constituting this record type.
Detailed Description
A record type aggregates a list of fields into a new type.
Each record type has a name making it unique. Two record types are unrelated to all other types (they do not have any super or sub types).
Definition at line 242 of file AstType.h.
Constructor & Destructor Documentation
souffle::AstRecordType::AstRecordType () inline
Creates a new record type.
Definition at line 260 of file AstType.h.
Referenced by clone().
 {}
Member Function Documentation
void souffle::AstRecordType::add (const std::string & name, const AstTypeIdentifier & type) inline
Adds a new field to this record type.
Definition at line 263 of file AstType.h.
References fields, and souffle::AstType::name.
{
         fields.push_back(Field({name, type}));
     }
AstRecordType* souffle::AstRecordType::clone () const inline override virtual
Creates a clone if this AST sub-structure.
Implements souffle::AstType.
Definition at line 288 of file AstType.h.
References AstRecordType(), fields, and souffle::AstType::getName().
{
         auto res = new AstRecordType();
         res->setName(getName());
         res->fields = fields;
         return res;
     }
bool souffle::AstRecordType::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 297 of file AstType.h.
References fields, souffle::AstType::getName(), and node.
{
         assert(dynamic_cast<const AstRecordType*>(&node));
         const AstRecordType& other = static_cast<const AstRecordType&>(node);
         return getName() == other.getName() && fields == other.fields;
     }
const std::vector<Field>& souffle::AstRecordType::getFields () const inline
Obtains the list of field constituting this record type.
Definition at line 268 of file AstType.h.
References fields.
Referenced by souffle::AstSemanticChecker::checkRecordType().
{
         return fields;
     }
void souffle::AstRecordType::print (std::ostream & os) const inline override virtual
Prints a summary of this type to the given stream.
Implements souffle::AstNode.
Definition at line 273 of file AstType.h.
References fields, and souffle::AstType::getName().
{
         os << ".type " << getName() << " = "
            << "[";
         for (unsigned i = 0; i < fields.size(); i++) {
             if (i != 0) {
                 os << ",";
             }
             os << fields[i].name;
             os << ":";
             os << fields[i].type;
         }
         os << "]";
     }
Field Documentation
std::vector<Field> souffle::AstRecordType::fields private
The list of fields constituting this record type.
Definition at line 256 of file AstType.h.
Referenced by add(), clone(), equal(), getFields(), and print().
The documentation for this class was generated from the following file:
AstType.h