souffle: souffle::Logger Class Reference
souffle::Logger Class Reference
The class utilized to times for the souffle profiling tool.
#include <Logger.h>
Public Member Functions
Logger (const char *label, std::ostream &out=std::cout)
~Logger ()
Private Types
typedef std::chrono::steady_clock clock
typedef clock::time_point time
Private Attributes
const char * label
std::ostream & out
time start
Detailed Description
The class utilized to times for the souffle profiling tool.
This class is utilized by both – the interpreted and compiled version – to conduct the corresponding measurements.
To far, only execution times are logged. More events, e.g. the number of processed tuples may be added in the future.
Definition at line 43 of file Logger.h.
Member Typedef Documentation
typedef std::chrono::steady_clock souffle::Logger::clock private
Definition at line 45 of file Logger.h.
typedef clock::time_point souffle::Logger::time private
Definition at line 46 of file Logger.h.
Constructor & Destructor Documentation
souffle::Logger::Logger (const char * label, std::ostream & out = std::cout) inline
Definition at line 58 of file Logger.h.
References souffle::now(), and start.
                                                          : label(label), out(out) {
         start = clock::now();
     }
souffle::Logger::~Logger () inline
Definition at line 62 of file Logger.h.
References souffle::Lock::acquire(), souffle::getOutputLock(), souffle::now(), and start.
               {
         auto duration = clock::now() - start;
         auto leas = getOutputLock().acquire();
         (void)leas;  // avoid warning
         out << label << std::chrono::duration_cast<std::chrono::duration<double>>(duration).count()
             << std::endl;
     }
Field Documentation
const char* souffle::Logger::label private
Definition at line 49 of file Logger.h.
std::ostream& souffle::Logger::out private
Definition at line 55 of file Logger.h.
time souffle::Logger::start private
Definition at line 52 of file Logger.h.
Referenced by Logger(), and ~Logger().
The documentation for this class was generated from the following file:
Logger.h