souffle: souffle::Order Class Reference
souffle::Order Class Reference
A class representing the order of predicates in the body of a rule.
#include <Interpreter.h>
Public Member Functions
void append (unsigned pos)
const std::vector< unsigned > & getOrder () const
bool isComplete () const
unsigned operator[] (unsigned index) const
void print (std::ostream &out) const
std::size_t size () const
Static Public Member Functions
static Order getIdentity (unsigned size)
Private Attributes
std::vector< unsigned > order
The covered order.
Friends
std::ostream & operator<< (std::ostream &out, const Order &order)
Detailed Description
A class representing the order of predicates in the body of a rule.
Definition at line 569 of file Interpreter.h.
Member Function Documentation
void souffle::Order::append (unsigned pos) inline
Definition at line 582 of file Interpreter.h.
References order.
Referenced by getIdentity().
{
         order.push_back(pos);
     }
static Order souffle::Order::getIdentity (unsigned size) inline static
Definition at line 574 of file Interpreter.h.
References append(), and size().
{
         Order res;
         for (unsigned i = 0; i < size; i++) {
             res.append(i);
         }
         return res;
     }
const std::vector<unsigned>& souffle::Order::getOrder () const inline
Definition at line 603 of file Interpreter.h.
References order.
{
         return order;
     }
bool souffle::Order::isComplete () const inline
Definition at line 594 of file Interpreter.h.
References souffle::contains(), and order.
{
         for (size_t i = 0; i < order.size(); i++) {
             if (!contains(order, i)) {
                 return false;
             }
         }
         return true;
     }
unsigned souffle::Order::operator[] (unsigned index) const inline
Definition at line 586 of file Interpreter.h.
References order.
{
         return order[index];
     }
void souffle::Order::print (std::ostream & out) const inline
Definition at line 607 of file Interpreter.h.
References order.
{
         out << order;
     }
std::size_t souffle::Order::size () const inline
Definition at line 590 of file Interpreter.h.
References order.
Referenced by getIdentity().
{
         return order.size();
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Order & order) friend
Definition at line 611 of file Interpreter.h.
{
         order.print(out);
         return out;
     }
Field Documentation
std::vector<unsigned> souffle::Order::order private
The covered order.
Definition at line 571 of file Interpreter.h.
Referenced by append(), getOrder(), isComplete(), operator[](), print(), and size().
The documentation for this class was generated from the following file:
Interpreter.h