souffle: souffle::scheduler::Problem< CostModel > Class Template Reference
souffle::scheduler::Problem< CostModel > Class Template Reference
The class summarizing a scheduling problem to be solved utilizing a given cost model.
#include <RuleScheduler.h>
Public Types
typedef CostModel::atom_type atom_type
The type of atom to be utilized.
typedef std::vector< atom_type > plan
The type of an execution plan.
typedef CostModel::state_type state_type
The type of state to be associated to execution plans.
Public Member Functions
void addAtom (const atom_type &atom)
Adds another atom to the list of atoms to be scheduled.
const std::vector< atom_type > & getAtoms () const
Obtains the list of atoms to be scheduled.
void print (std::ostream &out) const
Enables problems to be printed.
Problem (const std::vector< atom_type > &atoms=std::vector< atom_type >())
A constructor for scheduling problems.
plan solve (bool debug=false) const
Obtains a cost-optimal schedule of the atoms to be scheduled based on the underlying cost model.
Private Attributes
std::vector< atom_type > atoms
The atoms to be scheduled.
Friends
std::ostream & operator<< (std::ostream &out, const Problem &p)
Detailed Description
template<typename CostModel>
class souffle::scheduler::Problem< CostModel >
The class summarizing a scheduling problem to be solved utilizing a given cost model.
Definition at line 209 of file RuleScheduler.h.
Member Typedef Documentation
template<typename CostModel > typedef CostModel::atom_type souffle::scheduler::Problem< CostModel >::atom_type
The type of atom to be utilized.
Definition at line 212 of file RuleScheduler.h.
template<typename CostModel > typedef std::vector<atom_type> souffle::scheduler::Problem< CostModel >::plan
The type of an execution plan.
Definition at line 218 of file RuleScheduler.h.
template<typename CostModel > typedef CostModel::state_type souffle::scheduler::Problem< CostModel >::state_type
The type of state to be associated to execution plans.
Definition at line 215 of file RuleScheduler.h.
Constructor & Destructor Documentation
template<typename CostModel > souffle::scheduler::Problem< CostModel >::Problem (const std::vector< atom_type > & atoms = std::vector<atom_type>()) inline
A constructor for scheduling problems.
Definition at line 226 of file RuleScheduler.h.
 : atoms(atoms) {}
Member Function Documentation
template<typename CostModel > void souffle::scheduler::Problem< CostModel >::addAtom (const atom_type & atom) inline
Adds another atom to the list of atoms to be scheduled.
Definition at line 229 of file RuleScheduler.h.
{
         atoms.push_back(atom);
     }
template<typename CostModel > const std::vector<atom_type>& souffle::scheduler::Problem< CostModel >::getAtoms () const inline
Obtains the list of atoms to be scheduled.
Definition at line 234 of file RuleScheduler.h.
{
         return atoms;
     }
template<typename CostModel > void souffle::scheduler::Problem< CostModel >::print (std::ostream & out) const inline
Enables problems to be printed.
Definition at line 320 of file RuleScheduler.h.
References souffle::join().
{
         out << "{ " << join(atoms, ", ") << " }";
     }
template<typename CostModel > plan souffle::scheduler::Problem< CostModel >::solve (bool debug = false) const inline
Obtains a cost-optimal schedule of the atoms to be scheduled based on the underlying cost model.
Definition at line 242 of file RuleScheduler.h.
References souffle::contains(), and souffle::join().
{
         // create an instance of the cost model
         CostModel model;
         // shortcut
         if (atoms.size() < 2) {
             return atoms;  // not much to plan there
         }
         // print some debugging
         if (debug) {
             std::cout << "Processing Problem: " << atoms << "\n";
             // list of memorized results
         }
         map<int, map<plan, state_type>> cache;
         // initialize with empty plan
         cache[0][plan()] = model.getInitState();
         // compute recursive steps
         for (unsigned n = 1; n <= atoms.size(); n++) {
             for (const auto& cur : cache[n - 1]) {
                 const plan& subPlan = cur.first;
                 const state_type& inState = cur.second;
                 for (const auto& cur : atoms) {
                     // only add non-covered steps
                     if (contains(subPlan, cur)) {
                         continue;
                     }
                     // extend plan
                     plan plan = subPlan;
                     plan.push_back(cur);
                     // compute new state and register it
                     cache[n][plan] = model.applyTo(inState, cur);
                 }
             }
         }
         // get best full plan
         state_type best = cache[atoms.size()][atoms];
         plan bestPlan = atoms;
         for (const auto& cur : cache[atoms.size()]) {
             if (cur.second.getCost() < best.getCost()) {
                 best = cur.second;
                 bestPlan = cur.first;
             }
         }
         if (debug) {
             std::cout << "Results:\n"
                       << join(cache, "\n",
                                  [](std::ostream& out, const std::pair<int, map<plan, state_type>>& cur) {
                                      out << cur.first << ":\n\t"
                                          << join(cur.second, "\n\t",
                                                     [](std::ostream& out,
                                                             const std::pair<plan, state_type>& cur) {
                                                         out << "[" << join(cur.first, ",",
                                                                               [](std::ostream& out,
                                                                                       const atom_type& atom) {
                                                                                   out << atom.getID();
                                                                               })
                                                             << "] => " << cur.second;
                                                     })
                                          << "\n";
                                  })
                       << "\n";
             std::cout << "Solution: " << bestPlan << "\n";
         }
         // return best plan
         return bestPlan;
     }
Friends And Related Function Documentation
template<typename CostModel > std::ostream& operator<< (std::ostream & out, const Problem< CostModel > & p) friend
Definition at line 324 of file RuleScheduler.h.
{
         p.print(out);
         return out;
     }
Field Documentation
template<typename CostModel > std::vector<atom_type> souffle::scheduler::Problem< CostModel >::atoms private
The atoms to be scheduled.
Definition at line 222 of file RuleScheduler.h.
The documentation for this class was generated from the following file:
RuleScheduler.h