souffle: souffle::RamTernaryOperator Class Reference
souffle::RamTernaryOperator Class Reference
Ternary Function.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamTernaryOperator * clone () const override
Create clone.
const RamValue * getArg (int i) const
Get argument.
const RamValue & getArgument (int i) const
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () const override
Get level.
TernaryOp getOperator () const
Get operation symbol.
void print (std::ostream &os) const override
Print.
RamTernaryOperator (TernaryOp op, std::unique_ptr< RamValue > a0, std::unique_ptr< RamValue > a1, std::unique_ptr< RamValue > a2)
Public Member Functions inherited from souffle::RamValue
bool isConstant () const
Determines whether this value is a constant or not.
RamValue (RamNodeType type, bool isCnst)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::array< std::unique_ptr
< RamValue >, 3 > arguments
Arguments.
TernaryOp operation
Operation symbol.
Additional Inherited Members
Protected Attributes inherited from souffle::RamValue
bool cnst
Detailed Description
Ternary Function.
Definition at line 230 of file RamValue.h.
Constructor & Destructor Documentation
souffle::RamTernaryOperator::RamTernaryOperator (TernaryOp op, std::unique_ptr< RamValue > a0, std::unique_ptr< RamValue > a1, std::unique_ptr< RamValue > a2) inline
Definition at line 239 of file RamValue.h.
Referenced by clone().
             : RamValue(RN_TernaryOperator, a0->isConstant() && a1->isConstant() && a2->isConstant()),
               operation(op), arguments({{std::move(a0), std::move(a1), std::move(a2)}}) {}
Member Function Documentation
void souffle::RamTernaryOperator::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 293 of file RamValue.h.
References arguments, and map.
{
         for (int i = 0; i < 3; i++) {
             arguments[i] = map(std::move(arguments[i]));
         }
     }
RamTernaryOperator* souffle::RamTernaryOperator::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 284 of file RamValue.h.
References arguments, operation, and RamTernaryOperator().
{
         RamTernaryOperator* res =
                 new RamTernaryOperator(operation, std::unique_ptr<RamValue>(arguments[0]->clone()),
                         std::unique_ptr<RamValue>(arguments[1]->clone()),
                         std::unique_ptr<RamValue>(arguments[2]->clone()));
         return res;
     }
bool souffle::RamTernaryOperator::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 301 of file RamValue.h.
References getArgument(), getOperator(), and node.
{
         assert(dynamic_cast<const RamTernaryOperator*>(&node));
         const RamTernaryOperator& other = static_cast<const RamTernaryOperator&>(node);
         return getOperator() == other.getOperator() && getArgument(0) == other.getArgument(0) &&
                getArgument(1) == other.getArgument(1) && getArgument(2) == other.getArgument(2);
     }
const RamValue* souffle::RamTernaryOperator::getArg (int i) const inline
Get argument.
Definition at line 258 of file RamValue.h.
References arguments.
{
         return arguments[i].get();
     }
const RamValue& souffle::RamTernaryOperator::getArgument (int i) const inline
Definition at line 261 of file RamValue.h.
References arguments, and ASSERT.
Referenced by equal().
{
         ASSERT(arguments[i]);
         return *arguments[i];
     }
std::vector<const RamNode*> souffle::RamTernaryOperator::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 279 of file RamValue.h.
References arguments.
{
         return toVector<const RamNode*>(arguments[0].get(), arguments[1].get(), arguments[2].get());
     }
size_t souffle::RamTernaryOperator::getLevel () const inline override virtual
Get level.
Implements souffle::RamValue.
Definition at line 273 of file RamValue.h.
References arguments.
{
         return std::max(
                 std::max(arguments[0]->getLevel(), arguments[1]->getLevel()), arguments[2]->getLevel());
     }
TernaryOp souffle::RamTernaryOperator::getOperator () const inline
Get operation symbol.
Definition at line 267 of file RamValue.h.
References operation.
Referenced by equal().
{
         return operation;
     }
void souffle::RamTernaryOperator::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 245 of file RamValue.h.
References arguments, souffle::getSymbolForTernaryOp(), and operation.
{
         os << getSymbolForTernaryOp(operation);
         os << "(";
         arguments[0]->print(os);
         os << ",";
         arguments[1]->print(os);
         os << ",";
         arguments[2]->print(os);
         os << ")";
     }
Field Documentation
std::array<std::unique_ptr<RamValue>, 3> souffle::RamTernaryOperator::arguments private
Arguments.
Definition at line 236 of file RamValue.h.
Referenced by apply(), clone(), getArg(), getArgument(), getChildNodes(), getLevel(), and print().
TernaryOp souffle::RamTernaryOperator::operation private
Operation symbol.
Definition at line 233 of file RamValue.h.
Referenced by clone(), getOperator(), and print().
The documentation for this class was generated from the following file:
RamValue.h