souffle: souffle::AstComponent Class Reference
souffle::AstComponent Class Reference
A AST node describing a component within the input program.
#include <AstComponent.h>
Public Member Functions
void addBaseComponent (const AstComponentType &component)
void addClause (std::unique_ptr< AstClause > c)
void addComponent (std::unique_ptr< AstComponent > c)
void addInstantiation (std::unique_ptr< AstComponentInit > i)
void addIODirective (std::unique_ptr< AstIODirective > c)
void addIODirectiveChain (std::unique_ptr< AstIODirective > c)
void addOverride (const std::string &name)
void addRelation (std::unique_ptr< AstRelation > r)
void addType (std::unique_ptr< AstType > t)
void apply (const AstNodeMapper &mapper) override
Applies the node mapper to all child nodes and conducts the corresponding replacements.
AstComponent * clone () const override
Requests an independent, deep copy of this node.
const std::vector
< AstComponentType > & getBaseComponents () const
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
std::vector< AstClause * > getClauses () const
std::vector< AstComponent * > getComponents () const
const AstComponentType & getComponentType () const
std::vector< AstComponentInit * > getInstantiations () const
std::vector< AstIODirective * > getIODirectives () const
const std::set< std::string > & getOverridden () const
std::vector< AstRelation * > getRelations () const
std::vector< AstType * > getTypes () const
void print (std::ostream &os) const override
Output to a given output stream.
void setBaseComponents (const std::vector< AstComponentType > &basis)
void setComponentType (const AstComponentType &type)
~AstComponent () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
AstSrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const AstSrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
An internal function to determine equality to another node.
Private Attributes
std::vector< AstComponentType > baseComponents
A list of base types to inherit relations and clauses from.
std::vector< std::unique_ptr
< AstClause > > clauses
A list of clauses defined in this component.
std::vector< std::unique_ptr
< AstComponent > > components
A list of nested components.
std::vector< std::unique_ptr
< AstComponentInit > > instantiations
A list of nested component instantiations.
std::vector< std::unique_ptr
< AstIODirective > > ioDirectives
A list of IO directives defined in this component.
std::set< std::string > overrideRules
Set of relations that are overwritten.
std::vector< std::unique_ptr
< AstRelation > > relations
A list of relations declared in this component.
AstComponentType type
The type of this component, including its name and type parameters.
std::vector< std::unique_ptr
< AstType > > types
A list of types declared in this component.
Detailed Description
A AST node describing a component within the input program.
Definition at line 177 of file AstComponent.h.
Constructor & Destructor Documentation
souffle::AstComponent::~AstComponent () override default
Member Function Documentation
void souffle::AstComponent::addBaseComponent (const AstComponentType & component) inline
Definition at line 244 of file AstComponent.h.
References baseComponents.
{
         baseComponents.push_back(component);
     }
void souffle::AstComponent::addClause (std::unique_ptr< AstClause > c) inline
Definition at line 264 of file AstComponent.h.
References clauses.
{
         clauses.push_back(std::move(c));
     }
void souffle::AstComponent::addComponent (std::unique_ptr< AstComponent > c) inline
Definition at line 288 of file AstComponent.h.
References components.
{
         components.push_back(std::move(c));
     }
void souffle::AstComponent::addInstantiation (std::unique_ptr< AstComponentInit > i) inline
Definition at line 296 of file AstComponent.h.
References instantiations.
{
         instantiations.push_back(std::move(i));
     }
void souffle::AstComponent::addIODirective (std::unique_ptr< AstIODirective > c) inline
Definition at line 272 of file AstComponent.h.
References ioDirectives.
{
         ioDirectives.push_back(std::move(c));
     }
void souffle::AstComponent::addIODirectiveChain (std::unique_ptr< AstIODirective > c) inline
Definition at line 276 of file AstComponent.h.
References clone(), and ioDirectives.
{
         for (auto& currentName : c->getNames()) {
             std::unique_ptr<AstIODirective> clone(c->clone());
             clone->setName(currentName);
             ioDirectives.push_back(std::move(clone));
         }
     }
void souffle::AstComponent::addOverride (const std::string & name) inline
Definition at line 304 of file AstComponent.h.
References overrideRules.
{
         overrideRules.insert(name);
     }
void souffle::AstComponent::addRelation (std::unique_ptr< AstRelation > r) inline
Definition at line 256 of file AstComponent.h.
References relations.
{
         relations.push_back(std::move(r));
     }
void souffle::AstComponent::addType (std::unique_ptr< AstType > t) inline
Definition at line 248 of file AstComponent.h.
References types.
{
         types.push_back(std::move(t));
     }
void souffle::AstComponent::apply (const AstNodeMapper & mapper) inline override virtual
Applies the node mapper to all child nodes and conducts the corresponding replacements.
Implements souffle::AstNode.
Definition at line 345 of file AstComponent.h.
References clauses, components, instantiations, ioDirectives, relations, and types.
{
         // apply mapper to all sub-nodes
         for (auto& cur : components) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : types) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : ioDirectives) {
             cur = mapper(std::move(cur));
         }
         return;
     }
AstComponent* souffle::AstComponent::clone () const inline override virtual
Requests an independent, deep copy of this node.
Implements souffle::AstNode.
Definition at line 313 of file AstComponent.h.
References clauses, components, getBaseComponents(), getComponentType(), instantiations, ioDirectives, overrideRules, relations, setBaseComponents(), setComponentType(), and types.
Referenced by addIODirectiveChain().
{
         AstComponent* res = new AstComponent();
         res->setComponentType(getComponentType());
         res->setBaseComponents(getBaseComponents());
         for (const auto& cur : components) {
             res->components.push_back(std::unique_ptr<AstComponent>(cur->clone()));
         }
         for (const auto& cur : instantiations) {
             res->instantiations.push_back(std::unique_ptr<AstComponentInit>(cur->clone()));
         }
         for (const auto& cur : types) {
             res->types.push_back(std::unique_ptr<AstType>(cur->clone()));
         }
         for (const auto& cur : relations) {
             res->relations.push_back(std::unique_ptr<AstRelation>(cur->clone()));
         }
         for (const auto& cur : clauses) {
             res->clauses.push_back(std::unique_ptr<AstClause>(cur->clone()));
         }
         for (const auto& cur : ioDirectives) {
             res->ioDirectives.push_back(std::unique_ptr<AstIODirective>(cur->clone()));
         }
         for (const auto& cur : overrideRules) {
             res->overrideRules.insert(cur);
         }
         return res;
     }
bool souffle::AstComponent::equal (const AstNode & node) const inline override protected virtual
An internal function to determine equality to another node.
Implements souffle::AstNode.
Definition at line 431 of file AstComponent.h.
References baseComponents, clauses, components, souffle::equal_targets(), instantiations, ioDirectives, node, relations, type, and types.
{
         assert(dynamic_cast<const AstComponent*>(&node));
         const AstComponent& other = static_cast<const AstComponent&>(node);
         // compare all fields
         return type == other.type && baseComponents == other.baseComponents &&
                equal_targets(types, other.types) && equal_targets(relations, other.relations) &&
                equal_targets(clauses, other.clauses) && equal_targets(ioDirectives, other.ioDirectives) &&
                equal_targets(components, other.components) &&
                equal_targets(instantiations, other.instantiations);
     }
const std::vector<AstComponentType>& souffle::AstComponent::getBaseComponents () const inline
Definition at line 236 of file AstComponent.h.
References baseComponents.
Referenced by souffle::AstComponentChecker::checkComponent(), and clone().
{
         return baseComponents;
     }
std::vector<const AstNode*> souffle::AstComponent::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 370 of file AstComponent.h.
References clauses, components, instantiations, ioDirectives, relations, and types.
{
         std::vector<const AstNode*> res;
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : ioDirectives) {
             res.push_back(cur.get());
         }
         return res;
     }
std::vector<AstClause*> souffle::AstComponent::getClauses () const inline
Definition at line 268 of file AstComponent.h.
References clauses, and souffle::toPtrVector().
{
         return toPtrVector(clauses);
     }
std::vector<AstComponent*> souffle::AstComponent::getComponents () const inline
Definition at line 292 of file AstComponent.h.
References components, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent(), souffle::ComponentLookup::getComponent(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
const AstComponentType& souffle::AstComponent::getComponentType () const inline
Definition at line 228 of file AstComponent.h.
References type.
Referenced by souffle::AstComponentChecker::checkComponent(), souffle::AstComponentChecker::checkComponentReference(), clone(), and print().
{
         return type;
     }
std::vector<AstComponentInit*> souffle::AstComponent::getInstantiations () const inline
Definition at line 300 of file AstComponent.h.
References instantiations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(instantiations);
     }
std::vector<AstIODirective*> souffle::AstComponent::getIODirectives () const inline
Definition at line 284 of file AstComponent.h.
References ioDirectives, and souffle::toPtrVector().
{
         return toPtrVector(ioDirectives);
     }
const std::set<std::string>& souffle::AstComponent::getOverridden () const inline
Definition at line 308 of file AstComponent.h.
References overrideRules.
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return overrideRules;
     }
std::vector<AstRelation*> souffle::AstComponent::getRelations () const inline
Definition at line 260 of file AstComponent.h.
References relations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(relations);
     }
std::vector<AstType*> souffle::AstComponent::getTypes () const inline
Definition at line 252 of file AstComponent.h.
References souffle::toPtrVector(), and types.
{
         return toPtrVector(types);
     }
void souffle::AstComponent::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 396 of file AstComponent.h.
References baseComponents, clauses, components, getComponentType(), instantiations, ioDirectives, souffle::join(), overrideRules, relations, and types.
{
         os << ".comp " << getComponentType() << " ";
         if (!baseComponents.empty()) {
             os << ": " << join(baseComponents, ",") << " ";
         }
         os << "{\n";
         if (!components.empty()) {
             os << join(components, "\n", print_deref<std::unique_ptr<AstComponent>>()) << "\n";
         }
         if (!instantiations.empty()) {
             os << join(instantiations, "\n", print_deref<std::unique_ptr<AstComponentInit>>()) << "\n";
         }
         if (!types.empty()) {
             os << join(types, "\n", print_deref<std::unique_ptr<AstType>>()) << "\n";
         }
         if (!relations.empty()) {
             os << join(relations, "\n", print_deref<std::unique_ptr<AstRelation>>()) << "\n";
         }
         for (const auto& cur : overrideRules) {
             os << ".override " << cur << "\n";
         }
         if (!clauses.empty()) {
             os << join(clauses, "\n\n", print_deref<std::unique_ptr<AstClause>>()) << "\n";
         }
         if (!ioDirectives.empty()) {
             os << join(ioDirectives, "\n\n", print_deref<std::unique_ptr<AstIODirective>>()) << "\n";
         }
         os << "}\n";
     }
void souffle::AstComponent::setBaseComponents (const std::vector< AstComponentType > & basis) inline
Definition at line 240 of file AstComponent.h.
References baseComponents.
Referenced by clone().
{
         baseComponents = basis;
     }
void souffle::AstComponent::setComponentType (const AstComponentType & type) inline
Definition at line 232 of file AstComponent.h.
References type.
Referenced by clone().
{
         this->type = type;
     }
Field Documentation
std::vector<AstComponentType> souffle::AstComponent::baseComponents private
A list of base types to inherit relations and clauses from.
Definition at line 186 of file AstComponent.h.
Referenced by addBaseComponent(), equal(), getBaseComponents(), print(), and setBaseComponents().
std::vector<std::unique_ptr<AstClause> > souffle::AstComponent::clauses private
A list of clauses defined in this component.
Definition at line 201 of file AstComponent.h.
Referenced by addClause(), apply(), clone(), equal(), getChildNodes(), getClauses(), and print().
std::vector<std::unique_ptr<AstComponent> > souffle::AstComponent::components private
A list of nested components.
Definition at line 211 of file AstComponent.h.
Referenced by addComponent(), apply(), clone(), equal(), getChildNodes(), getComponents(), and print().
std::vector<std::unique_ptr<AstComponentInit> > souffle::AstComponent::instantiations private
A list of nested component instantiations.
Definition at line 216 of file AstComponent.h.
Referenced by addInstantiation(), apply(), clone(), equal(), getChildNodes(), getInstantiations(), and print().
std::vector<std::unique_ptr<AstIODirective> > souffle::AstComponent::ioDirectives private
A list of IO directives defined in this component.
Definition at line 206 of file AstComponent.h.
Referenced by addIODirective(), addIODirectiveChain(), apply(), clone(), equal(), getChildNodes(), getIODirectives(), and print().
std::set<std::string> souffle::AstComponent::overrideRules private
Set of relations that are overwritten.
Definition at line 221 of file AstComponent.h.
Referenced by addOverride(), clone(), getOverridden(), and print().
std::vector<std::unique_ptr<AstRelation> > souffle::AstComponent::relations private
A list of relations declared in this component.
Definition at line 196 of file AstComponent.h.
Referenced by addRelation(), apply(), clone(), equal(), getChildNodes(), getRelations(), and print().
AstComponentType souffle::AstComponent::type private
The type of this component, including its name and type parameters.
Definition at line 181 of file AstComponent.h.
Referenced by equal(), getComponentType(), and setComponentType().
std::vector<std::unique_ptr<AstType> > souffle::AstComponent::types private
A list of types declared in this component.
Definition at line 191 of file AstComponent.h.
Referenced by addType(), apply(), clone(), equal(), getChildNodes(), getTypes(), and print().
The documentation for this class was generated from the following file:
AstComponent.h