souffle: souffle::AstPragma Class Reference
souffle::AstPragma Class Reference
Representation of a global option.
#include <AstPragma.h>
Public Member Functions
virtual void apply (const AstNodeMapper &mapper)
No nested nodes to apply to.
AstPragma ()
AstPragma (const std::string &k, const std::string &v)
virtual AstPragma * clone () const
Creates a clone of this AST sub-structure.
virtual std::vector< const
AstNode * > getChildNodes () const
Obtains a list of all embedded child nodes.
std::pair< std::string,
std::string > getkvp () const
virtual void print (std::ostream &os) const
Output to a given output stream.
virtual ~AstPragma ()
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
AstSrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const AstSrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Data Fields
std::string key
Name of the key.
std::string value
Value.
Protected Member Functions
virtual bool equal (const AstNode &node) const
An internal function to determine equality to another node.
Friends
std::ostream & operator<< (std::ostream &out, const AstPragma &arg)
Detailed Description
Representation of a global option.
Definition at line 30 of file AstPragma.h.
Constructor & Destructor Documentation
virtual souffle::AstPragma::~AstPragma () inline virtual
Definition at line 40 of file AstPragma.h.
 {}
souffle::AstPragma::AstPragma () inline
Definition at line 42 of file AstPragma.h.
Referenced by clone().
 {}
souffle::AstPragma::AstPragma (const std::string & k, const std::string & v) inline
Definition at line 44 of file AstPragma.h.
 : key(k), value(v) {}
Member Function Documentation
virtual void souffle::AstPragma::apply (const AstNodeMapper & mapper) inline virtual
No nested nodes to apply to.
Implements souffle::AstNode.
Definition at line 62 of file AstPragma.h.
 {}
virtual AstPragma* souffle::AstPragma::clone () const inline virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Definition at line 53 of file AstPragma.h.
References AstPragma(), souffle::AstNode::getSrcLoc(), key, and value.
{
         auto res = new AstPragma();
         res->key = key;
         res->value = value;
         res->setSrcLoc(getSrcLoc());
         return res;
     }
virtual bool souffle::AstPragma::equal (const AstNode & node) const inline protected virtual
An internal function to determine equality to another node.
Implements souffle::AstNode.
Definition at line 33 of file AstPragma.h.
References key, node, and value.
{
         assert(dynamic_cast<const AstPragma*>(&node));
         const AstPragma& other = static_cast<const AstPragma&>(node);
         return other.key == key && other.value == value;
     }
virtual std::vector<const AstNode*> souffle::AstPragma::getChildNodes () const inline virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 47 of file AstPragma.h.
{
         // type is just cached, not essential
         return std::vector<const AstNode*>();
     }
std::pair<std::string, std::string> souffle::AstPragma::getkvp () const inline
Definition at line 69 of file AstPragma.h.
References key, and value.
Referenced by souffle::AstPragmaChecker::transform().
{
         return std::pair<std::string, std::string>(key, value);
     }
virtual void souffle::AstPragma::print (std::ostream & os) const inline virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 65 of file AstPragma.h.
References key, and value.
{
         os << ".pragma " << key << " " << value << "\n";
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const AstPragma & arg) friend
Definition at line 73 of file AstPragma.h.
{
         out << arg.key << " \"" << arg.value << "\"";
         return out;
     }
Field Documentation
std::string souffle::AstPragma::key
Name of the key.
Definition at line 79 of file AstPragma.h.
Referenced by clone(), equal(), getkvp(), and print().
std::string souffle::AstPragma::value
Value.
Definition at line 82 of file AstPragma.h.
Referenced by clone(), equal(), getkvp(), and print().
The documentation for this class was generated from the following file:
AstPragma.h