souffle: souffle::scheduler::State Class Reference
souffle::scheduler::State Class Reference abstract
The base class for the state associated to a problem after executing a (partial) plan.
#include <RuleScheduler.h>
Public Member Functions
Cost getCost () const
void incCost (Cost inc)
virtual void print (std::ostream &out) const =0
void setCost (Cost cost)
State ()
virtual ~State ()=default
Private Attributes
Cost cost
The cost for reaching this state.
Friends
std::ostream & operator<< (std::ostream &out, const State &s)
Detailed Description
The base class for the state associated to a problem after executing a (partial) plan.
Definition at line 344 of file RuleScheduler.h.
Constructor & Destructor Documentation
souffle::scheduler::State::State () inline
Definition at line 349 of file RuleScheduler.h.
 : cost(0) {}
virtual souffle::scheduler::State::~State () virtual default
Member Function Documentation
Cost souffle::scheduler::State::getCost () const inline
Definition at line 353 of file RuleScheduler.h.
References cost.
Referenced by souffle::scheduler::LogCostModel::applyTo(), souffle::scheduler::BindingState::print(), souffle::scheduler::SimpleComputationalCostState::print(), and souffle::scheduler::ComputeCostState::print().
{
         return cost;
     }
void souffle::scheduler::State::incCost (Cost inc) inline
Definition at line 361 of file RuleScheduler.h.
References cost.
Referenced by souffle::scheduler::MaxBindingModel::applyTo(), souffle::scheduler::SimpleComputationalCostModel::applyTo(), and souffle::scheduler::ComputeCostModel::applyTo().
{
         cost += inc;
     }
virtual void souffle::scheduler::State::print (std::ostream & out) const pure virtual
Implemented in souffle::scheduler::ComputeCostState, souffle::scheduler::SimpleComputationalCostState, and souffle::scheduler::BindingState.
void souffle::scheduler::State::setCost (Cost cost) inline
Definition at line 357 of file RuleScheduler.h.
References cost.
Referenced by souffle::scheduler::LogCostModel::applyTo(), and souffle::scheduler::LogCostModel::getInitState().
{
         this->cost = cost;
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const State & s) friend
Definition at line 367 of file RuleScheduler.h.
{
         s.print(out);
         return out;
     }
Field Documentation
Cost souffle::scheduler::State::cost private
The cost for reaching this state.
Definition at line 346 of file RuleScheduler.h.
Referenced by getCost(), incCost(), and setCost().
The documentation for this class was generated from the following file:
RuleScheduler.h