souffle: souffle::Adornment Class Reference
souffle::Adornment Class Reference
#include <MagicSet.h>
Public Member Functions
const std::vector< std::vector
< AdornedClause > > & getAdornedClauses () const
const BindingStore & getBindings () const
const std::set
< AstRelationIdentifier > & getEDB () const
const std::set
< AstRelationIdentifier > & getIDB () const
const std::set
< AstRelationIdentifier > & getIgnoredAtoms () const
const std::set
< AstRelationIdentifier > & getNegatedAtoms () const
const std::vector
< AstRelationIdentifier > & getRelations () const
void print (std::ostream &os) const
print the analysis result in HTML format
virtual void run (const AstTranslationUnit &translationUnit)
run analysis for a RAM translation unit
~Adornment ()
Public Member Functions inherited from souffle::AstAnalysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "adorned-clauses"
Private Attributes
std::vector< std::vector
< AdornedClause > > adornmentClauses
std::set< AstRelationIdentifier > adornmentEdb
std::set< AstRelationIdentifier > adornmentIdb
std::vector
< AstRelationIdentifier > adornmentRelations
BindingStore bindings
std::set< AstRelationIdentifier > ignoredAtoms
std::set< AstRelationIdentifier > negatedAtoms
Detailed Description
Definition at line 156 of file MagicSet.h.
Constructor & Destructor Documentation
souffle::Adornment::~Adornment () inline
Definition at line 169 of file MagicSet.h.
 {}
Member Function Documentation
const std::vector<std::vector<AdornedClause> >& souffle::Adornment::getAdornedClauses () const inline
Definition at line 175 of file MagicSet.h.
References adornmentClauses.
Referenced by souffle::MagicSetTransformer::transform().
{
         return adornmentClauses;
     }
const BindingStore& souffle::Adornment::getBindings () const inline
Definition at line 199 of file MagicSet.h.
References bindings.
Referenced by souffle::MagicSetTransformer::transform().
{
         return bindings;
     }
const std::set<AstRelationIdentifier>& souffle::Adornment::getEDB () const inline
Definition at line 183 of file MagicSet.h.
References adornmentEdb.
{
         return adornmentEdb;
     }
const std::set<AstRelationIdentifier>& souffle::Adornment::getIDB () const inline
Definition at line 187 of file MagicSet.h.
References adornmentIdb.
Referenced by souffle::MagicSetTransformer::transform().
{
         return adornmentIdb;
     }
const std::set<AstRelationIdentifier>& souffle::Adornment::getIgnoredAtoms () const inline
Definition at line 195 of file MagicSet.h.
References ignoredAtoms.
Referenced by souffle::MagicSetTransformer::transform().
{
         return ignoredAtoms;
     }
const std::set<AstRelationIdentifier>& souffle::Adornment::getNegatedAtoms () const inline
Definition at line 191 of file MagicSet.h.
References negatedAtoms.
Referenced by souffle::MagicSetTransformer::transform().
{
         return negatedAtoms;
     }
const std::vector<AstRelationIdentifier>& souffle::Adornment::getRelations () const inline
Definition at line 179 of file MagicSet.h.
References adornmentRelations.
Referenced by souffle::MagicSetTransformer::transform().
{
         return adornmentRelations;
     }
void souffle::Adornment::print (std::ostream & os) const virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 897 of file MagicSet.cpp.
References adornmentClauses, and adornmentRelations.
{
     for (size_t i = 0; i < adornmentClauses.size(); i++) {
         std::vector<AdornedClause> clauses = adornmentClauses[i];
         os << "Output " << i + 1 << ": " << adornmentRelations[i] << std::endl;
         for (AdornedClause clause : clauses) {
             os << clause << std::endl;
         }
         os << std::endl;
     }
 }
void souffle::Adornment::run (const AstTranslationUnit & translationUnit) virtual
run analysis for a RAM translation unit
Implements souffle::AstAnalysis.
Definition at line 709 of file MagicSet.cpp.
References souffle::addAggregators(), souffle::addForwardDependencies(), souffle::addIgnoredRelations(), adornmentClauses, adornmentEdb, adornmentIdb, adornmentRelations, arity, souffle::bindArguments(), souffle::bindComposites(), bindings, constraints, souffle::contains(), souffle::containsAggregators(), souffle::EQ, souffle::AdornedPredicate::getAdornment(), souffle::AstAtom::getArguments(), souffle::AstRelation::getArity(), souffle::AstNegation::getAtom(), souffle::AstRelation::getClauses(), souffle::AstConstraint::getLHS(), souffle::AdornedPredicate::getName(), souffle::AstAtom::getName(), souffle::getNextAtomSIPS(), souffle::AstConstraint::getOperator(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelation(), souffle::AstProgram::getRelations(), souffle::AstConstraint::getRHS(), souffle::getString(), ignoredAtoms, souffle::isBindingConstraint(), lhs, name, negatedAtoms, rhs, and souffle::visitDepthFirst().
{
     // -------------
     // --- Setup ---
     // -------------
     const AstProgram* program = translationUnit.getProgram();
     // normalises and tracks bindings of composite arguments (namely records and functors)
     BindingStore compositeBindings = bindComposites(program);
     // set up IDB/EDB and the output queries
     std::vector<AstRelationIdentifier> outputQueries;
     std::vector<std::vector<AdornedClause>> adornedProgram;
     // sort out the relations in the program into EDB/IDB and find computed relations
     for (AstRelation* rel : program->getRelations()) {
         AstRelationIdentifier relName = rel->getName();
         // find computed relations for the topdown part
         if (rel->isComputed()) {
             outputQueries.push_back(rel->getName());
             adornmentRelations.push_back(rel->getName());  // add relation to adornment
         }
         // check whether edb or idb
         bool is_edb = true;
         for (AstClause* clause : rel->getClauses()) {
             if (!clause->isFact()) {
                 is_edb = false;
                 break;
             }
         }
         if (is_edb) {
             adornmentEdb.insert(relName);
         } else {
             adornmentIdb.insert(relName);
         }
     }
     // find all negated literals
     visitDepthFirst(*program,
             [&](const AstNegation& negation) { negatedAtoms.insert(negation.getAtom()->getName()); });
     // add the relations needed for negated relations to be computed
     negatedAtoms = addForwardDependencies(program, negatedAtoms);
     // find atoms that should be ignored
     for (AstRelation* rel : program->getRelations()) {
         for (AstClause* clause : rel->getClauses()) {
             // ignore atoms that have rules containing aggregators
             if (containsAggregators(clause)) {
                 ignoredAtoms.insert(clause->getHead()->getName());
             }
             // ignore all atoms used inside an aggregator within the clause
             ignoredAtoms = addAggregators(clause, ignoredAtoms);
         }
     }
     // find atoms that should be ignored based on magic-transform option
     ignoredAtoms = addIgnoredRelations(program, ignoredAtoms);
     // if a relation is ignored, then all the atoms in its bodies need to be ignored
     ignoredAtoms = addForwardDependencies(program, ignoredAtoms);
     // -----------------
     // --- Adornment ---
     // -----------------
     // begin adornment algorithm
     // adornment is performed for each output query separately
     for (size_t querynum = 0; querynum < outputQueries.size(); querynum++) {
         AstRelationIdentifier outputQuery = outputQueries[querynum];
         std::vector<AdornedPredicate> currentPredicates;
         std::set<AdornedPredicate> seenPredicates;
         std::vector<AdornedClause> adornedClauses;
         // create an adorned predicate of the form outputName_ff..f
         size_t arity = program->getRelation(outputQuery)->getArity();
         std::string frepeat = std::string(arity, 'f');  // #fs = #args
         AdornedPredicate outputPredicate(outputQuery, frepeat);
         currentPredicates.push_back(outputPredicate);
         seenPredicates.insert(outputPredicate);
         // keep going through the remaining predicates that need to be adorned
         while (!currentPredicates.empty()) {
             // pop out the first element
             AdornedPredicate currPredicate = currentPredicates[0];
             currentPredicates.erase(currentPredicates.begin());
             // don't bother adorning ignored predicates
             if (contains(ignoredAtoms, currPredicate.getName())) {
                 continue;
             }
             // go through and adorn all IDB clauses defining the relation
             AstRelation* rel = program->getRelation(currPredicate.getName());
             for (AstClause* clause : rel->getClauses()) {
                 if (clause->isFact()) {
                     continue;
                 }
                 size_t numAtoms = clause->getAtoms().size();
                 std::vector<std::string> clauseAtomAdornments(numAtoms);
                 std::vector<unsigned int> ordering(numAtoms);
                 std::set<std::string> boundArgs;
                 // mark all bound arguments in the head as bound
                 AstAtom* clauseHead = clause->getHead();
                 std::string headAdornment = currPredicate.getAdornment();
                 std::vector<AstArgument*> headArguments = clauseHead->getArguments();
                 for (size_t argnum = 0; argnum < headArguments.size(); argnum++) {
                     if (headAdornment[argnum] == 'b') {
                         std::string name = getString(headArguments[argnum]);
                         boundArgs.insert(name);
                     }
                 }
                 // mark all bound arguments from the body
                 std::vector<AstConstraint*> constraints = clause->getConstraints();
                 for (size_t i = 0; i < constraints.size(); i++) {
                     AstConstraint* constraint = constraints[i];
                     BinaryConstraintOp op = constraint->getOperator();
                     if (op != BinaryConstraintOp::EQ) {
                         continue;
                     }
                     AstArgument* lhs = constraint->getLHS();
                     AstArgument* rhs = constraint->getRHS();
                     if (isBindingConstraint(lhs, rhs, boundArgs)) {
                         boundArgs.insert(getString(lhs));
                     }
                     if (isBindingConstraint(rhs, lhs, boundArgs)) {
                         boundArgs.insert(getString(rhs));
                     }
                 }
                 std::vector<AstAtom*> atoms = clause->getAtoms();
                 int atomsAdorned = 0;
                 int atomsTotal = atoms.size();
                 while (atomsAdorned < atomsTotal) {
                     // get the next body atom to adorn based on our SIPS
                     int currIndex = getNextAtomSIPS(atoms, boundArgs, adornmentEdb, compositeBindings);
                     AstAtom* currAtom = atoms[currIndex];
                     AstRelationIdentifier atomName = currAtom->getName();
                     // compute the adornment pattern of this atom, and
                     // add all its arguments to the list of bound args
                     std::pair<std::string, std::set<std::string>> result =
                             bindArguments(currAtom, boundArgs, compositeBindings);
                     std::string atomAdornment = result.first;
                     boundArgs = result.second;
                     // check if we've already dealt with this adornment before
                     if (!contains(seenPredicates, atomName, atomAdornment)) {
                         // not seen before, so push it onto the computation list
                         // and mark it as seen
                         currentPredicates.push_back(AdornedPredicate(atomName, atomAdornment));
                         seenPredicates.insert(AdornedPredicate(atomName, atomAdornment));
                     }
                     clauseAtomAdornments[currIndex] = atomAdornment;  // store the adornment
                     ordering[currIndex] = atomsAdorned;               // mark what atom number this is
                     atoms[currIndex] = nullptr;                       // mark as done
                     atomsAdorned++;
                 }
                 // adornment of this clause is complete - add it to the list of
                 // adorned clauses
                 adornedClauses.push_back(
                         AdornedClause(clause, headAdornment, clauseAtomAdornments, ordering));
             }
         }
         // add the list of adorned clauses matching the current output relation
         adornmentClauses.push_back(adornedClauses);
     }
     this->bindings = std::move(compositeBindings);
 }
Field Documentation
std::vector<std::vector<AdornedClause> > souffle::Adornment::adornmentClauses private
Definition at line 158 of file MagicSet.h.
Referenced by getAdornedClauses(), print(), and run().
std::set<AstRelationIdentifier> souffle::Adornment::adornmentEdb private
Definition at line 160 of file MagicSet.h.
Referenced by getEDB(), and run().
std::set<AstRelationIdentifier> souffle::Adornment::adornmentIdb private
Definition at line 161 of file MagicSet.h.
Referenced by getIDB(), and run().
std::vector<AstRelationIdentifier> souffle::Adornment::adornmentRelations private
Definition at line 159 of file MagicSet.h.
Referenced by getRelations(), print(), and run().
BindingStore souffle::Adornment::bindings private
Definition at line 164 of file MagicSet.h.
Referenced by getBindings(), and run().
std::set<AstRelationIdentifier> souffle::Adornment::ignoredAtoms private
Definition at line 163 of file MagicSet.h.
Referenced by getIgnoredAtoms(), and run().
constexpr const char* souffle::Adornment::name = "adorned-clauses" static
Definition at line 167 of file MagicSet.h.
Referenced by run().
std::set<AstRelationIdentifier> souffle::Adornment::negatedAtoms private
Definition at line 162 of file MagicSet.h.
Referenced by getNegatedAtoms(), and run().
The documentation for this class was generated from the following files:
MagicSet.h
MagicSet.cpp