souffle: souffle::scheduler::ComputeCostState Class Reference
souffle::scheduler::ComputeCostState Class Reference
The state associated to the computational cost model maintaining an estimate to the multiplicity of bound variables and an estimate of innermost loop iterations.
#include <RuleScheduler.h>
Public Member Functions
void bind (const Var &var, uint32_t mult)
ComputeCostState ()
uint64_t getInnermostIterations () const
uint32_t getMultiplicity (const Var &var) const
bool isBound (const Var &var) const
void print (std::ostream &out) const override
void setInnermostIterations (uint64_t val)
Public Member Functions inherited from souffle::scheduler::State
Cost getCost () const
void incCost (Cost inc)
void setCost (Cost cost)
State ()
virtual ~State ()=default
Private Attributes
uint64_t innermostIterations
An estimate for the number of innermost iterations.
std::map< Var, uint32_t > multiplicity
An estimate for the multiplicity of variables – hence, to how many different values those variables may be bound at the given state.
Detailed Description
The state associated to the computational cost model maintaining an estimate to the multiplicity of bound variables and an estimate of innermost loop iterations.
Definition at line 601 of file RuleScheduler.h.
Constructor & Destructor Documentation
souffle::scheduler::ComputeCostState::ComputeCostState () inline
Definition at line 615 of file RuleScheduler.h.
 : innermostIterations(1) {}
Member Function Documentation
void souffle::scheduler::ComputeCostState::bind (const Var & var, uint32_t mult) inline
Definition at line 617 of file RuleScheduler.h.
References multiplicity.
Referenced by souffle::scheduler::ComputeCostModel::applyTo().
{
         multiplicity[var] = mult;
     }
uint64_t souffle::scheduler::ComputeCostState::getInnermostIterations () const inline
Definition at line 630 of file RuleScheduler.h.
References innermostIterations.
Referenced by souffle::scheduler::ComputeCostModel::applyTo().
{
         return innermostIterations;
     }
uint32_t souffle::scheduler::ComputeCostState::getMultiplicity (const Var & var) const inline
Definition at line 625 of file RuleScheduler.h.
References isBound(), and multiplicity.
{
         assert(isBound(var));
         return multiplicity.find(var)->second;
     }
bool souffle::scheduler::ComputeCostState::isBound (const Var & var) const inline
Definition at line 621 of file RuleScheduler.h.
References multiplicity.
Referenced by souffle::scheduler::ComputeCostModel::applyTo(), and getMultiplicity().
{
         return multiplicity.find(var) != multiplicity.end();
     }
void souffle::scheduler::ComputeCostState::print (std::ostream & out) const inline override virtual
Implements souffle::scheduler::State.
Definition at line 638 of file RuleScheduler.h.
References souffle::scheduler::State::getCost(), innermostIterations, and multiplicity.
{
         out << "State(" << getCost() << "," << multiplicity << "," << innermostIterations << ")";
     }
void souffle::scheduler::ComputeCostState::setInnermostIterations (uint64_t val) inline
Definition at line 634 of file RuleScheduler.h.
References innermostIterations.
Referenced by souffle::scheduler::ComputeCostModel::applyTo().
{
         innermostIterations = val;
     }
Field Documentation
uint64_t souffle::scheduler::ComputeCostState::innermostIterations private
An estimate for the number of innermost iterations.
Definition at line 612 of file RuleScheduler.h.
Referenced by getInnermostIterations(), print(), and setInnermostIterations().
std::map<Var, uint32_t> souffle::scheduler::ComputeCostState::multiplicity private
An estimate for the multiplicity of variables – hence, to how many different values those variables may be bound at the given state.
Definition at line 607 of file RuleScheduler.h.
Referenced by bind(), getMultiplicity(), isBound(), and print().
The documentation for this class was generated from the following file:
RuleScheduler.h