souffle: souffle::scheduler::ComputeCostAtom Class Reference
souffle::scheduler::ComputeCostAtom Class Reference
An extended version of the atom utilized by the computational cost model which is depending on additional statistical information.
#include <RuleScheduler.h>
Public Member Functions
ComputeCostAtom (int id, const std::vector< Argument > &args, const RelationStats &stats)
unsigned getCardinality () const
const RelationStats & getRelationStats () const
void print (std::ostream &out) const override
Public Member Functions inherited from souffle::scheduler::Atom
Atom (int id, const std::vector< Argument > &args)
const std::vector< Argument > & getArguments () const
Obtains the list of (abstracted) arguments exposed by this atom.
unsigned getArity () const
Obtains the arity of the targeted relation.
int getID () const
Obtains the identifier of this atom.
unsigned getNumConstants () const
Obtains the number of constant arguments.
std::vector< Var > getVariables () const
Obtains a list of the variable arguments.
bool operator< (const Atom &other) const
bool operator== (const Atom &other) const
virtual ~Atom ()=default
Private Attributes
RelationStats stats
Additional Inherited Members
Data Fields inherited from souffle::scheduler::Atom
std::vector< Argument > args
The list of arguments of this atom.
int id
An ID of this atom, making it unique.
Detailed Description
An extended version of the atom utilized by the computational cost model which is depending on additional statistical information.
Definition at line 573 of file RuleScheduler.h.
Constructor & Destructor Documentation
souffle::scheduler::ComputeCostAtom::ComputeCostAtom (int id, const std::vector< Argument > & args, const RelationStats & stats) inline
Definition at line 577 of file RuleScheduler.h.
References souffle::RelationStats::getArity().
             : Atom(id, args), stats(stats) {
         assert(args.size() == stats.getArity());
     }
Member Function Documentation
unsigned souffle::scheduler::ComputeCostAtom::getCardinality () const inline
Definition at line 586 of file RuleScheduler.h.
References souffle::RelationStats::getCardinality(), and stats.
Referenced by print().
{
         return stats.getCardinality();
     }
const RelationStats& souffle::scheduler::ComputeCostAtom::getRelationStats () const inline
Definition at line 582 of file RuleScheduler.h.
References stats.
Referenced by souffle::scheduler::ComputeCostModel::applyTo(), and print().
{
         return stats;
     }
void souffle::scheduler::ComputeCostAtom::print (std::ostream & out) const inline override virtual
Reimplemented from souffle::scheduler::Atom.
Definition at line 590 of file RuleScheduler.h.
References souffle::scheduler::Atom::getArguments(), getCardinality(), souffle::scheduler::Atom::getID(), and getRelationStats().
{
         out << "<" << getID() << ">|" << getCardinality() << "," << getRelationStats() << "|( "
             << getArguments() << " )";
     }
Field Documentation
RelationStats souffle::scheduler::ComputeCostAtom::stats private
Definition at line 574 of file RuleScheduler.h.
Referenced by getCardinality(), and getRelationStats().
The documentation for this class was generated from the following file:
RuleScheduler.h