souffle: souffle::RelationStats Class Reference
souffle::RelationStats Class Reference
A summary of statistical properties of a ram relation.
#include <Interpreter.h>
Public Member Functions
uint8_t getArity () const
uint64_t getCardinality () const
uint64_t getEstimatedCardinality (Column c) const
uint32_t getSampleSize () const
RelationStats & operator= (const RelationStats &)=default
RelationStats & operator= (RelationStats &&)=default
void print (std::ostream &out) const
RelationStats ()
RelationStats (uint64_t size, const std::vector< uint64_t > &cards)
RelationStats (const RelationStats &)=default
RelationStats (RelationStats &&)=default
Static Public Member Functions
static RelationStats extractFrom (const InterpreterRelation &rel, uint32_t sample_size=std::numeric_limits< uint32_t >::max())
A factory function extracting statistical information form the given relation base on a given sample size.
Private Attributes
uint8_t arity
The arity - accurate.
std::vector< uint64_t > cardinalities
The cardinality of the various components of the tuples - estimated.
uint32_t sample_size
The sample size estimations are based on.
uint64_t size
The number of tuples - accurate.
Friends
std::ostream & operator<< (std::ostream &out, const RelationStats &stats)
Detailed Description
A summary of statistical properties of a ram relation.
Definition at line 641 of file Interpreter.h.
Constructor & Destructor Documentation
souffle::RelationStats::RelationStats () inline
Definition at line 655 of file Interpreter.h.
 : arity(0), size(0), sample_size(0) {}
souffle::RelationStats::RelationStats (uint64_t size, const std::vector< uint64_t > & cards) inline
Definition at line 657 of file Interpreter.h.
             : arity(cards.size()), size(size), sample_size(0), cardinalities(cards) {}
souffle::RelationStats::RelationStats (const RelationStats &) default
souffle::RelationStats::RelationStats (RelationStats &&) default
Member Function Documentation
RelationStats souffle::RelationStats::extractFrom (const InterpreterRelation & rel, uint32_t sample_size = std::numeric_limits<uint32_t>::max()) static
A factory function extracting statistical information form the given relation base on a given sample size.
If the sample size is not specified, the full relation will be processed.
Definition at line 1051 of file Interpreter.cpp.
References arity, souffle::InterpreterRelation::begin(), cardinalities, souffle::InterpreterRelation::end(), souffle::InterpreterRelation::getArity(), sample_size, souffle::InterpreterRelation::size(), and size.
{
     // write each column in its own set
     std::vector<btree_set<RamDomain>> columns(rel.getArity());
     // analyze sample
     uint32_t count = 0;
     for (auto it = rel.begin(); it != rel.end() && count < sample_size; ++it, ++count) {
         const RamDomain* tuple = *it;
         // compute cardinality of columns
         for (std::size_t i = 0; i < rel.getArity(); ++i) {
             columns[i].insert(tuple[i]);
         }
     }
     // create the resulting statistics object
     RelationStats stats;
     stats.arity = rel.getArity();
     stats.size = rel.size();
     stats.sample_size = count;
     for (std::size_t i = 0; i < rel.getArity(); i++) {
         // estimate the cardinality of the columns
         uint64_t card = 0;
         if (count > 0) {
             // based on the observed probability
             uint64_t cur = columns[i].size();
             double p = ((double)cur / (double)count);
             // obtain an estimate of the overall cardinality
             card = (uint64_t)(p * rel.size());
             // make sure that it is at least what you have seen
             if (card < cur) {
                 card = cur;
             }
         }
         // add result
         stats.cardinalities.push_back(card);
     }
     // done
     return stats;
 }
uint8_t souffle::RelationStats::getArity () const inline
Definition at line 674 of file Interpreter.h.
References arity.
Referenced by souffle::scheduler::ComputeCostAtom::ComputeCostAtom().
{
         return arity;
     }
uint64_t souffle::RelationStats::getCardinality () const inline
Definition at line 678 of file Interpreter.h.
References size.
Referenced by souffle::scheduler::ComputeCostModel::applyTo(), and souffle::scheduler::ComputeCostAtom::getCardinality().
{
         return size;
     }
uint64_t souffle::RelationStats::getEstimatedCardinality (Column c) const inline
Definition at line 686 of file Interpreter.h.
References cardinalities.
Referenced by souffle::scheduler::ComputeCostModel::applyTo().
{
         if (c >= cardinalities.size()) {
             return 0;
         }
         return cardinalities[c];
     }
uint32_t souffle::RelationStats::getSampleSize () const inline
Definition at line 682 of file Interpreter.h.
References sample_size.
{
         return sample_size;
     }
RelationStats& souffle::RelationStats::operator= (const RelationStats &) default
RelationStats& souffle::RelationStats::operator= (RelationStats &&) default
void souffle::RelationStats::print (std::ostream & out) const inline
Definition at line 693 of file Interpreter.h.
References cardinalities.
{
         out << cardinalities;
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const RelationStats & stats) friend
Definition at line 697 of file Interpreter.h.
{
         stats.print(out);
         return out;
     }
Field Documentation
uint8_t souffle::RelationStats::arity private
The arity - accurate.
Definition at line 643 of file Interpreter.h.
Referenced by extractFrom(), and getArity().
std::vector<uint64_t> souffle::RelationStats::cardinalities private
The cardinality of the various components of the tuples - estimated.
Definition at line 652 of file Interpreter.h.
Referenced by extractFrom(), getEstimatedCardinality(), and print().
uint32_t souffle::RelationStats::sample_size private
The sample size estimations are based on.
Definition at line 649 of file Interpreter.h.
Referenced by extractFrom(), and getSampleSize().
uint64_t souffle::RelationStats::size private
The number of tuples - accurate.
Definition at line 646 of file Interpreter.h.
Referenced by extractFrom(), and getCardinality().
The documentation for this class was generated from the following files:
Interpreter.h
Interpreter.cpp