souffle: souffle::Synthesiser Class Reference
souffle::Synthesiser Class Reference
A RAM synthesiser: synthesises a C++ program from a RAM program.
#include <Synthesiser.h>
Public Member Functions
void generateCode (const RamTranslationUnit &tu, std::ostream &os, const std::string &id) const
Generates the code for a given ram translation unit.
void setReportTarget (std::ostream &report)
Updates logging stream.
Synthesiser ()
A simple constructor.
Private Attributes
std::ostream * report
An optional stream to print logging information to an output stream.
Detailed Description
A RAM synthesiser: synthesises a C++ program from a RAM program.
Definition at line 35 of file Synthesiser.h.
Constructor & Destructor Documentation
souffle::Synthesiser::Synthesiser () inline
A simple constructor.
Definition at line 50 of file Synthesiser.h.
 : report(nullptr) {}
Member Function Documentation
void souffle::Synthesiser::generateCode (const RamTranslationUnit & tu, std::ostream & os, const std::string & id) const
Generates the code for a given ram translation unit.
Parameters
tu
os the stream to send the generated C++ code to.
id the base identifier used in code generation, including class name.
Definition at line 1249 of file Synthesiser.cpp.
References arity, souffle::Global::config(), souffle::RamRelation::getArity(), souffle::RamLoad::getIODirectives(), souffle::RamProgram::getMain(), souffle::RamTranslationUnit::getP(), souffle::RamRelationStatement::getRelation(), souffle::RamProgram::getSubroutines(), souffle::RamRelation::getSymbolMask(), souffle::RamTranslationUnit::getSymbolTable(), name, report, souffle::SymbolTable::resolve(), souffle::SymbolTable::size(), souffle::sub(), and souffle::visitDepthFirst().
{
     // ---------------------------------------------------------------
     //                      Auto-Index Generation
     // ---------------------------------------------------------------
     const SymbolTable& symTable = unit.getSymbolTable();
     const RamProgram& prog = unit.getP();
     // collect all used indices
     IndexMap indices;
     visitDepthFirst(prog, [&](const RamNode& node) {
         if (const RamScan* scan = dynamic_cast<const RamScan*>(&node)) {
             indices[scan->getRelation()].setHashmap(scan->getRelation().isHashmap());
             indices[scan->getRelation()].addSearch(scan->getRangeQueryColumns());
         }
         if (const RamAggregate* agg = dynamic_cast<const RamAggregate*>(&node)) {
             indices[agg->getRelation()].setHashmap(agg->getRelation().isHashmap());
             indices[agg->getRelation()].addSearch(agg->getRangeQueryColumns());
         }
         if (const RamNotExists* ne = dynamic_cast<const RamNotExists*>(&node)) {
             indices[ne->getRelation()].setHashmap(ne->getRelation().isHashmap());
             indices[ne->getRelation()].addSearch(ne->getKey());
         }
     });
     // compute smallest number of indices (and report)
     if (report) {
         *report << "------ Auto-Index-Generation Report -------\n";
     }
     for (auto& cur : indices) {
         cur.second.solve();
         if (report) {
             *report << "Relation " << cur.first.getName() << "\n";
             *report << "\tNumber of Scan Patterns: " << cur.second.getSearches().size() << "\n";
             for (auto& cols : cur.second.getSearches()) {
                 *report << "\t\t";
                 for (uint32_t i = 0; i < cur.first.getArity(); i++) {
                     if ((1UL << i) & cols) {
                         *report << cur.first.getArg(i) << " ";
                     }
                 }
                 *report << "\n";
             }
             *report << "\tNumber of Indexes: " << cur.second.getAllOrders().size() << "\n";
             for (auto& order : cur.second.getAllOrders()) {
                 *report << "\t\t";
                 for (auto& i : order) {
                     *report << cur.first.getArg(i) << " ";
                 }
                 *report << "\n";
             }
             *report << "------ End of Auto-Index-Generation Report -------\n";
         }
     }
     // ---------------------------------------------------------------
     //                      Code Generation
     // ---------------------------------------------------------------
     std::string classname = "Sf_" + id;
     // generate C++ program
     os << "#include \"souffle/CompiledSouffle.h\"\n";
     if (Global::config().has("provenance")) {
         os << "#include \"souffle/Explain.h\"\n";
         os << "#include <ncurses.h>\n";
     }
     os << "\n";
     os << "namespace souffle {\n";
     os << "using namespace ram;\n";
     // print wrapper for regex
     os << "class " << classname << " : public SouffleProgram {\n";
     os << "private:\n";
     os << "static inline bool regex_wrapper(const char *pattern, const char *text) {\n";
     os << "   bool result = false; \n";
     os << "   try { result = std::regex_match(text, std::regex(pattern)); } catch(...) { \n";
     os << "     std::cerr << \"warning: wrong pattern provided for match(\\\"\" << pattern << \"\\\",\\\"\" "
           "<< text << \"\\\")\\n\";\n}\n";
     os << "   return result;\n";
     os << "}\n";
     os << "static inline std::string substr_wrapper(const char *str, size_t idx, size_t len) {\n";
     os << "   std::string sub_str, result; \n";
     os << "   try { result = std::string(str).substr(idx,len); } catch(...) { \n";
     os << "     std::cerr << \"warning: wrong index position provided by substr(\\\"\";\n";
     os << "     std::cerr << str << \"\\\",\" << (int32_t)idx << \",\" << (int32_t)len << \") "
           "functor.\\n\";\n";
     os << "   } return result;\n";
     os << "}\n";
     if (Global::config().has("profile")) {
         os << "std::string profiling_fname;\n";
     }
     // declare symbol table
     os << "public:\n";
     os << "SymbolTable symTable;\n";
     // print relation definitions
     std::string initCons;      // initialization of constructor
     std::string deleteForNew;  // matching deletes for each new, used in the destructor
     std::string registerRel;   // registration of relations
     int relCtr = 0;
     std::string tempType;  // string to hold the type of the temporary relations
     visitDepthFirst(*(prog.getMain()), [&](const RamCreate& create) {
         // get some table details
         const auto& rel = create.getRelation();
         int arity = rel.getArity();
         const std::string& raw_name = rel.getName();
         const std::string& name = getRelationName(rel);
         // ensure that the type of the new knowledge is the same as that of the delta knowledge
         tempType = (rel.isTemp() && raw_name.find("@delta") != std::string::npos)
                            ? getRelationType(rel, rel.getArity(), indices[rel])
                            : tempType;
         const std::string& type =
                 (rel.isTemp()) ? tempType : getRelationType(rel, rel.getArity(), indices[rel]);
         // defining table
         os << "// -- Table: " << raw_name << "\n";
         os << type << "* " << name << ";\n";
         if (initCons.size() > 0) {
             initCons += ",\n";
         }
         initCons += name + "(new " + type + "())";
         deleteForNew += "delete " + name + ";\n";
         if ((rel.isInput() || rel.isComputed() || Global::config().has("provenance")) && !rel.isTemp()) {
             os << "souffle::RelationWrapper<";
             os << relCtr++ << ",";
             os << type << ",";
             os << "Tuple<RamDomain," << arity << ">,";
             os << arity << ",";
             os << (rel.isInput() ? "true" : "false") << ",";
             os << (rel.isComputed() ? "true" : "false");
             os << "> wrapper_" << name << ";\n";
             // construct types
             std::string tupleType = "std::array<const char *," + std::to_string(arity) + ">{";
             std::string tupleName = "std::array<const char *," + std::to_string(arity) + ">{";
             if (rel.getArity()) {
                 tupleType += "\"" + rel.getArgTypeQualifier(0) + "\"";
                 for (int i = 1; i < arity; i++) {
                     tupleType += ",\"" + rel.getArgTypeQualifier(i) + "\"";
                 }
                 tupleName += "\"" + rel.getArg(0) + "\"";
                 for (int i = 1; i < arity; i++) {
                     tupleName += ",\"" + rel.getArg(i) + "\"";
                 }
             }
             tupleType += "}";
             tupleName += "}";
             initCons += ",\nwrapper_" + name + "(" + "*" + name + ",symTable,\"" + raw_name + "\"," +
                         tupleType + "," + tupleName + ")";
             registerRel += "addRelation(\"" + raw_name + "\",&wrapper_" + name + "," +
                            std::to_string(rel.isInput()) + "," + std::to_string(rel.isOutput()) + ");\n";
         }
     });
     os << "public:\n";
     // -- constructor --
     os << classname;
     if (Global::config().has("profile")) {
         os << "(std::string pf=\"profile.log\") : profiling_fname(pf)";
         if (initCons.size() > 0) {
             os << ",\n" << initCons;
         }
     } else {
         os << "()";
         if (initCons.size() > 0) {
             os << " : " << initCons;
         }
     }
     os << "{\n";
     os << registerRel;
     if (symTable.size() > 0) {
         os << "// -- initialize symbol table --\n";
         os << "static const char *symbols[]={\n";
         for (size_t i = 0; i < symTable.size(); i++) {
             os << "\tR\"(" << symTable.resolve(i) << ")\",\n";
         }
         os << "};\n";
         os << "symTable.insert(symbols," << symTable.size() << ");\n";
         os << "\n";
     }
     os << "}\n";
     // -- destructor --
     os << "~" << classname << "() {\n";
     os << deleteForNew;
     os << "}\n";
     // -- run function --
     os << "private:\ntemplate <bool performIO> void runFunction(std::string inputDirectory = \".\", "
           "std::string outputDirectory = \".\") {\n";
     os << "SignalHandler::instance()->set();\n";
     // initialize counter
     os << "// -- initialize counter --\n";
     os << "std::atomic<RamDomain> ctr(0);\n\n";
     // set default threads (in embedded mode)
     if (std::stoi(Global::config().get("jobs")) > 0) {
         os << "#if defined(__EMBEDDED_SOUFFLE__) && defined(_OPENMP)\n";
         os << "omp_set_num_threads(" << std::stoi(Global::config().get("jobs")) << ");\n";
         os << "#endif\n\n";
     }
     // add actual program body
     os << "// -- query evaluation --\n";
     if (Global::config().has("profile")) {
         os << "std::ofstream profile(profiling_fname);\n";
         os << "profile << \"@start-debug\\n\";\n";
         genCode(os, *(prog.getMain()), indices);
     } else {
         genCode(os, *(prog.getMain()), indices);
     }
     // add code printing hint statistics
     os << "\n// -- relation hint statistics --\n";
     os << "if(isHintsProfilingEnabled()) {\n";
     os << "std::cout << \" -- Operation Hint Statistics --\\n\";\n";
     visitDepthFirst(*(prog.getMain()), [&](const RamCreate& create) {
         auto name = getRelationName(create.getRelation());
         os << "std::cout << \"Relation " << name << ":\\n\";\n";
         os << name << "->printHintStatistics(std::cout,\"  \");\n";
         os << "std::cout << \"\\n\";\n";
     });
     os << "}\n";
     os << "SignalHandler::instance()->reset();\n";
     os << "}\n";  // end of runFunction() method
     // add methods to run with and without performing IO (mainly for the interface)
     os << "public:\nvoid run() { runFunction<false>(); }\n";
     os << "public:\nvoid runAll(std::string inputDirectory = \".\", std::string outputDirectory = \".\") { "
           "runFunction<true>(inputDirectory, outputDirectory); }\n";
     // issue printAll method
     os << "public:\n";
     os << "void printAll(std::string outputDirectory = \".\") {\n";
     visitDepthFirst(*(prog.getMain()), [&](const RamStatement& node) {
         if (auto store = dynamic_cast<const RamStore*>(&node)) {
             for (IODirectives ioDirectives : store->getIODirectives()) {
                 os << "try {";
                 os << "std::map<std::string, std::string> directiveMap(" << ioDirectives << ");\n";
                 os << "if (!outputDirectory.empty() && directiveMap[\"IO\"] == \"file\" && ";
                 os << "directiveMap[\"filename\"].front() != '/') {";
                 os << "directiveMap[\"filename\"] = outputDirectory + \"/\" + directiveMap[\"filename\"];";
                 os << "}\n";
                 os << "IODirectives ioDirectives(directiveMap);\n";
                 os << "IOSystem::getInstance().getWriter(";
                 os << "SymbolMask({" << store->getRelation().getSymbolMask() << "})";
                 os << ", symTable, ioDirectives, " << Global::config().has("provenance");
                 os << ")->writeAll(*" << getRelationName(store->getRelation()) << ");\n";
                 os << "} catch (std::exception& e) {std::cerr << e.what();exit(1);}\n";
             }
         } else if (auto print = dynamic_cast<const RamPrintSize*>(&node)) {
             os << "{ auto lease = getOutputLock().acquire(); \n";
             os << "(void)lease;\n";
             os << "std::cout << R\"(" << print->getMessage() << ")\" <<  ";
             os << getRelationName(print->getRelation()) << "->"
                << "size() << std::endl;\n";
             os << "}";
         }
     });
     os << "}\n";  // end of printAll() method
     // issue loadAll method
     os << "public:\n";
     os << "void loadAll(std::string inputDirectory = \".\") {\n";
     visitDepthFirst(*(prog.getMain()), [&](const RamLoad& load) {
         // get some table details
         os << "try {";
         os << "std::map<std::string, std::string> directiveMap(";
         os << load.getIODirectives() << ");\n";
         os << "if (!inputDirectory.empty() && directiveMap[\"IO\"] == \"file\" && ";
         os << "directiveMap[\"filename\"].front() != '/') {";
         os << "directiveMap[\"filename\"] = inputDirectory + \"/\" + directiveMap[\"filename\"];";
         os << "}\n";
         os << "IODirectives ioDirectives(directiveMap);\n";
         os << "IOSystem::getInstance().getReader(";
         os << "SymbolMask({" << load.getRelation().getSymbolMask() << "})";
         os << ", symTable, ioDirectives";
         os << ", " << Global::config().has("provenance");
         os << ")->readAll(*" << getRelationName(load.getRelation());
         os << ");\n";
         os << "} catch (std::exception& e) {std::cerr << e.what();exit(1);}\n";
     });
     os << "}\n";  // end of loadAll() method
     // issue dump methods
     auto dumpRelation = [&](const std::string& name, const SymbolMask& mask, size_t arity) {
         auto relName = name;
         os << "try {";
         os << "IODirectives ioDirectives;\n";
         os << "ioDirectives.setIOType(\"stdout\");\n";
         os << "ioDirectives.setRelationName(\"" << name << "\");\n";
         os << "IOSystem::getInstance().getWriter(";
         os << "SymbolMask({" << mask << "})";
         os << ", symTable, ioDirectives, " << Global::config().has("provenance");
         os << ")->writeAll(*" << relName << ");\n";
         os << "} catch (std::exception& e) {std::cerr << e.what();exit(1);}\n";
     };
     // dump inputs
     os << "public:\n";
     os << "void dumpInputs(std::ostream& out = std::cout) {\n";
     visitDepthFirst(*(prog.getMain()), [&](const RamLoad& load) {
         auto& name = getRelationName(load.getRelation());
         auto& mask = load.getRelation().getSymbolMask();
         size_t arity = load.getRelation().getArity();
         dumpRelation(name, mask, arity);
     });
     os << "}\n";  // end of dumpInputs() method
     // dump outputs
     os << "public:\n";
     os << "void dumpOutputs(std::ostream& out = std::cout) {\n";
     visitDepthFirst(*(prog.getMain()), [&](const RamStore& store) {
         auto& name = getRelationName(store.getRelation());
         auto& mask = store.getRelation().getSymbolMask();
         size_t arity = store.getRelation().getArity();
         dumpRelation(name, mask, arity);
     });
     os << "}\n";  // end of dumpOutputs() method
     os << "public:\n";
     os << "const SymbolTable &getSymbolTable() const {\n";
     os << "return symTable;\n";
     os << "}\n";  // end of getSymbolTable() method
     // TODO: generate code for subroutines
     if (Global::config().has("provenance")) {
         // generate subroutine adapter
         os << "void executeSubroutine(std::string name, const std::vector<RamDomain>& args, "
               "std::vector<RamDomain>& ret, std::vector<bool>& err) override {\n";
         // subroutine number
         size_t subroutineNum = 0;
         for (auto& sub : prog.getSubroutines()) {
             os << "if (name == \"" << sub.first << "\") {\n"
                << "subproof_" << subroutineNum
                << "(args, ret, err);\n"  // subproof_i to deal with special characters in relation names
                << "}\n";
             subroutineNum++;
         }
         os << "}\n";  // end of executeSubroutine
         // generate method for each subroutine
         subroutineNum = 0;
         for (auto& sub : prog.getSubroutines()) {
             // method header
             os << "void "
                << "subproof_" << subroutineNum << "(const std::vector<RamDomain>& args, "
                                                   "std::vector<RamDomain>& ret, std::vector<bool>& err) {\n";
             // generate code for body
             genCode(os, *sub.second, indices);
             os << "return;\n";
             os << "}\n";  // end of subroutine
             subroutineNum++;
         }
     }
     os << "};\n";  // end of class declaration
     // hidden hooks
     os << "SouffleProgram *newInstance_" << id << "(){return new " << classname << ";}\n";
     os << "SymbolTable *getST_" << id << "(SouffleProgram *p){return &reinterpret_cast<" << classname
        << "*>(p)->symTable;}\n";
     os << "#ifdef __EMBEDDED_SOUFFLE__\n";
     os << "class factory_" << classname << ": public souffle::ProgramFactory {\n";
     os << "SouffleProgram *newInstance() {\n";
     os << "return new " << classname << "();\n";
     os << "};\n";
     os << "public:\n";
     os << "factory_" << classname << "() : ProgramFactory(\"" << id << "\"){}\n";
     os << "};\n";
     os << "static factory_" << classname << " __factory_" << classname << "_instance;\n";
     os << "}\n";
     os << "#else\n";
     os << "}\n";
     os << "int main(int argc, char** argv)\n{\n";
     os << "try{\n";
     // parse arguments
     os << "souffle::CmdOptions opt(";
     os << "R\"(" << Global::config().get("") << ")\",\n";
     os << "R\"(.)\",\n";
     os << "R\"(.)\",\n";
     if (Global::config().has("profile")) {
         os << "true,\n";
         os << "R\"(" << Global::config().get("profile") << ")\",\n";
     } else {
         os << "false,\n";
         os << "R\"()\",\n";
     }
     os << std::stoi(Global::config().get("jobs")) << "\n";
     os << ");\n";
     os << "if (!opt.parse(argc,argv)) return 1;\n";
     os << "#if defined(_OPENMP) \n";
     os << "omp_set_nested(true);\n";
     os << "#endif\n";
     os << "souffle::";
     if (Global::config().has("profile")) {
         os << classname + " obj(opt.getProfileName());\n";
     } else {
         os << classname + " obj;\n";
     }
     os << "obj.runAll(opt.getInputFileDir(), opt.getOutputFileDir());\n";
     if (Global::config().get("provenance") == "1") {
         os << "explain(obj, true, false);\n";
     } else if (Global::config().get("provenance") == "2") {
         os << "explain(obj, true, true);\n";
     }
     os << "return 0;\n";
     os << "} catch(std::exception &e) { souffle::SignalHandler::instance()->error(e.what());}\n";
     os << "}\n";
     os << "#endif\n";
 }
void souffle::Synthesiser::setReportTarget (std::ostream & report) inline
Updates logging stream.
Definition at line 44 of file Synthesiser.h.
References report.
{
         this->report = &report;
     }
Field Documentation
std::ostream* souffle::Synthesiser::report private
An optional stream to print logging information to an output stream.
Definition at line 38 of file Synthesiser.h.
Referenced by generateCode(), and setReportTarget().
The documentation for this class was generated from the following files:
Synthesiser.h
Synthesiser.cpp