souffle: souffle::CPPIdentifierMap Class Reference
souffle::CPPIdentifierMap Class Reference
A singleton which provides a mapping from strings to unique valid CPP identifiers.
Public Member Functions
~CPPIdentifierMap ()=default
Static Public Member Functions
static std::string getIdentifier (const std::string &name)
Given a string, returns its corresponding unique valid identifier;.
static CPPIdentifierMap & getInstance ()
Obtains the singleton instance.
Private Member Functions
CPPIdentifierMap ()
const std::string identifier (const std::string &name)
Instance method for getIdentifier above.
Private Attributes
std::map< const std::string,
const std::string > identifiers
Static Private Attributes
static CPPIdentifierMap * instance = nullptr
Detailed Description
A singleton which provides a mapping from strings to unique valid CPP identifiers.
Definition at line 52 of file Synthesiser.cpp.
Constructor & Destructor Documentation
souffle::CPPIdentifierMap::~CPPIdentifierMap () default
souffle::CPPIdentifierMap::CPPIdentifierMap () inline private
Definition at line 74 of file Synthesiser.cpp.
Referenced by getInstance().
 {}
Member Function Documentation
static std::string souffle::CPPIdentifierMap::getIdentifier (const std::string & name) inline static
Given a string, returns its corresponding unique valid identifier;.
Definition at line 67 of file Synthesiser.cpp.
References getInstance(), and identifier().
{
         return getInstance().identifier(name);
     }
static CPPIdentifierMap& souffle::CPPIdentifierMap::getInstance () inline static
Obtains the singleton instance.
Definition at line 57 of file Synthesiser.cpp.
References CPPIdentifierMap(), and instance.
Referenced by getIdentifier().
{
         if (instance == nullptr) {
             instance = new CPPIdentifierMap();
         }
         return *instance;
     }
const std::string souffle::CPPIdentifierMap::identifier (const std::string & name) inline private
Instance method for getIdentifier above.
Definition at line 81 of file Synthesiser.cpp.
References identifiers.
Referenced by getIdentifier().
{
         auto it = identifiers.find(name);
         if (it != identifiers.end()) {
             return it->second;
         }
         // strip leading numbers
         unsigned int i;
         for (i = 0; i < name.length(); ++i) {
             if (isalnum(name.at(i)) || name.at(i) == '_') {
                 break;
             }
         }
         std::string id;
         for (auto ch : std::to_string(identifiers.size() + 1) + '_' + name.substr(i)) {
             // alphanumeric characters are allowed
             if (isalnum(ch)) {
                 id += ch;
             }
             // all other characters are replaced by an underscore, except when
             // the previous character was an underscore as double underscores
             // in identifiers are reserved by the standard
             else if (id.size() == 0 || id.back() != '_') {
                 id += '_';
             }
         }
         // most compilers have a limit of 2048 characters (if they have a limit at all) for
         // identifiers; we use half of that for safety
         id = id.substr(0, 1024);
         identifiers.insert(std::make_pair(name, id));
         return id;
     }
Field Documentation
std::map<const std::string, const std::string> souffle::CPPIdentifierMap::identifiers private
Definition at line 114 of file Synthesiser.cpp.
Referenced by identifier().
CPPIdentifierMap * souffle::CPPIdentifierMap::instance = nullptr static private
Definition at line 76 of file Synthesiser.cpp.
Referenced by getInstance().
The documentation for this class was generated from the following file:
Synthesiser.cpp