souffle: souffle::AstTranslator Class Reference
souffle::AstTranslator Class Reference
A utility class capable of conducting the conversion between AST and RAM structures.
#include <AstTranslator.h>
Public Member Functions
std::unique_ptr< RamStatement > makeSubproofSubroutine (const AstClause &clause, const AstProgram *program, const TypeEnvironment &typeEnv)
generate RAM code for subroutine to get subproofs
std::unique_ptr< RamStatement > translateClause (const AstClause &clause, const AstProgram *program, const TypeEnvironment *typeEnv, int version=0, bool ret=false)
generate RAM code for a clause
std::unique_ptr< RamStatement > translateNonRecursiveRelation (const AstRelation &rel, const AstProgram *program, const RecursiveClauses *recursiveClauses, const TypeEnvironment &typeEnv)
Generates RAM code for the non-recursive clauses of the given relation.
std::unique_ptr< RamProgram > translateProgram (const AstTranslationUnit &translationUnit)
Translate AST to RamProgram.
std::unique_ptr< RamStatement > translateRecursiveRelation (const std::set< const AstRelation * > &scc, const AstProgram *program, const RecursiveClauses *recursiveClauses, const TypeEnvironment &typeEnv)
generate RAM code for recursive relations in a strongly-connected component
std::string translateRelationName (const AstRelationIdentifier &id)
If true, created constructs will be annotated with logging information.
std::unique_ptr
< RamTranslationUnit > translateUnit (AstTranslationUnit &tu)
translates AST to translation unit
Detailed Description
A utility class capable of conducting the conversion between AST and RAM structures.
Definition at line 43 of file AstTranslator.h.
Member Function Documentation
std::unique_ptr< RamStatement > souffle::AstTranslator::makeSubproofSubroutine (const AstClause & clause, const AstProgram * program, const TypeEnvironment & typeEnv)
generate RAM code for subroutine to get subproofs
make a subroutine to search for subproofs
Definition at line 1195 of file AstTranslator.cpp.
References souffle::AstClause::clone(), souffle::EQ, souffle::AstAtom::getArgument(), souffle::LT, rec, and translateClause().
Referenced by translateProgram().
{
     // make intermediate clause with constraints
     std::unique_ptr<AstClause> intermediateClause(clause.clone());
     // name unnamed variables
     nameUnnamedVariables(intermediateClause.get());
     // add constraint for each argument in head of atom
     AstAtom* head = intermediateClause->getHead();
     for (size_t i = 0; i < head->getArguments().size() - 2; i++) {
         auto arg = head->getArgument(i);
         if (auto var = dynamic_cast<AstVariable*>(arg)) {
             intermediateClause->addToBody(std::make_unique<AstConstraint>(BinaryConstraintOp::EQ,
                     std::unique_ptr<AstArgument>(var->clone()), std::make_unique<AstSubroutineArgument>(i)));
         } else if (auto func = dynamic_cast<AstFunctor*>(arg)) {
             intermediateClause->addToBody(std::make_unique<AstConstraint>(BinaryConstraintOp::EQ,
                     std::unique_ptr<AstArgument>(func->clone()), std::make_unique<AstSubroutineArgument>(i)));
         } else if (auto rec = dynamic_cast<AstRecordInit*>(arg)) {
             intermediateClause->addToBody(std::make_unique<AstConstraint>(BinaryConstraintOp::EQ,
                     std::unique_ptr<AstArgument>(rec->clone()), std::make_unique<AstSubroutineArgument>(i)));
         }
     }
     // index of level argument in argument list
     size_t levelIndex = head->getArguments().size() - 2;
     // add level constraints
     for (size_t i = 0; i < intermediateClause->getBodyLiterals().size(); i++) {
         auto lit = intermediateClause->getBodyLiteral(i);
         if (auto atom = dynamic_cast<AstAtom*>(lit)) {
             auto arity = atom->getArity();
             // arity - 1 is the level number in body atoms
             intermediateClause->addToBody(std::make_unique<AstConstraint>(BinaryConstraintOp::LT,
                     std::unique_ptr<AstArgument>(atom->getArgument(arity - 1)->clone()),
                     std::make_unique<AstSubroutineArgument>(levelIndex)));
         }
     }
     return translateClause(*intermediateClause, program, &typeEnv, 0, true);
 }
std::unique_ptr< RamStatement > souffle::AstTranslator::translateClause (const AstClause & clause, const AstProgram * program, const TypeEnvironment * typeEnv, int version = 0, bool ret = false)
generate RAM code for a clause
Definition at line 431 of file AstTranslator.cpp.
References souffle::RamNotExists::addArg(), souffle::RamReturn::addValue(), souffle::any_of(), arity, souffle::AstExecutionOrder::begin(), souffle::AstClause::clone(), souffle::Global::config(), souffle::RamAggregate::COUNT, souffle::AstAggregator::count, souffle::AstExecutionOrder::end(), souffle::EQ, souffle::AstAtom::getArgument(), souffle::AstAtom::getArguments(), souffle::AstAtom::getArity(), souffle::AstAtom::getAtom(), souffle::getAtomRelation(), souffle::AstClause::getAtoms(), souffle::AstClause::getBodyLiterals(), souffle::AstAggregator::getBodyLiterals(), souffle::AstClause::getExecutionPlan(), souffle::AstClause::getHead(), souffle::AstAggregator::getOperator(), souffle::AstExecutionPlan::getOrderFor(), souffle::AstAggregator::getTargetExpression(), souffle::AstExecutionPlan::hasOrderFor(), souffle::AstClause::isFact(), souffle::AstClause::isRule(), level, souffle::RamAggregate::MAX, souffle::AstAggregator::max, souffle::RamAggregate::MIN, souffle::AstAggregator::min, rec, souffle::AstExecutionOrder::size(), souffle::RamAggregate::SUM, souffle::AstAggregator::sum, and souffle::visitDepthFirstPostOrder().
Referenced by makeSubproofSubroutine(), translateNonRecursiveRelation(), and translateRecursiveRelation().
{
     // check whether there is an imposed order constraint
     if (clause.getExecutionPlan() && clause.getExecutionPlan()->hasOrderFor(version)) {
         // get the imposed order
         const AstExecutionOrder& order = clause.getExecutionPlan()->getOrderFor(version);
         // create a copy and fix order
         std::unique_ptr<AstClause> copy(clause.clone());
         // Change order to start at zero
         std::vector<unsigned int> newOrder(order.size());
         std::transform(order.begin(), order.end(), newOrder.begin(),
                 [](unsigned int i) -> unsigned int { return i - 1; });
         // re-order atoms
         copy->reorderAtoms(newOrder);
         // clear other order and fix plan
         copy->clearExecutionPlan();
         copy->setFixedExecutionPlan();
         // translate reordered clause
         return translateClause(*copy, program, typeEnv, version);
     }
     // get extract some details
     const AstAtom& head = *clause.getHead();
     // a utility to translate atoms to relations
     auto getRelation = [&](const AstAtom* atom) {
         return getRamRelation((program ? getAtomRelation(atom, program) : nullptr), typeEnv,
                 getRelationName(atom->getName()), atom->getArity());
     };
     // handle facts
     if (clause.isFact()) {
         // translate arguments
         std::vector<std::unique_ptr<RamValue>> values;
         for (auto& arg : clause.getHead()->getArguments()) {
             values.push_back(translateValue(*arg));
         }
         // create a fact statement
         return std::make_unique<RamFact>(getRelation(&head), std::move(values));
     }
     // the rest should be rules
     assert(clause.isRule());
     // -- index values in rule --
     // create value index
     ValueIndex valueIndex;
     // the order of processed operations
     std::vector<const AstNode*> op_nesting;
     int level = 0;
     for (AstAtom* atom : clause.getAtoms()) {
         // index nested variables and records
         typedef std::vector<AstArgument*> arg_list;
         // std::map<const arg_list*, int> arg_level;
         std::map<const AstNode*, std::unique_ptr<arg_list>> nodeArgs;
         std::function<arg_list*(const AstNode*)> getArgList = [&](const AstNode* curNode) {
             if (!nodeArgs.count(curNode)) {
                 if (auto rec = dynamic_cast<const AstRecordInit*>(curNode)) {
                     nodeArgs.insert(std::make_pair(curNode, std::make_unique<arg_list>(rec->getArguments())));
                 } else if (auto atom = dynamic_cast<const AstAtom*>(curNode)) {
                     nodeArgs.insert(
                             std::make_pair(curNode, std::make_unique<arg_list>(atom->getArguments())));
                 } else {
                     assert(false && "node type doesn't have arguments!");
                 }
             }
             arg_list* cur = nodeArgs[curNode].get();
             return cur;
         };
         std::map<const arg_list*, int> arg_level;
         nodeArgs.insert(std::make_pair(atom, std::make_unique<arg_list>(atom->getArguments())));
         // the atom is obtained at the current level
         arg_level[nodeArgs[atom].get()] = level;
         op_nesting.push_back(atom);
         // increment nesting level for the atom
         level++;
         // relation
         std::unique_ptr<RamRelation> relation = getRelation(atom);
         std::function<void(const AstNode*)> indexValues = [&](const AstNode* curNode) {
             arg_list* cur = getArgList(curNode);
             for (size_t pos = 0; pos < cur->size(); pos++) {
                 // get argument
                 auto& arg = (*cur)[pos];
                 // check for variable references
                 if (auto var = dynamic_cast<const AstVariable*>(arg)) {
                     if (pos < relation->getArity()) {
                         valueIndex.addVarReference(*var, arg_level[cur], pos, relation->getArg(pos));
                     } else {
                         valueIndex.addVarReference(*var, arg_level[cur], pos);
                     }
                 }
                 // check for nested records
                 if (auto rec = dynamic_cast<const AstRecordInit*>(arg)) {
                     // introduce new nesting level for unpack
                     int unpack_level = level++;
                     op_nesting.push_back(rec);
                     arg_level[getArgList(rec)] = unpack_level;
                     valueIndex.setRecordUnpackLevel(*rec, unpack_level);
                     // register location of record
                     valueIndex.setRecordDefinition(*rec, arg_level[cur], pos);
                     // resolve nested components
                     indexValues(rec);
                 }
             }
         };
         indexValues(atom);
     }
     // add aggregation functions
     std::vector<const AstAggregator*> aggregators;
     visitDepthFirstPostOrder(clause, [&](const AstAggregator& cur) {
         // add each aggregator expression only once
         if (any_of(aggregators, [&](const AstAggregator* agg) { return *agg == cur; })) {
             return;
         }
         int aggLoc = level++;
         valueIndex.setAggregatorLocation(cur, Location({aggLoc, 0}));
         // bind aggregator variables to locations
         assert(dynamic_cast<const AstAtom*>(cur.getBodyLiterals()[0]));
         const AstAtom& atom = static_cast<const AstAtom&>(*cur.getBodyLiterals()[0]);
         for (size_t pos = 0; pos < atom.getArguments().size(); ++pos) {
             if (const AstVariable* var = dynamic_cast<const AstVariable*>(atom.getArgument(pos))) {
                 valueIndex.addVarReference(*var, aggLoc, (int)pos, getRelation(&atom)->getArg(pos));
             }
         };
         // and remember aggregator
         aggregators.push_back(&cur);
     });
     // -- create RAM statement --
     // begin with projection
     std::unique_ptr<RamOperation> op;
     if (ret) {
         RamReturn* returnValue = new RamReturn(level);
         // get all values in the body
         for (AstLiteral* lit : clause.getBodyLiterals()) {
             if (auto atom = dynamic_cast<AstAtom*>(lit)) {
                 for (AstArgument* arg : atom->getArguments()) {
                     returnValue->addValue(translateValue(arg, valueIndex));
                 }
             } else if (auto neg = dynamic_cast<AstNegation*>(lit)) {
                 for (size_t i = 0; i < neg->getAtom()->getArguments().size() - 2; i++) {
                     auto arg = neg->getAtom()->getArguments()[i];
                     returnValue->addValue(translateValue(arg, valueIndex));
                 }
                 returnValue->addValue(std::make_unique<RamNumber>(-1));
                 returnValue->addValue(std::make_unique<RamNumber>(-1));
             }
         }
         op = std::unique_ptr<RamOperation>(returnValue);
     } else {
         std::unique_ptr<RamProject> project =
                 std::unique_ptr<RamProject>(new RamProject(getRelation(&head), level));
         for (AstArgument* arg : head.getArguments()) {
             project->addArg(translateValue(arg, valueIndex));
         }
         // check existence for original tuple if we have provenance
         if (Global::config().has("provenance")) {
             auto uniquenessEnforcement = std::make_unique<RamNotExists>(getRelation(&head));
             auto arity = head.getArity() - 2;
             bool add = true;
             // add args for original tuple
             for (size_t i = 0; i < arity; i++) {
                 auto arg = head.getArgument(i);
                 // don't add counters
                 if (dynamic_cast<AstCounter*>(arg)) {
                     add = false;
                     break;
                 }
                 uniquenessEnforcement->addArg(translateValue(arg, valueIndex));
             }
             // add two unnamed args for provenance columns
             uniquenessEnforcement->addArg(nullptr);
             uniquenessEnforcement->addArg(nullptr);
             if (add) {
                 project->addCondition(std::move(uniquenessEnforcement), *project);
             }
         }
         // build up insertion call
         op = std::move(project);  // start with innermost
     }
     // add aggregator levels
     for (auto it = aggregators.rbegin(); it != aggregators.rend(); ++it) {
         const AstAggregator* cur = *it;
         level--;
         // translate aggregation function
         RamAggregate::Function fun = RamAggregate::MIN;
         switch (cur->getOperator()) {
             case AstAggregator::min:
                 fun = RamAggregate::MIN;
                 break;
             case AstAggregator::max:
                 fun = RamAggregate::MAX;
                 break;
             case AstAggregator::count:
                 fun = RamAggregate::COUNT;
                 break;
             case AstAggregator::sum:
                 fun = RamAggregate::SUM;
                 break;
         }
         // translate target expression
         std::unique_ptr<RamValue> value = translateValue(cur->getTargetExpression(), valueIndex);
         // translate body literal
         assert(cur->getBodyLiterals().size() == 1 && "Unsupported complex aggregation body encountered!");
         const AstAtom* atom = dynamic_cast<const AstAtom*>(cur->getBodyLiterals()[0]);
         assert(atom && "Unsupported complex aggregation body encountered!");
         // add Ram-Aggregation layer
         op = std::unique_ptr<RamOperation>(
                 new RamAggregate(std::move(op), fun, std::move(value), getRelation(atom)));
         // add constant constraints
         for (size_t pos = 0; pos < atom->argSize(); ++pos) {
             if (AstConstant* c = dynamic_cast<AstConstant*>(atom->getArgument(pos))) {
                 op->addCondition(std::unique_ptr<RamCondition>(new RamBinaryRelation(BinaryConstraintOp::EQ,
                         std::unique_ptr<RamValue>(
                                 new RamElementAccess(level, pos, getRelation(atom)->getArg(pos))),
                         std::make_unique<RamNumber>(c->getIndex()))));
             }
         }
     }
     // build operation bottom-up
     while (!op_nesting.empty()) {
         // get next operator
         const AstNode* cur = op_nesting.back();
         op_nesting.pop_back();
         // get current nesting level
         auto level = op_nesting.size();
         if (const AstAtom* atom = dynamic_cast<const AstAtom*>(cur)) {
             // find out whether a "search" or "if" should be issued
             bool isExistCheck = !valueIndex.isSomethingDefinedOn(level);
             for (size_t pos = 0; pos < atom->argSize(); ++pos) {
                 if (dynamic_cast<AstAggregator*>(atom->getArgument(pos))) {
                     isExistCheck = false;
                 }
             }
             // add a scan level
             op = std::make_unique<RamScan>(getRelation(atom), std::move(op), isExistCheck);
             // add constraints
             for (size_t pos = 0; pos < atom->argSize(); ++pos) {
                 if (AstConstant* c = dynamic_cast<AstConstant*>(atom->getArgument(pos))) {
                     op->addCondition(std::unique_ptr<RamCondition>(new RamBinaryRelation(
                             BinaryConstraintOp::EQ, std::unique_ptr<RamValue>(new RamElementAccess(
                                                             level, pos, getRelation(atom)->getArg(pos))),
                             std::make_unique<RamNumber>(c->getIndex()))));
                 } else if (AstAggregator* agg = dynamic_cast<AstAggregator*>(atom->getArgument(pos))) {
                     auto loc = valueIndex.getAggregatorLocation(*agg);
                     op->addCondition(std::unique_ptr<RamCondition>(new RamBinaryRelation(
                             BinaryConstraintOp::EQ, std::unique_ptr<RamValue>(new RamElementAccess(
                                                             level, pos, getRelation(atom)->getArg(pos))),
                             std::unique_ptr<RamValue>(
                                     new RamElementAccess(loc.level, loc.component, loc.name)))));
                 }
             }
             // TODO: support constants in nested records!
         } else if (const AstRecordInit* rec = dynamic_cast<const AstRecordInit*>(cur)) {
             // add an unpack level
             const Location& loc = valueIndex.getDefinitionPoint(*rec);
             op = std::unique_ptr<RamOperation>(
                     new RamLookup(std::move(op), loc.level, loc.component, rec->getArguments().size()));
             // add constant constraints
             for (size_t pos = 0; pos < rec->getArguments().size(); ++pos) {
                 if (AstConstant* c = dynamic_cast<AstConstant*>(rec->getArguments()[pos])) {
                     op->addCondition(std::unique_ptr<RamCondition>(new RamBinaryRelation(
                             BinaryConstraintOp::EQ, std::make_unique<RamElementAccess>(level, pos),
                             std::make_unique<RamNumber>(c->getIndex()))));
                 }
             }
         } else {
             std::cout << "Unsupported AST node type: " << typeid(*cur).name() << "\n";
             assert(false && "Unsupported AST node for creation of scan-level!");
         }
     }
     /* add equivalence constraints imposed by variable binding */
     for (const auto& cur : valueIndex.getVariableReferences()) {
         // the first appearance
         const Location& first = *cur.second.begin();
         // all other appearances
         for (const Location& loc : cur.second) {
             if (first != loc) {
                 op->addCondition(std::unique_ptr<RamCondition>(new RamBinaryRelation(BinaryConstraintOp::EQ,
                         std::unique_ptr<RamValue>(
                                 new RamElementAccess(first.level, first.component, first.name)),
                         std::unique_ptr<RamValue>(
                                 new RamElementAccess(loc.level, loc.component, loc.name)))));
             }
         }
     }
     /* add conditions caused by atoms, negations, and binary relations */
     for (const auto& lit : clause.getBodyLiterals()) {
         // for atoms
         if (dynamic_cast<const AstAtom*>(lit)) {
             // covered already within the scan/lookup generation step
             // for binary relations
         } else if (auto binRel = dynamic_cast<const AstConstraint*>(lit)) {
             std::unique_ptr<RamValue> valLHS = translateValue(binRel->getLHS(), valueIndex);
             std::unique_ptr<RamValue> valRHS = translateValue(binRel->getRHS(), valueIndex);
             op->addCondition(std::unique_ptr<RamCondition>(
                     new RamBinaryRelation(binRel->getOperator(), translateValue(binRel->getLHS(), valueIndex),
                             translateValue(binRel->getRHS(), valueIndex))));
             // for negations
         } else if (auto neg = dynamic_cast<const AstNegation*>(lit)) {
             // get contained atom
             const AstAtom* atom = neg->getAtom();
             // create constraint
             RamNotExists* notExists = new RamNotExists(getRelation(atom));
             auto arity = atom->getArity();
             // account for two extra provenance columns
             if (Global::config().has("provenance")) {
                 arity -= 2;
             }
             for (size_t i = 0; i < arity; i++) {
                 const auto& arg = atom->getArgument(i);
                 // for (const auto& arg : atom->getArguments()) {
                 notExists->addArg(translateValue(*arg, valueIndex));
             }
             // we don't care about the provenance columns when doing the existence check
             if (Global::config().has("provenance")) {
                 notExists->addArg(nullptr);
                 notExists->addArg(nullptr);
             }
             // add constraint
             op->addCondition(std::unique_ptr<RamCondition>(notExists));
         } else {
             std::cout << "Unsupported node type: " << typeid(*lit).name();
             assert(false && "Unsupported node type!");
         }
     }
     /* generate the final RAM Insert statement */
     return std::make_unique<RamInsert>(clause, std::move(op));
 }
std::unique_ptr< RamStatement > souffle::AstTranslator::translateNonRecursiveRelation (const AstRelation & rel, const AstProgram * program, const RecursiveClauses * recursiveClauses, const TypeEnvironment & typeEnv)
Generates RAM code for the non-recursive clauses of the given relation.
generate RAM code for a non-recursive relation
Returns
a corresponding statement or null if there are no non-recursive clauses.
Definition at line 837 of file AstTranslator.cpp.
References souffle::appendStmt(), souffle::Global::config(), souffle::AstRelation::getArity(), souffle::AstRelation::getClauses(), souffle::AstRelation::getName(), souffle::AstNode::getSrcLoc(), souffle::RecursiveClauses::recursive(), souffle::stringify(), souffle::toString(), and translateClause().
Referenced by translateProgram(), and translateRecursiveRelation().
{
     /* start with an empty sequence */
     std::unique_ptr<RamStatement> res;
     // the ram table reference
     std::unique_ptr<RamRelation> rrel =
             getRamRelation(&rel, &typeEnv, getRelationName(rel.getName()), rel.getArity());
     /* iterate over all clauses that belong to the relation */
     for (AstClause* clause : rel.getClauses()) {
         // skip recursive rules
         if (recursiveClauses->recursive(clause)) {
             continue;
         }
         // translate clause
         std::unique_ptr<RamStatement> rule = translateClause(*clause, program, &typeEnv);
         // add logging
         if (Global::config().has("profile")) {
             std::string clauseText = stringify(toString(*clause));
             std::ostringstream line;
             line << "nonrecursive-rule;" << rel.getName() << ";";
             line << clause->getSrcLoc() << ";";
             line << clauseText << ";";
             std::string label = line.str();
             rule = std::unique_ptr<RamStatement>(new RamSequence(
                     std::unique_ptr<RamStatement>(new RamLogTimer(std::move(rule), "@t-" + label)),
                     std::make_unique<RamLogSize>(
                             std::unique_ptr<RamRelation>(rrel->clone()), "@n-" + label)));
         }
         // add debug info
         std::ostringstream ds;
         ds << toString(*clause) << "\nin file ";
         ds << clause->getSrcLoc();
         rule = std::make_unique<RamDebugInfo>(std::move(rule), ds.str());
         // add rule to result
         appendStmt(res, std::move(rule));
     }
     // if no clauses have been translated, we are done
     if (!res) {
         return res;
     }
     // add logging for entire relation
     if (Global::config().has("profile")) {
         // compute label
         std::ostringstream line;
         line << "nonrecursive-relation;" << rel.getName() << ";";
         line << rel.getSrcLoc() << ";";
         std::string label = line.str();
         // add timer
         res = std::make_unique<RamLogTimer>(std::move(res), "@t-" + label);
         // add table size printer
         appendStmt(res,
                 std::make_unique<RamLogSize>(std::unique_ptr<RamRelation>(rrel->clone()), "@n-" + label));
     }
     // done
     return res;
 }
std::unique_ptr< RamProgram > souffle::AstTranslator::translateProgram (const AstTranslationUnit & translationUnit)
Translate AST to RamProgram.
translates the given datalog program into an equivalent RAM program
Do nothing for empty schedules
Definition at line 1240 of file AstTranslator.cpp.
References souffle::appendStmt(), ASSERT, souffle::Global::config(), souffle::createAndLoad(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getClauseNum(), souffle::AstClause::getHead(), souffle::AstAtom::getName(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), makeSubproofSubroutine(), souffle::printSizeStore(), translateNonRecursiveRelation(), translateRecursiveRelation(), and souffle::visitDepthFirst().
Referenced by souffle::AutoScheduleTransformer::autotune(), and translateUnit().
{
     const TypeEnvironment& typeEnv =
             translationUnit.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
     RecursiveClauses* recursiveClauses = translationUnit.getAnalysis<RecursiveClauses>();
     /* start with an empty sequence */
     std::unique_ptr<RamStatement> res = std::make_unique<RamSequence>();
     /* Compute SCCs of program */
     const auto& sccGraph = *translationUnit.getAnalysis<SCCGraph>();
     const auto& schedule = translationUnit.getAnalysis<RelationSchedule>()->schedule();
     /** Do nothing for empty schedules */
     if (schedule.empty()) {
         return std::make_unique<RamProgram>(std::move(res));
     }
     /* proceed over each step, in stratification these become subprograms */
     unsigned index = 0;
     for (const RelationScheduleStep& step : schedule) {
         std::unique_ptr<RamStatement> current;
         /* during stratification, create and load all predecessor relations in another scc */
         for (const AstRelation* rel : step.computed()) {
             createAndLoad(current, rel, typeEnv, true, sccGraph.isRecursive(rel), true);
         }
         /* translate the body, this is where actual computation happens */
         std::unique_ptr<RamStatement> stmt;
         if (!step.recursive()) {
             ASSERT(step.computed().size() == 1 && "SCC contains more than one relation");
             const AstRelation* rel = *step.computed().begin();
             /* Run non-recursive evaluation */
             stmt = translateNonRecursiveRelation(
                     *rel, translationUnit.getProgram(), recursiveClauses, typeEnv);
         } else {
             stmt = translateRecursiveRelation(
                     step.computed(), translationUnit.getProgram(), recursiveClauses, typeEnv);
         }
         appendStmt(current, std::move(stmt));
         /* store all relations with fault tolerance, and output relations without */
         for (const AstRelation* rel : step.computed()) {
             printSizeStore(current, rel, typeEnv, true);
         }
         /* drop expired relations, or all relations for stratification */
         if (!Global::config().has("provenance")) {
             for (const AstRelation* rel : step.expired()) {
                 appendStmt(current, std::make_unique<RamDrop>(getRamRelation(rel, &typeEnv)));
             }
             if (index == schedule.size() - 1) {
                 for (const AstRelation* rel : step.computed()) {
                     appendStmt(current, std::make_unique<RamDrop>(getRamRelation(rel, &typeEnv)));
                 }
             }
         }
         // append the current step to the result
         if (current) {
             appendStmt(res, std::move(current));
             // increment the index
             index++;
         }
     }
     if (res && Global::config().has("profile")) {
         res = std::make_unique<RamLogTimer>(std::move(res), "@runtime;");
     }
     // done for main prog
     std::unique_ptr<RamProgram> prog(new RamProgram(std::move(res)));
     // add subroutines for each clause
     if (Global::config().has("provenance")) {
         visitDepthFirst(translationUnit.getProgram()->getRelations(), [&](const AstClause& clause) {
             std::stringstream relName;
             relName << clause.getHead()->getName();
             if (relName.str().find("@info") != std::string::npos || clause.getBodyLiterals().size() == 0) {
                 return;
             }
             std::string subroutineLabel =
                     relName.str() + "_" + std::to_string(clause.getClauseNum()) + "_subproof";
             prog->addSubroutine(
                     subroutineLabel, makeSubproofSubroutine(clause, translationUnit.getProgram(), typeEnv));
         });
     }
     return prog;
 }
std::unique_ptr< RamStatement > souffle::AstTranslator::translateRecursiveRelation (const std::set< const AstRelation * > & scc, const AstProgram * program, const RecursiveClauses * recursiveClauses, const TypeEnvironment & typeEnv)
generate RAM code for recursive relations in a strongly-connected component
Definition at line 942 of file AstTranslator.cpp.
References souffle::appendStmt(), souffle::AstAtom::clone(), souffle::AstClause::clone(), souffle::Global::config(), souffle::getAtomRelation(), souffle::AstClause::getAtoms(), souffle::AstClause::getExecutionPlan(), souffle::AstClause::getHead(), souffle::AstExecutionPlan::getMaxVersion(), souffle::AstNode::getSrcLoc(), souffle::RecursiveClauses::recursive(), souffle::AstAtom::setName(), souffle::stringify(), souffle::toString(), translateClause(), and translateNonRecursiveRelation().
Referenced by translateProgram().
{
     // initialize sections
     std::unique_ptr<RamStatement> preamble;
     std::unique_ptr<RamSequence> updateTable(new RamSequence());
     std::unique_ptr<RamStatement> postamble;
     // --- create preamble ---
     // mappings for temporary relations
     std::map<const AstRelation*, std::unique_ptr<RamRelation>> rrel;
     std::map<const AstRelation*, std::unique_ptr<RamRelation>> relDelta;
     std::map<const AstRelation*, std::unique_ptr<RamRelation>> relNew;
     /* Compute non-recursive clauses for relations in scc and push
        the results in their delta tables. */
     for (const AstRelation* rel : scc) {
         std::unique_ptr<RamStatement> updateRelTable;
         /* create two temporary tables for relaxed semi-naive evaluation */
         auto relName = getRelationName(rel->getName());
         rrel[rel] = getRamRelation(rel, &typeEnv, relName, rel->getArity());
         relDelta[rel] = getRamRelation(rel, &typeEnv, "delta_" + relName, rel->getArity(), true);
         relNew[rel] = getRamRelation(rel, &typeEnv, "new_" + relName, rel->getArity(), true);
         /* create update statements for fixpoint (even iteration) */
         appendStmt(updateRelTable,
                 std::unique_ptr<RamStatement>(new RamSequence(
                         std::unique_ptr<RamStatement>(
                                 new RamMerge(std::unique_ptr<RamRelation>(rrel[rel]->clone()),
                                         std::unique_ptr<RamRelation>(relNew[rel]->clone()))),
                         std::unique_ptr<RamStatement>(
                                 new RamSwap(std::unique_ptr<RamRelation>(relDelta[rel]->clone()),
                                         std::unique_ptr<RamRelation>(relNew[rel]->clone()))),
                         std::make_unique<RamClear>(std::unique_ptr<RamRelation>(relNew[rel]->clone())))));
         /* measure update time for each relation */
         if (Global::config().has("profile")) {
             std::ostringstream ost, osn;
             ost << "@c-recursive-relation;" << rel->getName() << ";" << rel->getSrcLoc() << ";";
             updateRelTable = std::make_unique<RamLogTimer>(std::move(updateRelTable), ost.str());
         }
         /* drop temporary tables after recursion */
         appendStmt(postamble, std::unique_ptr<RamStatement>(new RamSequence(
                                       std::unique_ptr<RamStatement>(new RamDrop(
                                               std::unique_ptr<RamRelation>(relDelta[rel]->clone()))),
                                       std::unique_ptr<RamStatement>(new RamDrop(
                                               std::unique_ptr<RamRelation>(relNew[rel]->clone()))))));
         /* Generate code for non-recursive part of relation */
         appendStmt(preamble, translateNonRecursiveRelation(*rel, program, recursiveClauses, typeEnv));
         /* Generate merge operation for temp tables */
         appendStmt(preamble, std::unique_ptr<RamStatement>(
                                      new RamMerge(std::unique_ptr<RamRelation>(relDelta[rel]->clone()),
                                              std::unique_ptr<RamRelation>(rrel[rel]->clone()))));
         /* Add update operations of relations to parallel statements */
         updateTable->add(std::move(updateRelTable));
     }
     // --- build main loop ---
     std::unique_ptr<RamParallel> loopSeq(new RamParallel());
     // create a utility to check SCC membership
     auto isInSameSCC = [&](
             const AstRelation* rel) { return std::find(scc.begin(), scc.end(), rel) != scc.end(); };
     /* Compute temp for the current tables */
     for (const AstRelation* rel : scc) {
         std::unique_ptr<RamStatement> loopRelSeq;
         /* Find clauses for relation rel */
         for (size_t i = 0; i < rel->clauseSize(); i++) {
             AstClause* cl = rel->getClause(i);
             // skip non-recursive clauses
             if (!recursiveClauses->recursive(cl)) {
                 continue;
             }
             // each recursive rule results in several operations
             int version = 0;
             const auto& atoms = cl->getAtoms();
             for (size_t j = 0; j < atoms.size(); ++j) {
                 const AstAtom* atom = atoms[j];
                 const AstRelation* atomRelation = getAtomRelation(atom, program);
                 // only interested in atoms within the same SCC
                 if (!isInSameSCC(atomRelation)) {
                     continue;
                 }
                 // modify the processed rule to use relDelta and write to relNew
                 std::unique_ptr<AstClause> r1(cl->clone());
                 r1->getHead()->setName(relNew[rel]->getName());
                 r1->getAtoms()[j]->setName(relDelta[atomRelation]->getName());
                 r1->addToBody(std::unique_ptr<AstLiteral>(
                         new AstNegation(std::unique_ptr<AstAtom>(cl->getHead()->clone()))));
                 // replace wildcards with variables (reduces indices when wildcards are used in recursive
                 // atoms)
                 nameUnnamedVariables(r1.get());
                 // reduce R to P ...
                 for (size_t k = j + 1; k < atoms.size(); k++) {
                     if (isInSameSCC(getAtomRelation(atoms[k], program))) {
                         AstAtom* cur = r1->getAtoms()[k]->clone();
                         cur->setName(relDelta[getAtomRelation(atoms[k], program)]->getName());
                         r1->addToBody(std::make_unique<AstNegation>(std::unique_ptr<AstAtom>(cur)));
                     }
                 }
                 std::unique_ptr<RamStatement> rule = translateClause(*r1, program, &typeEnv, version);
                 /* add logging */
                 if (Global::config().has("profile")) {
                     std::string clauseText = stringify(toString(*cl));
                     std::ostringstream line;
                     line << "recursive-rule;" << rel->getName() << ";";
                     line << version << ";";
                     line << cl->getSrcLoc() << ";";
                     line << clauseText << ";";
                     std::string label = line.str();
                     rule = std::unique_ptr<RamStatement>(new RamSequence(
                             std::unique_ptr<RamStatement>(new RamLogTimer(std::move(rule), "@t-" + label)),
                             std::unique_ptr<RamLogSize>(new RamLogSize(
                                     std::unique_ptr<RamRelation>(relNew[rel]->clone()), "@n-" + label))));
                 }
                 // add debug info
                 std::ostringstream ds;
                 ds << toString(*cl) << "\nin file ";
                 ds << cl->getSrcLoc();
                 rule = std::make_unique<RamDebugInfo>(std::move(rule), ds.str());
                 // add to loop body
                 appendStmt(loopRelSeq, std::move(rule));
                 // increment version counter
                 version++;
             }
             assert(cl->getExecutionPlan() == nullptr || version > cl->getExecutionPlan()->getMaxVersion());
         }
         // if there was no rule, continue
         if (!loopRelSeq) {
             continue;
         }
         // label all versions
         if (Global::config().has("profile")) {
             std::ostringstream line;
             line << "recursive-relation;" << rel->getName() << ";" << rel->getSrcLoc() << ";";
             std::string label = line.str();
             loopRelSeq = std::make_unique<RamLogTimer>(std::move(loopRelSeq), "@t-" + label);
             appendStmt(
                     loopRelSeq, std::make_unique<RamLogSize>(
                                         std::unique_ptr<RamRelation>(relNew[rel]->clone()), "@n-" + label));
         }
         /* add rule computations of a relation to parallel statement */
         loopSeq->add(std::move(loopRelSeq));
     }
     /* construct exit conditions for odd and even iteration */
     auto addCondition = [](std::unique_ptr<RamCondition>& cond, std::unique_ptr<RamCondition> clause) {
         cond = ((cond) ? std::unique_ptr<RamCondition>(new RamAnd(std::move(cond), std::move(clause)))
                        : std::move(clause));
     };
     std::unique_ptr<RamCondition> exitCond;
     for (const AstRelation* rel : scc) {
         addCondition(exitCond, std::unique_ptr<RamCondition>(
                                        new RamEmpty(std::unique_ptr<RamRelation>(relNew[rel]->clone()))));
     }
     /* construct fixpoint loop  */
     std::unique_ptr<RamStatement> res;
     if (preamble) appendStmt(res, std::move(preamble));
     if (!loopSeq->getStatements().empty() && exitCond && updateTable) {
         appendStmt(res, std::unique_ptr<RamStatement>(new RamLoop(std::move(loopSeq),
                                 std::make_unique<RamExit>(std::move(exitCond)), std::move(updateTable))));
     }
     if (postamble) {
         appendStmt(res, std::move(postamble));
     }
     if (res) return res;
     assert(false && "Not Implemented");
     return nullptr;
 }
std::string souffle::AstTranslator::translateRelationName (const AstRelationIdentifier & id)
If true, created constructs will be annotated with logging information.
A constructor for this translators.
Parameters
logging if generated clauses should be annotated with logging operations Converts the given relation identifier into a relation name.
Definition at line 184 of file AstTranslator.cpp.
{
     return getRelationName(id);
 }
std::unique_ptr<RamTranslationUnit> souffle::AstTranslator::translateUnit (AstTranslationUnit & tu) inline
translates AST to translation unit
Definition at line 84 of file AstTranslator.h.
References souffle::AstTranslationUnit::getDebugReport(), souffle::AstTranslationUnit::getErrorReport(), souffle::AstTranslationUnit::getSymbolTable(), and translateProgram().
Referenced by souffle::main().
{
         std::unique_ptr<RamProgram> ramProg = translateProgram(tu);
         SymbolTable& symTab = tu.getSymbolTable();
         ErrorReport& errReport = tu.getErrorReport();
         DebugReport& debugReport = tu.getDebugReport();
         return std::make_unique<RamTranslationUnit>(std::move(ramProg), symTab, errReport, debugReport);
     }
The documentation for this class was generated from the following files:
AstTranslator.h
AstTranslator.cpp