souffle: souffle::InterpreterRelation Class Reference
souffle::InterpreterRelation Class Reference
Interpreter Relation.
#include <Interpreter.h>
Data Structures
struct Block
Block data structure for storing tuples.
class iterator
Iterator for relation.
Public Member Functions
iterator begin () const
get iterator begin of relation
bool empty () const
Check whether relation is empty.
iterator end () const
get iterator begin of relation
bool exists (const RamDomain *tuple) const
check whether a tuple exists in the relation
virtual std::vector< RamDomain * > extend (const RamDomain *tuple)
Extend tuple.
virtual void extend (const InterpreterRelation &rel)
Extend relation.
size_t getArity () const
Get arity of relation.
InterpreterIndex * getIndex (const SearchColumns &key, InterpreterIndex *cachedIndex) const
get index for a given set of keys using a cached index as a helper.
InterpreterIndex * getIndex (const SearchColumns &key) const
get index for a given set of keys.
InterpreterIndex * getIndex (const InterpreterIndexOrder &order) const
get index for a given order.
SearchColumns getTotalIndexKey () const
Obtains a full index-key for this relation.
virtual void insert (const RamDomain *tuple)
Insert tuple.
template<typename... Args>
void insert (RamDomain first, Args...rest)
Insert tuple via arguments.
void insert (const InterpreterRelation &other)
Merge another relation into this relation.
InterpreterRelation (size_t relArity)
InterpreterRelation (const InterpreterRelation &other)=delete
InterpreterRelation (InterpreterRelation &&other)
InterpreterRelation & operator= (const InterpreterRelation &other)=delete
InterpreterRelation & operator= (InterpreterRelation &&other)
void purge ()
Purge table.
size_t size () const
Gets the number of contained tuples.
virtual ~InterpreterRelation ()
Private Attributes
std::list< RamDomain * > allocatedBlocks
List of all allocated blocks.
size_t arity
Arity of relation.
std::unique_ptr< Block > head
Head of block list.
std::map
< InterpreterIndexOrder,
std::unique_ptr
< InterpreterIndex > > indices
List of indices.
Lock lock
Lock for parallel execution.
size_t num_tuples
Number of tuples in relation.
Block * tail
Tail of block list.
InterpreterIndex * totalIndex
Total index for existence checks.
Static Private Attributes
static const int BLOCK_SIZE = 1024
Size of blocks containing tuples.
Detailed Description
Interpreter Relation.
Definition at line 36 of file Interpreter.h.
Constructor & Destructor Documentation
souffle::InterpreterRelation::InterpreterRelation (size_t relArity) inline
Definition at line 82 of file Interpreter.h.
             : arity(relArity), num_tuples(0), head(std::make_unique<Block>()), tail(head.get()),
               totalIndex(nullptr) {}
souffle::InterpreterRelation::InterpreterRelation (const InterpreterRelation & other) delete
souffle::InterpreterRelation::InterpreterRelation (InterpreterRelation && other) inline
Definition at line 88 of file Interpreter.h.
References allocatedBlocks, head, and indices.
             : arity(other.arity), num_tuples(other.num_tuples), tail(other.tail),
               totalIndex(other.totalIndex) {
         // take over ownership
         head.swap(other.head);
         indices.swap(other.indices);
         allocatedBlocks.swap(other.allocatedBlocks);
     }
virtual souffle::InterpreterRelation::~InterpreterRelation () inline virtual
Definition at line 98 of file Interpreter.h.
References allocatedBlocks.
{
         for (auto x : allocatedBlocks) delete[] x;
     }
Member Function Documentation
iterator souffle::InterpreterRelation::begin () const inline
get iterator begin of relation
Definition at line 337 of file Interpreter.h.
References arity, empty(), end(), getArity(), and head.
Referenced by souffle::InterpreterRelInterface::begin(), souffle::RelationStats::extractFrom(), and getIndex().
{
         // check for emptiness
         if (empty()) {
             return end();
         }
         // support 0-arity
         auto arity = getArity();
         if (arity == 0) {
             Block dummyBlock;
             RamDomain dummyTuple;
             return iterator(&dummyBlock, &dummyTuple, 0);
         }
         // support non-empty non-zero arity relation
         return iterator(head.get(), &head->data[0], arity);
     }
bool souffle::InterpreterRelation::empty () const inline
Check whether relation is empty.
Definition at line 125 of file Interpreter.h.
References num_tuples.
Referenced by begin(), and exists().
{
         return num_tuples == 0;
     }
iterator souffle::InterpreterRelation::end () const inline
get iterator begin of relation
Definition at line 356 of file Interpreter.h.
Referenced by begin(), souffle::InterpreterRelInterface::end(), souffle::RelationStats::extractFrom(), and getIndex().
{
         return iterator();
     }
bool souffle::InterpreterRelation::exists (const RamDomain * tuple) const inline
check whether a tuple exists in the relation
Definition at line 275 of file Interpreter.h.
References empty(), souffle::InterpreterIndex::exists(), getArity(), getIndex(), getTotalIndexKey(), and totalIndex.
Referenced by souffle::InterpreterRelInterface::contains(), and insert().
{
         // handle arity 0
         if (getArity() == 0) {
             return !empty();
         }
         // handle all other arities
         if (!totalIndex) {
             totalIndex = getIndex(getTotalIndexKey());
         }
         return totalIndex->exists(tuple);
     }
virtual std::vector<RamDomain*> souffle::InterpreterRelation::extend (const RamDomain * tuple) inline virtual
Extend tuple.
Reimplemented in souffle::InterpreterEqRelation.
Definition at line 361 of file Interpreter.h.
{
         std::vector<RamDomain*> newTuples;
         // A standard relation does not generate extra new knowledge on insertion.
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         return newTuples;
     }
virtual void souffle::InterpreterRelation::extend (const InterpreterRelation & rel) inline virtual
Extend relation.
Reimplemented in souffle::InterpreterEqRelation.
Definition at line 371 of file Interpreter.h.
 {}
size_t souffle::InterpreterRelation::getArity () const inline
Get arity of relation.
Definition at line 120 of file Interpreter.h.
References arity.
Referenced by begin(), exists(), souffle::RelationStats::extractFrom(), souffle::InterpreterRelInterface::getArity(), getIndex(), getTotalIndexKey(), insert(), and operator=().
{
         return arity;
     }
InterpreterIndex* souffle::InterpreterRelation::getIndex (const SearchColumns & key, InterpreterIndex * cachedIndex) const inline
get index for a given set of keys using a cached index as a helper.
Keys are encoded as bits for each column
Definition at line 200 of file Interpreter.h.
References souffle::InterpreterIndex::order().
Referenced by exists(), and getIndex().
{
         if (!cachedIndex) {
             return getIndex(key);
         }
         return getIndex(cachedIndex->order());
     }
InterpreterIndex* souffle::InterpreterRelation::getIndex (const SearchColumns & key) const inline
get index for a given set of keys.
Keys are encoded as bits for each column
Definition at line 208 of file Interpreter.h.
References souffle::Lock::acquire(), souffle::InterpreterIndexOrder::append(), getArity(), getIndex(), indices, souffle::InterpreterIndexOrder::isCompatible(), souffle::InterpreterIndexOrder::isComplete(), and lock.
{
         // suffix for order, if no matching prefix exists
         std::vector<unsigned char> suffix;
         suffix.reserve(getArity());
         // convert to order
         InterpreterIndexOrder order;
         for (size_t k = 1, i = 0; i < getArity(); i++, k *= 2) {
             if (key & k) {
                 order.append(i);
             } else {
                 suffix.push_back(i);
             }
         }
         // see whether there is an order with a matching prefix
         InterpreterIndex* res = nullptr;
         {
             auto lease = lock.acquire();
             (void)lease;
             for (auto it = indices.begin(); !res && it != indices.end(); ++it) {
                 if (order.isCompatible(it->first)) {
                     res = it->second.get();
                 }
             }
         }
         // if found, use compatible index
         if (res) {
             return res;
         }
         // extend index to full index
         for (auto cur : suffix) {
             order.append(cur);
         }
         assert(order.isComplete());
         // get a new index
         return getIndex(order);
     }
InterpreterIndex* souffle::InterpreterRelation::getIndex (const InterpreterIndexOrder & order) const inline
get index for a given order.
Keys are encoded as bits for each column
Definition at line 250 of file Interpreter.h.
References souffle::Lock::acquire(), begin(), end(), indices, and lock.
{
         // TODO: improve index usage by re-using indices with common prefix
         InterpreterIndex* res = nullptr;
         {
             auto lease = lock.acquire();
             (void)lease;
             auto pos = indices.find(order);
             if (pos == indices.end()) {
                 std::unique_ptr<InterpreterIndex>& newIndex = indices[order];
                 newIndex = std::make_unique<InterpreterIndex>(order);
                 newIndex->insert(this->begin(), this->end());
                 res = newIndex.get();
             } else {
                 res = pos->second.get();
             }
         }
         return res;
     }
SearchColumns souffle::InterpreterRelation::getTotalIndexKey () const inline
Obtains a full index-key for this relation.
Definition at line 270 of file Interpreter.h.
References getArity().
Referenced by exists().
{
         return (1 << (getArity())) - 1;
     }
virtual void souffle::InterpreterRelation::insert (const RamDomain * tuple) inline virtual
Insert tuple.
Reimplemented in souffle::InterpreterEqRelation.
Definition at line 135 of file Interpreter.h.
References arity, ASSERT, souffle::InterpreterRelation::Block::data, exists(), souffle::InterpreterRelation::Block::getFreeSpace(), indices, souffle::InterpreterRelation::Block::next, num_tuples, tail, and souffle::InterpreterRelation::Block::used.
Referenced by souffle::InterpreterEqRelation::extend(), souffle::InterpreterRelInterface::insert(), insert(), and souffle::InterpreterEqRelation::insert().
{
         // check for null-arity
         if (arity == 0) {
             // set number of tuples to one -- that's it
             num_tuples = 1;
             return;
         }
         ASSERT(tuple);
         // make existence check
         if (exists(tuple)) {
             return;
         }
         // prepare tail
         if (tail->getFreeSpace() < arity || arity == 0) {
             tail->next = std::make_unique<Block>();
             tail = tail->next.get();
         }
         // insert element into tail
         RamDomain* newTuple = &tail->data[tail->used];
         for (size_t i = 0; i < arity; ++i) {
             newTuple[i] = tuple[i];
         }
         tail->used += arity;
         // update all indexes with new tuple
         for (const auto& cur : indices) {
             cur.second->insert(newTuple);
         }
         // increment relation size
         num_tuples++;
     }
template<typename... Args> void souffle::InterpreterRelation::insert (RamDomain first, Args... rest) inline
Insert tuple via arguments.
Definition at line 174 of file Interpreter.h.
References insert().
{
         RamDomain tuple[] = {first, RamDomain(rest)...};
         insert(tuple);
     }
void souffle::InterpreterRelation::insert (const InterpreterRelation & other) inline
Merge another relation into this relation.
Definition at line 180 of file Interpreter.h.
References getArity(), and insert().
{
         assert(getArity() == other.getArity());
         for (const auto& cur : other) {
             insert(cur);
         }
     }
InterpreterRelation& souffle::InterpreterRelation::operator= (const InterpreterRelation & other) delete
InterpreterRelation& souffle::InterpreterRelation::operator= (InterpreterRelation && other) inline
Definition at line 105 of file Interpreter.h.
References ASSERT, getArity(), head, indices, num_tuples, tail, and totalIndex.
{
         ASSERT(getArity() == other.getArity());
         num_tuples = other.num_tuples;
         tail = other.tail;
         totalIndex = other.totalIndex;
         // take over ownership
         head.swap(other.head);
         indices.swap(other.indices);
         return *this;
     }
void souffle::InterpreterRelation::purge () inline
Purge table.
Definition at line 188 of file Interpreter.h.
References head, indices, num_tuples, and tail.
                  {
         std::unique_ptr<Block> newHead = std::make_unique<Block>();
         head.swap(newHead);
         tail = head.get();
         for (const auto& cur : indices) {
             cur.second->purge();
         }
         num_tuples = 0;
     }
size_t souffle::InterpreterRelation::size () const inline
Gets the number of contained tuples.
Definition at line 130 of file Interpreter.h.
References num_tuples.
Referenced by souffle::RelationStats::extractFrom(), and souffle::InterpreterRelInterface::size().
{
         return num_tuples;
     }
Field Documentation
std::list<RamDomain*> souffle::InterpreterRelation::allocatedBlocks private
List of all allocated blocks.
Definition at line 70 of file Interpreter.h.
Referenced by InterpreterRelation(), and ~InterpreterRelation().
size_t souffle::InterpreterRelation::arity private
Arity of relation.
Definition at line 39 of file Interpreter.h.
Referenced by begin(), getArity(), and insert().
const int souffle::InterpreterRelation::BLOCK_SIZE = 1024 static private
Size of blocks containing tuples.
Definition at line 42 of file Interpreter.h.
std::unique_ptr<Block> souffle::InterpreterRelation::head private
Head of block list.
Definition at line 64 of file Interpreter.h.
Referenced by begin(), InterpreterRelation(), operator=(), and purge().
std::map<InterpreterIndexOrder, std::unique_ptr<InterpreterIndex> > souffle::InterpreterRelation::indices mutable private
List of indices.
Definition at line 73 of file Interpreter.h.
Referenced by getIndex(), insert(), InterpreterRelation(), operator=(), and purge().
Lock souffle::InterpreterRelation::lock mutable private
Lock for parallel execution.
Definition at line 79 of file Interpreter.h.
Referenced by getIndex().
size_t souffle::InterpreterRelation::num_tuples private
Number of tuples in relation.
Definition at line 61 of file Interpreter.h.
Referenced by empty(), insert(), operator=(), purge(), and size().
Block* souffle::InterpreterRelation::tail private
Tail of block list.
Definition at line 67 of file Interpreter.h.
Referenced by insert(), operator=(), and purge().
InterpreterIndex* souffle::InterpreterRelation::totalIndex mutable private
Total index for existence checks.
Definition at line 76 of file Interpreter.h.
Referenced by exists(), and operator=().
The documentation for this class was generated from the following file:
Interpreter.h