souffle: souffle::AstStringConstant Class Reference
souffle::AstStringConstant Class Reference
Subclass of Argument that represents a datalog constant value.
#include <AstArgument.h>
Public Member Functions
AstStringConstant (SymbolTable &symTable, const char *c)
AstStringConstant * clone () const override
Creates a clone if this AST sub-structure.
const std::string getConstant () const
void print (std::ostream &os) const override
Print argument to the given output stream.
Public Member Functions inherited from souffle::AstConstant
void apply (const AstNodeMapper &) override
Mutates this node.
AstConstant (AstDomain i)
AstDomain getIndex () const
Public Member Functions inherited from souffle::AstArgument
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
AstSrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const AstSrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Private Member Functions
AstStringConstant (SymbolTable *symTable, size_t index)
Private Attributes
SymbolTable * symTable
Additional Inherited Members
Protected Member Functions inherited from souffle::AstConstant
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes inherited from souffle::AstConstant
AstDomain idx
Index of this Constant in the SymbolTable.
Detailed Description
Subclass of Argument that represents a datalog constant value.
Definition at line 203 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstStringConstant::AstStringConstant (SymbolTable * symTable, size_t index) inline private
Definition at line 205 of file AstArgument.h.
Referenced by clone().
 : AstConstant(index), symTable(symTable) {}
souffle::AstStringConstant::AstStringConstant (SymbolTable & symTable, const char * c) inline
Definition at line 208 of file AstArgument.h.
             : AstConstant(symTable.lookup(c)), symTable(&symTable) {}
Member Function Documentation
AstStringConstant* souffle::AstStringConstant::clone () const inline override virtual
Creates a clone if this AST sub-structure.
Implements souffle::AstArgument.
Definition at line 222 of file AstArgument.h.
References AstStringConstant(), souffle::AstConstant::getIndex(), souffle::AstNode::getSrcLoc(), souffle::AstNode::setSrcLoc(), and symTable.
{
         AstStringConstant* res = new AstStringConstant(symTable, getIndex());
         res->setSrcLoc(getSrcLoc());
         return res;
     }
const std::string souffle::AstStringConstant::getConstant () const inline
Returns
String representation of this Constant
Definition at line 212 of file AstArgument.h.
References souffle::AstConstant::getIndex(), souffle::SymbolTable::resolve(), and symTable.
Referenced by print().
{
         return symTable->resolve(getIndex());
     }
void souffle::AstStringConstant::print (std::ostream & os) const inline override virtual
Print argument to the given output stream.
Implements souffle::AstNode.
Definition at line 217 of file AstArgument.h.
References getConstant().
{
         os << "\"" << getConstant() << "\"";
     }
Field Documentation
SymbolTable* souffle::AstStringConstant::symTable private
Definition at line 204 of file AstArgument.h.
Referenced by clone(), and getConstant().
The documentation for this class was generated from the following file:
AstArgument.h