souffle: souffle::AutoScheduleTransformer Class Reference
souffle::AutoScheduleTransformer Class Reference
Transformation pass which tunes the given program by re-ordering the atoms in the included rules to improve performance.
#include <AstTuner.h>
Public Member Functions
AutoScheduleTransformer ()
std::string getName () const override
~AutoScheduleTransformer () override=default
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
static bool autotune (AstTranslationUnit &translationUnit, std::ostream *report)
Perform auto-scheduling for the given program.
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass which tunes the given program by re-ordering the atoms in the included rules to improve performance.
This operation is based on an actual, interpreted execution of the given program and the collection of profiling data.
Definition at line 32 of file AstTuner.h.
Constructor & Destructor Documentation
souffle::AutoScheduleTransformer::AutoScheduleTransformer () inline
Definition at line 37 of file AstTuner.h.
 {}
souffle::AutoScheduleTransformer::~AutoScheduleTransformer () override default
Member Function Documentation
bool souffle::AutoScheduleTransformer::autotune (AstTranslationUnit & translationUnit, std::ostream * report) static
Perform auto-scheduling for the given program.
Returns
whether the program was modified
Definition at line 80 of file AstTuner.cpp.
References souffle::Global::config(), data, souffle::Interpreter::execute(), souffle::AstClause::getAtoms(), souffle::AstTranslationUnit::getProgram(), souffle::AstTranslationUnit::getSymbolTable(), souffle::ExecutionSummary::order, souffle::AstClause::reorderAtoms(), souffle::ScheduledExecution, souffle::Interpreter::setReportTarget(), souffle::ExecutionSummary::time, souffle::AstTranslator::translateProgram(), and souffle::visitDepthFirst().
Referenced by transform().
{
     const QueryExecutionStrategy& strategy = ScheduledExecution;
     bool verbose = Global::config().has("verbose");
     // start with status message
     if (verbose) {
         std::cout << "\n";
     }
     if (verbose) {
         std::cout << "----------------- Auto-Scheduling Started -----------------\n";
     }
     // step 1 - translate to RAM program
     if (verbose) {
         std::cout << "[ Converting to RAM Program ...                           ]\n";
     }
     std::unique_ptr<RamProgram> prog = AstTranslator().translateProgram(translationUnit);
     const RamStatement* stmt = prog->getMain();
     // check whether there is something to tune
     if (!stmt) {
         if (verbose) {
             std::cout << "[                                     No Rules in Program ]\n";
             std::cout << "---------------- Auto-Scheduling Completed ----------------\n";
         }
         return false;
     }
     if (verbose) {
         std::cout << "[                                                    Done ]\n";
     }
     // step 2 - run in interpreted mode, collect decisions
     if (verbose) {
         std::cout << "[ Profiling RAM Program ...                               ]\n";
     }
     Profiler::Data data;
     Profiler profiler(strategy, data);
     // create a copy of the symbol table
     souffle::SymbolTable table = translationUnit.getSymbolTable();
     // create interpreter instance
     Interpreter interpreter(profiler);
     if (report && verbose) {
         SplitStream splitStream(report, &std::cout);
         interpreter.setReportTarget(splitStream);
     } else if (report) {
         interpreter.setReportTarget(*report);
     } else if (verbose) {
         interpreter.setReportTarget(std::cout);
     }
     // run interpreter
     interpreter.execute(table, *prog);
     if (verbose) {
         std::cout << "[                                                    Done ]\n";
     }
     if (verbose) {
         std::cout << "Data:\n";
         for (const auto& cur : data) {
             std::cout << "Clause @ " << cur.first << "\n";
             for (const ExecutionSummary& instance : cur.second) {
                 std::cout << "\t" << instance.order << " in " << instance.time << "ms\n";
             }
         }
     }
     // step 3 - process collected data ..
     if (verbose) {
         std::cout << "[ Selecting most significant schedules ...                ]\n";
     }
     std::map<AstSrcLocation, const AstClause*> clauses;
     visitDepthFirst(*translationUnit.getProgram(),
             [&](const AstClause& clause) { clauses[clause.getSrcLoc()] = &clause; });
     std::map<const AstClause*, long> longestTime;
     std::map<const AstClause*, Order> bestOrders;
     // extract best order for each clause
     for (const auto& cur : data) {
         const AstClause* clause = clauses[cur.first];
         assert(clause && "Unknown clause discovered!");
         for (const ExecutionSummary& instance : cur.second) {
             if (longestTime[clause] < instance.time) {
                 longestTime[clause] = instance.time;
                 bestOrders[clause] = instance.order;
             }
         }
     }
     if (verbose) {
         for (const auto& cur : bestOrders) {
             std::cout << *cur.first << "\n Best Order: " << cur.second
                       << "\n Time: " << longestTime[cur.first] << "\n\n";
         }
     }
     if (verbose) {
         std::cout << "[                                                    Done ]\n";
     }
     // step 4 - apply transformations
     if (verbose) {
         std::cout << "[ Re-scheduling rules ...                                 ]\n";
     }
     bool changed = false;
     for (const auto& cur : bestOrders) {
         AstClause* clause = const_cast<AstClause*>(cur.first);
         bool orderChanged = false;
         const std::vector<unsigned>& newOrder = cur.second.getOrder();
         // Check whether best order is different to the original order
         for (unsigned int i = 0; i < clause->getAtoms().size(); i++) {
             if (newOrder[i] != i) {
                 orderChanged = true;
                 break;
             }
         }
         if (orderChanged) {
             clause->reorderAtoms(newOrder);
             changed = true;
         }
     }
     if (verbose) {
         std::cout << "[                                                    Done ]\n";
     }
     // end with status message
     if (verbose) {
         std::cout << "---------------- Auto-Scheduling Completed -----------------\n";
     }
     return changed;
 }
std::string souffle::AutoScheduleTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 41 of file AstTuner.h.
{
         return "AutoScheduleTransformer";
     }
bool souffle::AutoScheduleTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 67 of file AstTuner.cpp.
References souffle::DebugReport::addSection(), autotune(), souffle::Global::config(), souffle::DebugReporter::getCodeSection(), and souffle::AstTranslationUnit::getDebugReport().
{
     bool changed = false;
     if (!Global::config().get("debug-report").empty()) {
         std::stringstream report;
         changed = autotune(translationUnit, &report);
         translationUnit.getDebugReport().addSection(
                 DebugReporter::getCodeSection("auto-schedule", "Auto Schedule Report", report.str()));
     } else {
         changed = autotune(translationUnit, nullptr);
     }
     return changed;
 }
The documentation for this class was generated from the following files:
AstTuner.h
AstTuner.cpp