souffle: souffle::Interpreter Class Reference
souffle::Interpreter Class Reference
A RAM interpreter.
#include <Interpreter.h>
Public Member Functions
std::unique_ptr
< InterpreterEnvironment > execute (SymbolTable &table, const RamProgram &prog) const
Runs the given RAM statement on an empty environment and returns this environment after the completion of the execution.
std::unique_ptr
< InterpreterEnvironment > execute (const RamTranslationUnit &tu) const
Runs the given RAM statement on an empty environment and returns this environment after the completion of the execution.
virtual void executeSubroutine (InterpreterEnvironment &env, const RamStatement &stmt, const std::vector< RamDomain > &arguments, std::vector< RamDomain > &returnValues, std::vector< bool > &returnErrors) const
Runs a subroutine of a RamProgram.
Interpreter (const QueryExecutionStrategy &queryStrategy)
A constructor accepting a query strategy.
void invoke (const RamProgram &prog, InterpreterEnvironment &env) const
run the program for a given interpreter environment
void setReportTarget (std::ostream &report)
Update logging stream.
Data Fields
QueryExecutionStrategy queryStrategy
An execution strategy for the interpreter.
Protected Attributes
std::ostream * report
An optional stream to print logging information to an output stream.
Detailed Description
A RAM interpreter.
The RAM program will be processed within the callers process. Before every query operation, an optional scheduling step will be conducted.
Definition at line 708 of file Interpreter.h.
Constructor & Destructor Documentation
souffle::Interpreter::Interpreter (const QueryExecutionStrategy & queryStrategy) inline
A constructor accepting a query strategy.
Definition at line 744 of file Interpreter.h.
             : report(nullptr), queryStrategy(queryStrategy) {}
Member Function Documentation
std::unique_ptr<InterpreterEnvironment> souffle::Interpreter::execute (SymbolTable & table, const RamProgram & prog) const inline
Runs the given RAM statement on an empty environment and returns this environment after the completion of the execution.
Definition at line 725 of file Interpreter.h.
References invoke().
Referenced by souffle::AutoScheduleTransformer::autotune(), and execute().
{
         auto env = std::make_unique<InterpreterEnvironment>(table);
         invoke(prog, *env);
         return env;
     }
std::unique_ptr<InterpreterEnvironment> souffle::Interpreter::execute (const RamTranslationUnit & tu) const inline
Runs the given RAM statement on an empty environment and returns this environment after the completion of the execution.
Definition at line 735 of file Interpreter.h.
References execute(), souffle::RamTranslationUnit::getProgram(), and souffle::RamTranslationUnit::getSymbolTable().
{
         return execute(tu.getSymbolTable(), *tu.getProgram());
     }
void souffle::Interpreter::executeSubroutine (InterpreterEnvironment & env, const RamStatement & stmt, const std::vector< RamDomain > & arguments, std::vector< RamDomain > & returnValues, std::vector< bool > & returnErrors) const virtual
Runs a subroutine of a RamProgram.
Definition at line 876 of file Interpreter.cpp.
References souffle::EvalContext::setArguments(), souffle::EvalContext::setReturnErrors(), and souffle::EvalContext::setReturnValues().
Referenced by souffle::InterpreterProgInterface::executeSubroutine().
{
     EvalContext ctxt;
     ctxt.setReturnValues(returnValues);
     ctxt.setReturnErrors(returnErrors);
     ctxt.setArguments(arguments);
     // run subroutine
     const RamOperation& op = static_cast<const RamInsert&>(stmt).getOperation();
     apply(op, env, ctxt);
 }
void souffle::Interpreter::invoke (const RamProgram & prog, InterpreterEnvironment & env) const
run the program for a given interpreter environment
Definition at line 856 of file Interpreter.cpp.
References souffle::Global::config(), souffle::RamProgram::getMain(), souffle::SignalHandler::instance(), souffle::SignalHandler::reset(), and souffle::SignalHandler::set().
Referenced by execute().
{
     SignalHandler::instance()->set();
     if (Global::config().has("profile")) {
         std::string fname = Global::config().get("profile");
         // open output stream
         std::ofstream os(fname);
         if (!os.is_open()) {
             throw std::invalid_argument("Cannot open profile log file <" + fname + ">");
         }
         os << "@start-debug\n";
         run(queryStrategy, report, &os, *(prog.getMain()), env);
     } else {
         run(queryStrategy, report, nullptr, *(prog.getMain()), env);
     }
     SignalHandler::instance()->reset();
 }
void souffle::Interpreter::setReportTarget (std::ostream & report) inline
Update logging stream.
Definition at line 717 of file Interpreter.h.
References report.
Referenced by souffle::AutoScheduleTransformer::autotune().
{
         this->report = &report;
     }
Field Documentation
QueryExecutionStrategy souffle::Interpreter::queryStrategy
An execution strategy for the interpreter.
Definition at line 740 of file Interpreter.h.
std::ostream* souffle::Interpreter::report protected
An optional stream to print logging information to an output stream.
Definition at line 711 of file Interpreter.h.
Referenced by setReportTarget().
The documentation for this class was generated from the following files:
Interpreter.h
Interpreter.cpp