souffle: souffle::shared_mutex Class Reference
souffle::shared_mutex Class Reference
#include <Util.h>
Public Member Functions
void lock ()
void lock_shared ()
shared_mutex ()
bool try_lock ()
bool try_lock_shared ()
void unlock ()
void unlock_shared ()
Private Attributes
std::condition_variable gate1_
std::condition_variable gate2_
std::mutex mut_
unsigned state_
Static Private Attributes
static const unsigned n_readers_ = ~write_entered_
static const unsigned write_entered_ = 1U << (sizeof(unsigned) * CHAR_BIT - 1)
Detailed Description
Definition at line 1152 of file Util.h.
Constructor & Destructor Documentation
souffle::shared_mutex::shared_mutex () inline
Definition at line 1162 of file Util.h.
 : state_(0) {}
Member Function Documentation
void souffle::shared_mutex::lock () inline
Definition at line 1165 of file Util.h.
Referenced by souffle::BinaryRelation< tuple_type >::clear(), souffle::DisjointSet::clear(), souffle::SparseDisjointSet< DomainInt >::clear(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::DisjointSet::genMap(), souffle::DisjointSet::makeNode(), and souffle::SparseDisjointSet< DomainInt >::toDense().
                 {
         std::unique_lock<std::mutex> lk(mut_);
         while (state_ & write_entered_) gate1_.wait(lk);
         state_ |= write_entered_;
         while (state_ & n_readers_) gate2_.wait(lk);
     }
void souffle::shared_mutex::lock_shared () inline
Definition at line 1190 of file Util.h.
Referenced by souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::SparseDisjointSet< DomainInt >::nodeExists(), souffle::DisjointSet::numInSet(), souffle::BinaryRelation< tuple_type >::size(), souffle::SparseDisjointSet< DomainInt >::toDense(), and souffle::SparseDisjointSet< DomainInt >::toSparse().
{
         std::unique_lock<std::mutex> lk(mut_);
         while ((state_ & write_entered_) || (state_ & n_readers_) == n_readers_) gate1_.wait(lk);
         unsigned num_readers = (state_ & n_readers_) + 1;
         state_ &= ~n_readers_;
         state_ |= num_readers;
     }
bool souffle::shared_mutex::try_lock () inline
Definition at line 1172 of file Util.h.
                     {
         std::unique_lock<std::mutex> lk(mut_, std::try_to_lock);
         if (lk.owns_lock() && state_ == 0) {
             state_ = write_entered_;
             return true;
         }
         return false;
     }
bool souffle::shared_mutex::try_lock_shared () inline
Definition at line 1198 of file Util.h.
{
         std::unique_lock<std::mutex> lk(mut_, std::try_to_lock);
         unsigned num_readers = state_ & n_readers_;
         if (lk.owns_lock() && !(state_ & write_entered_) && num_readers != n_readers_) {
             ++num_readers;
             state_ &= ~n_readers_;
             state_ |= num_readers;
             return true;
         }
         return false;
     }
void souffle::shared_mutex::unlock () inline
Definition at line 1181 of file Util.h.
Referenced by souffle::BinaryRelation< tuple_type >::clear(), souffle::DisjointSet::clear(), souffle::SparseDisjointSet< DomainInt >::clear(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::DisjointSet::genMap(), souffle::DisjointSet::makeNode(), and souffle::SparseDisjointSet< DomainInt >::toDense().
                   {
         {
             std::lock_guard<std::mutex> _(mut_);
             state_ = 0;
         }
         gate1_.notify_all();
     }
void souffle::shared_mutex::unlock_shared () inline
Definition at line 1211 of file Util.h.
Referenced by souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::SparseDisjointSet< DomainInt >::nodeExists(), souffle::DisjointSet::numInSet(), souffle::BinaryRelation< tuple_type >::size(), souffle::SparseDisjointSet< DomainInt >::toDense(), and souffle::SparseDisjointSet< DomainInt >::toSparse().
{
         std::lock_guard<std::mutex> _(mut_);
         unsigned num_readers = (state_ & n_readers_) - 1;
         state_ &= ~n_readers_;
         state_ |= num_readers;
         if (state_ & write_entered_) {
             if (num_readers == 0) gate2_.notify_one();
         } else {
             if (num_readers == n_readers_ - 1) gate1_.notify_one();
         }
     }
Field Documentation
std::condition_variable souffle::shared_mutex::gate1_ private
Definition at line 1154 of file Util.h.
std::condition_variable souffle::shared_mutex::gate2_ private
Definition at line 1155 of file Util.h.
std::mutex souffle::shared_mutex::mut_ private
Definition at line 1153 of file Util.h.
const unsigned souffle::shared_mutex::n_readers_ = ~write_entered_ static private
Definition at line 1159 of file Util.h.
unsigned souffle::shared_mutex::state_ private
Definition at line 1156 of file Util.h.
const unsigned souffle::shared_mutex::write_entered_ = 1U << (sizeof(unsigned) * CHAR_BIT - 1) static private
Definition at line 1158 of file Util.h.
The documentation for this class was generated from the following file:
Util.h