souffle: souffle::scheduler::SimpleComputationalCostAtom Class Reference
souffle::scheduler::SimpleComputationalCostAtom Class Reference
An extended version of the atom utilized by the simple computational cost model which required the cardinality of the targeted relation.
#include <RuleScheduler.h>
Public Member Functions
unsigned getCardinality () const
void print (std::ostream &out) const override
SimpleComputationalCostAtom (int id, const std::vector< Argument > &args, std::size_t card)
Public Member Functions inherited from souffle::scheduler::Atom
Atom (int id, const std::vector< Argument > &args)
const std::vector< Argument > & getArguments () const
Obtains the list of (abstracted) arguments exposed by this atom.
unsigned getArity () const
Obtains the arity of the targeted relation.
int getID () const
Obtains the identifier of this atom.
unsigned getNumConstants () const
Obtains the number of constant arguments.
std::vector< Var > getVariables () const
Obtains a list of the variable arguments.
bool operator< (const Atom &other) const
bool operator== (const Atom &other) const
virtual ~Atom ()=default
Private Attributes
std::size_t cardinality
Additional Inherited Members
Data Fields inherited from souffle::scheduler::Atom
std::vector< Argument > args
The list of arguments of this atom.
int id
An ID of this atom, making it unique.
Detailed Description
An extended version of the atom utilized by the simple computational cost model which required the cardinality of the targeted relation.
Definition at line 463 of file RuleScheduler.h.
Constructor & Destructor Documentation
souffle::scheduler::SimpleComputationalCostAtom::SimpleComputationalCostAtom (int id, const std::vector< Argument > & args, std::size_t card) inline
Definition at line 467 of file RuleScheduler.h.
             : Atom(id, args), cardinality(card) {}
Member Function Documentation
unsigned souffle::scheduler::SimpleComputationalCostAtom::getCardinality () const inline
Definition at line 470 of file RuleScheduler.h.
References cardinality.
Referenced by souffle::scheduler::SimpleComputationalCostModel::applyTo(), and souffle::scheduler::LogCostModel::applyTo().
{
         return cardinality;
     }
void souffle::scheduler::SimpleComputationalCostAtom::print (std::ostream & out) const inline override virtual
Reimplemented from souffle::scheduler::Atom.
Definition at line 474 of file RuleScheduler.h.
References cardinality, souffle::scheduler::Atom::getArguments(), and souffle::scheduler::Atom::getID().
{
         out << "<" << getID() << ">|" << cardinality << "|( " << getArguments() << " )";
     }
Field Documentation
std::size_t souffle::scheduler::SimpleComputationalCostAtom::cardinality private
Definition at line 464 of file RuleScheduler.h.
Referenced by getCardinality(), and print().
The documentation for this class was generated from the following file:
RuleScheduler.h