souffle: souffle::SymbolTable Class Reference
souffle::SymbolTable Class Reference
Global pool of re-usable strings.
#include <SymbolTable.h>
Public Member Functions
Lock::Lease acquireLock () const
void insert (const char **symbols, const size_t n)
Bulk insert symbols into the table, note that this operation is more efficient than repeated inserts of single symbols.
void insert (const char *symbol)
Insert a single symbol into the table, not that this operation should not be used if inserting symbols in bulk.
const size_t lookup (const char *symbol)
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
const size_t lookupExisting (const char *str) const
Finds the index of a symbol in the table, giving an error if it's not found.
SymbolTable & operator= (const SymbolTable &other)
Assignment operator, performs a deep copy and frees memory allocated for all strings.
SymbolTable & operator= (SymbolTable &&other) noexcept
Assignment operator for r-value references.
void print (std::ostream &out) const
Print the symbol table to the given stream.
const char * resolve (const size_t idx) const
Find a symbol in the table by its index, note that this gives an error if the index is out of bounds.
const size_t size () const
SymbolTable ()
Empty constructor.
SymbolTable (const SymbolTable &other)
Copy constructor, performs a deep copy.
SymbolTable (SymbolTable &&other) noexcept
Copy constructor for r-value reference.
const size_t unsafeLookup (const char *symbol)
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
const char * unsafeResolve (const size_t idx) const
virtual ~SymbolTable ()
Destructor, frees memory allocated for all strings.
Private Member Functions
void copyAll ()
Convenience method to copy strings between symbol tables and resolve their references.
void freeAll ()
Convenience method to free memory allocated for strings.
void newSymbol (const char *symbol)
Convenience method to place a new symbol in the table, if it does not exist.
const size_t newSymbolOfIndex (const char *symbol)
Convenience method to place a new symbol in the table, if it does not exist, and return the index of it.
Private Attributes
Lock access
A lock to synchronize parallel accesses.
std::vector< char * > numToStr
Map indices to strings.
std::unordered_map
< std::string, size_t > strToNum
Map strings to indices.
Friends
std::ostream & operator<< (std::ostream &out, const SymbolTable &table)
Stream operator, used as a convenience for print.
Detailed Description
Global pool of re-usable strings.
SymbolTable stores Datalog symbols and converts them to numbers and vice versa.
Definition at line 37 of file SymbolTable.h.
Constructor & Destructor Documentation
souffle::SymbolTable::SymbolTable () inline
Empty constructor.
Definition at line 92 of file SymbolTable.h.
 {}
souffle::SymbolTable::SymbolTable (const SymbolTable & other) inline
Copy constructor, performs a deep copy.
Definition at line 95 of file SymbolTable.h.
References copyAll().
                                           : numToStr(other.numToStr), strToNum(other.strToNum) {
         copyAll();
     }
souffle::SymbolTable::SymbolTable (SymbolTable && other) inline noexcept
Copy constructor for r-value reference.
Definition at line 100 of file SymbolTable.h.
References numToStr, and strToNum.
{
         numToStr.swap(other.numToStr);
         strToNum.swap(other.strToNum);
     }
virtual souffle::SymbolTable::~SymbolTable () inline virtual
Destructor, frees memory allocated for all strings.
Definition at line 106 of file SymbolTable.h.
References freeAll().
{
         freeAll();
     }
Member Function Documentation
Lock::Lease souffle::SymbolTable::acquireLock () const inline
Definition at line 206 of file SymbolTable.h.
References access, and souffle::Lock::acquire().
Referenced by souffle::ReadStream::readAll(), and souffle::WriteStream::writeAll().
{
         return access.acquire();
     }
void souffle::SymbolTable::copyAll () inline private
Convenience method to copy strings between symbol tables and resolve their references.
Definition at line 49 of file SymbolTable.h.
References numToStr, and strToNum.
Referenced by operator=(), and SymbolTable().
{
         for (auto& cur : numToStr) {
             cur = strdup(cur);
         }
         for (auto& cur : strToNum) {
             const_cast<std::string&>(cur.first) = numToStr[cur.second];
         }
     }
void souffle::SymbolTable::freeAll () inline private
Convenience method to free memory allocated for strings.
Definition at line 59 of file SymbolTable.h.
References numToStr.
Referenced by operator=(), and ~SymbolTable().
{
         for (auto cur : numToStr) {
             free(cur);
         }
     }
void souffle::SymbolTable::insert (const char ** symbols, const size_t n) inline
Bulk insert symbols into the table, note that this operation is more efficient than repeated inserts of single symbols.
Definition at line 178 of file SymbolTable.h.
References access, souffle::Lock::acquire(), newSymbol(), numToStr, size(), and strToNum.
{
         auto lease = access.acquire();
         (void)lease;  // avoid warning;
         strToNum.reserve(size() + n);
         numToStr.reserve(size() + n);
         for (size_t idx = 0; idx < n; idx++) {
             newSymbol(symbols[idx]);
         }
     }
void souffle::SymbolTable::insert (const char * symbol) inline
Insert a single symbol into the table, not that this operation should not be used if inserting symbols in bulk.
Definition at line 190 of file SymbolTable.h.
References access, souffle::Lock::acquire(), and newSymbol().
{
         auto lease = access.acquire();
         (void)lease;  // avoid warning;
         newSymbol(symbol);
     }
const size_t souffle::SymbolTable::lookup (const char * symbol) inline
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
Definition at line 130 of file SymbolTable.h.
References access, souffle::Lock::acquire(), and newSymbolOfIndex().
Referenced by souffle::tuple::operator<<().
{
         auto lease = access.acquire();
         (void)lease;  // avoid warning;
         return newSymbolOfIndex(symbol);
     }
const size_t souffle::SymbolTable::lookupExisting (const char * str) const inline
Finds the index of a symbol in the table, giving an error if it's not found.
Definition at line 137 of file SymbolTable.h.
References access, souffle::Lock::acquire(), and strToNum.
Referenced by souffle::ExplainProvenance::argsToNums(), and souffle::ExplainProvenanceSLD::findTuple().
{
         auto lease = access.acquire();
         (void)lease;  // avoid warning;
         auto result = strToNum.find(str);
         if (result == strToNum.end()) {
             std::cerr << "Error string not found in call to SymbolTable::lookupExisting.\n";
             exit(1);
         } else {
             return result->second;
         }
     }
void souffle::SymbolTable::newSymbol (const char * symbol) inline private
Convenience method to place a new symbol in the table, if it does not exist.
Definition at line 82 of file SymbolTable.h.
References numToStr, and strToNum.
Referenced by insert().
{
         if (strToNum.find(symbol) == strToNum.end()) {
             char* str = strdup(symbol);
             strToNum[str] = numToStr.size();
             numToStr.push_back(str);
         }
     }
const size_t souffle::SymbolTable::newSymbolOfIndex (const char * symbol) inline private
Convenience method to place a new symbol in the table, if it does not exist, and return the index of it.
Definition at line 67 of file SymbolTable.h.
References numToStr, and strToNum.
Referenced by lookup(), and unsafeLookup().
{
         size_t idx;
         auto it = strToNum.find(symbol);
         if (it == strToNum.end()) {
             char* str = strdup(symbol);
             idx = numToStr.size();
             strToNum[str] = idx;
             numToStr.push_back(str);
         } else {
             idx = it->second;
         }
         return idx;
     }
SymbolTable& souffle::SymbolTable::operator= (const SymbolTable & other) inline
Assignment operator, performs a deep copy and frees memory allocated for all strings.
Definition at line 111 of file SymbolTable.h.
References copyAll(), freeAll(), numToStr, and strToNum.
{
         if (this == &other) {
             return *this;
         }
         freeAll();
         numToStr = other.numToStr;
         strToNum = other.strToNum;
         copyAll();
         return *this;
     }
SymbolTable& souffle::SymbolTable::operator= (SymbolTable && other) inline noexcept
Assignment operator for r-value references.
Definition at line 123 of file SymbolTable.h.
References numToStr, and strToNum.
{
         numToStr.swap(other.numToStr);
         strToNum.swap(other.strToNum);
         return *this;
     }
void souffle::SymbolTable::print (std::ostream & out) const inline
Print the symbol table to the given stream.
Definition at line 197 of file SymbolTable.h.
References souffle::join(), and strToNum.
{
         out << "SymbolTable: {\n\t";
         out << join(strToNum, "\n\t", [](std::ostream& out,
                                               const std::pair<std::string, std::size_t>& entry) {
             out << entry.first << "\t => " << entry.second;
         }) << "\n";
         out << "}\n";
     }
const char* souffle::SymbolTable::resolve (const size_t idx) const inline
Find a symbol in the table by its index, note that this gives an error if the index is out of bounds.
Definition at line 156 of file SymbolTable.h.
References access, souffle::Lock::acquire(), numToStr, and size().
Referenced by souffle::Synthesiser::generateCode(), souffle::AstStringConstant::getConstant(), souffle::ExplainProvenance::numsToArgs(), souffle::InterpreterRelInterface::iterator_base::operator*(), and souffle::tuple::operator>>().
{
         auto lease = access.acquire();
         (void)lease;  // avoid warning;
         if (idx >= size()) {
             // TODO: use different error reporting here!!
             std::cerr << "Error index out of bounds in call to SymbolTable::resolve.\n";
             exit(1);
         }
         return numToStr[idx];
     }
const size_t souffle::SymbolTable::size () const inline
Definition at line 172 of file SymbolTable.h.
References numToStr.
Referenced by souffle::Synthesiser::generateCode(), insert(), and resolve().
{
         return numToStr.size();
     }
const size_t souffle::SymbolTable::unsafeLookup (const char * symbol) inline
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
Definition at line 150 of file SymbolTable.h.
References newSymbolOfIndex().
Referenced by souffle::ReadStreamSQLite::readNextTuple(), and souffle::ReadStreamCSV::readNextTuple().
{
         return newSymbolOfIndex(symbol);
     }
const char* souffle::SymbolTable::unsafeResolve (const size_t idx) const inline
Definition at line 167 of file SymbolTable.h.
References numToStr.
Referenced by souffle::WriteStreamSQLite::getSymbolTableID(), souffle::WriteStreamSQLite::getSymbolTableIDFromDB(), souffle::WriteFileCSV::writeNextTuple(), and souffle::WriteCoutCSV::writeNextTuple().
{
         return numToStr[idx];
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const SymbolTable & table) friend
Stream operator, used as a convenience for print.
Definition at line 211 of file SymbolTable.h.
{
         table.print(out);
         return out;
     }
Field Documentation
Lock souffle::SymbolTable::access mutable private
A lock to synchronize parallel accesses.
Definition at line 39 of file SymbolTable.h.
Referenced by acquireLock(), insert(), lookup(), lookupExisting(), and resolve().
std::vector<char*> souffle::SymbolTable::numToStr private
Map indices to strings.
Definition at line 43 of file SymbolTable.h.
Referenced by copyAll(), freeAll(), insert(), newSymbol(), newSymbolOfIndex(), operator=(), resolve(), size(), SymbolTable(), and unsafeResolve().
std::unordered_map<std::string, size_t> souffle::SymbolTable::strToNum private
Map strings to indices.
Definition at line 46 of file SymbolTable.h.
Referenced by copyAll(), insert(), lookupExisting(), newSymbol(), newSymbolOfIndex(), operator=(), print(), and SymbolTable().
The documentation for this class was generated from the following file:
SymbolTable.h