souffle: souffle::scheduler::SimpleComputationalCostState Class Reference
souffle::scheduler::SimpleComputationalCostState Class Reference
The state associated to the simple computational cost model maintaining a set of bound variables and an estimation for the number of innermost loop iterations.
#include <RuleScheduler.h>
Public Member Functions
void bind (const Var &var)
uint64_t getInnermostIterations () const
bool isBound (const Var &var) const
void print (std::ostream &out) const override
void setInnermostIterations (uint64_t val)
SimpleComputationalCostState ()
Public Member Functions inherited from souffle::scheduler::State
Cost getCost () const
void incCost (Cost inc)
void setCost (Cost cost)
State ()
virtual ~State ()=default
Private Attributes
std::set< Var > bound
The set of bound variables at this state.
uint64_t innermostIterations
The estimated number of innermost iterations at this state.
Detailed Description
The state associated to the simple computational cost model maintaining a set of bound variables and an estimation for the number of innermost loop iterations.
Definition at line 484 of file RuleScheduler.h.
Constructor & Destructor Documentation
souffle::scheduler::SimpleComputationalCostState::SimpleComputationalCostState () inline
Definition at line 492 of file RuleScheduler.h.
 : innermostIterations(1) {}
Member Function Documentation
void souffle::scheduler::SimpleComputationalCostState::bind (const Var & var) inline
Definition at line 494 of file RuleScheduler.h.
References bound.
Referenced by souffle::scheduler::SimpleComputationalCostModel::applyTo().
{
         bound.insert(var);
     }
uint64_t souffle::scheduler::SimpleComputationalCostState::getInnermostIterations () const inline
Definition at line 502 of file RuleScheduler.h.
References innermostIterations.
Referenced by souffle::scheduler::SimpleComputationalCostModel::applyTo().
{
         return innermostIterations;
     }
bool souffle::scheduler::SimpleComputationalCostState::isBound (const Var & var) const inline
Definition at line 498 of file RuleScheduler.h.
References bound.
Referenced by souffle::scheduler::SimpleComputationalCostModel::applyTo().
{
         return bound.find(var) != bound.end();
     }
void souffle::scheduler::SimpleComputationalCostState::print (std::ostream & out) const inline override virtual
Implements souffle::scheduler::State.
Definition at line 510 of file RuleScheduler.h.
References bound, souffle::scheduler::State::getCost(), and innermostIterations.
{
         out << "State(" << getCost() << "," << bound << "," << innermostIterations << ")";
     }
void souffle::scheduler::SimpleComputationalCostState::setInnermostIterations (uint64_t val) inline
Definition at line 506 of file RuleScheduler.h.
References innermostIterations.
Referenced by souffle::scheduler::SimpleComputationalCostModel::applyTo().
{
         innermostIterations = val;
     }
Field Documentation
std::set<Var> souffle::scheduler::SimpleComputationalCostState::bound private
The set of bound variables at this state.
Definition at line 486 of file RuleScheduler.h.
Referenced by bind(), isBound(), and print().
uint64_t souffle::scheduler::SimpleComputationalCostState::innermostIterations private
The estimated number of innermost iterations at this state.
Definition at line 489 of file RuleScheduler.h.
Referenced by getInnermostIterations(), print(), and setInnermostIterations().
The documentation for this class was generated from the following file:
RuleScheduler.h