souffle: souffle::AstConstraint Class Reference
souffle::AstConstraint Class Reference
Subclass of Literal that represents a binary constraint e.g., x = y.
#include <AstLiteral.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Mutates this node.
AstConstraint (BinaryConstraintOp o, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs)
AstConstraint (const std::string &op, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs)
AstConstraint * clone () const override
Creates a clone if this AST sub-structure.
const AstAtom * getAtom () const override
This kind of literal has no nested atom.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
AstArgument * getLHS () const
Return LHS argument.
BinaryConstraintOp getOperator () const
Return binary operator.
AstArgument * getRHS () const
Return RHS argument.
const bool isNumerical () const
Check whether constraint is a numeric constraint.
const bool isSymbolic () const
Check whether constraint is a symbolic constraint.
void negate ()
Negates the constraint.
void print (std::ostream &os) const override
Output the constraint to a given stream.
void setOperator (BinaryConstraintOp op)
Update the binary operator.
~AstConstraint () override=default
Public Member Functions inherited from souffle::AstLiteral
AstLiteral ()
~AstLiteral () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
AstSrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const AstSrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::unique_ptr< AstArgument > lhs
Left-hand side argument of a binary operation.
BinaryConstraintOp operation
The operator in this relation.
std::unique_ptr< AstArgument > rhs
Right-hand side argument of a binary operation.
Detailed Description
Subclass of Literal that represents a binary constraint e.g., x = y.
Definition at line 231 of file AstLiteral.h.
Constructor & Destructor Documentation
souffle::AstConstraint::AstConstraint (BinaryConstraintOp o, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs) inline
Definition at line 243 of file AstLiteral.h.
Referenced by clone().
             : operation(o), lhs(std::move(ls)), rhs(std::move(rs)) {}
souffle::AstConstraint::AstConstraint (const std::string & op, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs) inline
Definition at line 246 of file AstLiteral.h.
             : operation(toBinaryConstraintOp(op)), lhs(std::move(ls)), rhs(std::move(rs)) {}
souffle::AstConstraint::~AstConstraint () override default
Member Function Documentation
void souffle::AstConstraint::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 307 of file AstLiteral.h.
References lhs, map, and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
AstConstraint* souffle::AstConstraint::clone () const inline override virtual
Creates a clone if this AST sub-structure.
Implements souffle::AstLiteral.
Definition at line 299 of file AstLiteral.h.
References AstConstraint(), souffle::AstNode::getSrcLoc(), lhs, operation, rhs, and souffle::AstNode::setSrcLoc().
Referenced by souffle::negateLiteral().
{
         AstConstraint* res = new AstConstraint(operation, std::unique_ptr<AstArgument>(lhs->clone()),
                 std::unique_ptr<AstArgument>(rhs->clone()));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstConstraint::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 319 of file AstLiteral.h.
References lhs, node, operation, and rhs.
{
         assert(dynamic_cast<const AstConstraint*>(&node));
         const AstConstraint& other = static_cast<const AstConstraint&>(node);
         return operation == other.operation && *lhs == *other.lhs && *rhs == *other.rhs;
     }
const AstAtom* souffle::AstConstraint::getAtom () const inline override virtual
This kind of literal has no nested atom.
Implements souffle::AstLiteral.
Definition at line 252 of file AstLiteral.h.
{
         return nullptr;
     }
std::vector<const AstNode*> souffle::AstConstraint::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 313 of file AstLiteral.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
AstArgument* souffle::AstConstraint::getLHS () const inline
Return LHS argument.
Definition at line 257 of file AstLiteral.h.
References lhs.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getConstTerms(), souffle::getGroundedTerms(), souffle::getInlinedLiteral(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::Adornment::run(), and souffle::detail::BddbddbConverter::visitConstraint().
{
         return lhs.get();
     }
BinaryConstraintOp souffle::AstConstraint::getOperator () const inline
Return binary operator.
Definition at line 267 of file AstLiteral.h.
References operation.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::getConstTerms(), souffle::getGroundedTerms(), souffle::getInlinedLiteral(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::Adornment::run(), and souffle::detail::BddbddbConverter::visitConstraint().
{
         return operation;
     }
AstArgument* souffle::AstConstraint::getRHS () const inline
Return RHS argument.
Definition at line 262 of file AstLiteral.h.
References rhs.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getConstTerms(), souffle::getGroundedTerms(), souffle::getInlinedLiteral(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::Adornment::run(), and souffle::detail::BddbddbConverter::visitConstraint().
{
         return rhs.get();
     }
const bool souffle::AstConstraint::isNumerical () const inline
Check whether constraint is a numeric constraint.
Definition at line 282 of file AstLiteral.h.
References souffle::isNumericBinaryConstraintOp(), and operation.
Referenced by souffle::AstSemanticChecker::checkProgram().
{
         return isNumericBinaryConstraintOp(operation);
     }
const bool souffle::AstConstraint::isSymbolic () const inline
Check whether constraint is a symbolic constraint.
Definition at line 287 of file AstLiteral.h.
References souffle::isSymbolicBinaryConstraintOp(), and operation.
Referenced by souffle::AstSemanticChecker::checkProgram().
{
         return isSymbolicBinaryConstraintOp(operation);
     }
void souffle::AstConstraint::negate () inline
Negates the constraint.
Definition at line 277 of file AstLiteral.h.
References souffle::negatedConstraintOp(), operation, and setOperator().
Referenced by souffle::negateLiteral().
                   {
         setOperator(souffle::negatedConstraintOp(operation));
     }
void souffle::AstConstraint::print (std::ostream & os) const inline override virtual
Output the constraint to a given stream.
Implements souffle::AstNode.
Definition at line 292 of file AstLiteral.h.
References lhs, operation, rhs, and souffle::toBinaryConstraintSymbol().
{
         lhs->print(os);
         os << " " << toBinaryConstraintSymbol(operation) << " ";
         rhs->print(os);
     }
void souffle::AstConstraint::setOperator (BinaryConstraintOp op) inline
Update the binary operator.
Definition at line 272 of file AstLiteral.h.
References operation.
Referenced by negate().
{
         operation = op;
     }
Field Documentation
std::unique_ptr<AstArgument> souffle::AstConstraint::lhs protected
Left-hand side argument of a binary operation.
Definition at line 237 of file AstLiteral.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getLHS(), and print().
BinaryConstraintOp souffle::AstConstraint::operation protected
The operator in this relation.
Definition at line 234 of file AstLiteral.h.
Referenced by clone(), equal(), getOperator(), isNumerical(), isSymbolic(), negate(), print(), and setOperator().
std::unique_ptr<AstArgument> souffle::AstConstraint::rhs protected
Right-hand side argument of a binary operation.
Definition at line 240 of file AstLiteral.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRHS(), and print().
The documentation for this class was generated from the following file:
AstLiteral.h