souffle: souffle::detail::BddbddbConverter Class Reference
souffle::detail::BddbddbConverter Class Reference
Public Member Functions
BddbddbConverter ()
void convert (std::ostream &out, const AstProgram &program)
Private Member Functions
void visitAtom (const AstAtom &atom, std::ostream &out) override
void visitClause (const AstClause &clause, std::ostream &out) override
Converting a clause.
void visitConstraint (const AstConstraint &cnstr, std::ostream &out) override
void visitFunctor (const AstFunctor &fun, std::ostream &out) override
void visitNegation (const AstNegation &neg, std::ostream &out) override
void visitNode (const AstNode &node, std::ostream &) override
void visitNumberConstant (const AstNumberConstant &num, std::ostream &out) override
void visitProgram (const AstProgram &program, std::ostream &out) override
The entry point for the conversion of a program, converting the basic top-level structure.
void visitRelation (const AstRelation &rel, std::ostream &out) override
Converting a relation by creating its declaration.
void visitRelationIdentifier (const AstRelationIdentifier &id, std::ostream &out)
void visitStringConstant (const AstStringConstant &str, std::ostream &out) override
void visitTypeCast (const AstTypeCast &cast, std::ostream &out) override
void visitUnnamedVariable (const AstUnnamedVariable &var, std::ostream &out) override
void visitVariable (const AstVariable &var, std::ostream &out) override
Private Member Functions inherited from souffle::AstVisitor< void, std::ostream & >
void operator() (const AstNode &node, Params...args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const AstNode &node, Params...args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of AstNodes.
virtual ~AstVisitor ()=default
A virtual destructor.
LINK (PrimitiveType, Type)
LINK (RecordType, Type)
LINK (UnionType, Type)
LINK (Type, Node)
LINK (Argument, Node)
LINK (Literal, Node)
LINK (Program, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (IODirective, Node)
LINK (Relation, Node)
LINK (Pragma, Node)
virtual void visitNode (const AstNode &, Params...)
The base case for all visitors – if no more specific overload was defined.
Private Attributes
std::vector< std::string > extra_literals
int varCounter
Detailed Description
Definition at line 31 of file BddbddbBackend.cpp.
Constructor & Destructor Documentation
souffle::detail::BddbddbConverter::BddbddbConverter () inline
Definition at line 38 of file BddbddbBackend.cpp.
 : varCounter(0) {}
Member Function Documentation
void souffle::detail::BddbddbConverter::convert (std::ostream & out, const AstProgram & program) inline
Definition at line 40 of file BddbddbBackend.cpp.
References souffle::AstVisitor< void, std::ostream & >::visit().
Referenced by souffle::toBddbddb().
{
         visit(program, out);
     }
void souffle::detail::BddbddbConverter::visitAtom (const AstAtom & atom, std::ostream & out) inline override private
Definition at line 140 of file BddbddbBackend.cpp.
References souffle::AstAtom::getArguments(), souffle::AstAtom::getName(), souffle::join(), souffle::AstVisitor< void, std::ostream & >::visit(), and visitRelationIdentifier().
{
         visitRelationIdentifier(atom.getName(), out);
         // since no nullary-relations are allowed, we add a dummy value
         if (atom.getArguments().empty()) {
             out << "(0)";
             return;
         }
         out << "(";
         out << join(atom.getArguments(), ",", [&](std::ostream& out, AstArgument* cur) { visit(*cur, out); });
         out << ")";
     }
void souffle::detail::BddbddbConverter::visitClause (const AstClause & clause, std::ostream & out) inline override private
Converting a clause.
Definition at line 112 of file BddbddbBackend.cpp.
References extra_literals, souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstClause::isFact(), souffle::join(), souffle::toString(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         visit(*clause.getHead(), out);
         // if it is a fact, that's it
         if (clause.isFact()) {
             // there must not be any additons
             if (!extra_literals.empty()) {
                 throw UnsupportedConstructException("Unsupported fact: " + toString(clause));
             }
             out << ".\n";
             return;
         }
         // convert the body
         out << " :- ";
         out << join(
                 clause.getBodyLiterals(), ",", [&](std::ostream& out, AstLiteral* cur) { visit(*cur, out); });
         // add extra_literals
         for (const auto& cur : extra_literals) {
             out << "," << cur;
         }
         extra_literals.clear();
         // done
         out << ".\n";
     }
void souffle::detail::BddbddbConverter::visitConstraint (const AstConstraint & cnstr, std::ostream & out) inline override private
Definition at line 159 of file BddbddbBackend.cpp.
References souffle::AstConstraint::getLHS(), souffle::AstConstraint::getOperator(), souffle::AstConstraint::getRHS(), souffle::toBinaryConstraintSymbol(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         visit(*cnstr.getLHS(), out);
         out << toBinaryConstraintSymbol(cnstr.getOperator());
         visit(*cnstr.getRHS(), out);
     }
void souffle::detail::BddbddbConverter::visitFunctor (const AstFunctor & fun, std::ostream & out) inline override private
Definition at line 178 of file BddbddbBackend.cpp.
References extra_literals, souffle::getSymbolForBinaryOp(), souffle::toString(), varCounter, and souffle::AstVisitor< void, std::ostream & >::visit().
{
         // create a new variable
         std::string var = "aux_var_" + toString(varCounter++);
         // write variable
         out << var;
         // assign variable in extra clause
         std::stringstream binding;
         binding << var << "=";
         // process unary operators
         if (dynamic_cast<const AstUnaryFunctor*>(&fun)) {
             // binary functors are not supported
             throw UnsupportedConstructException("Unsupported function: " + toString(fun));
         } else if (const AstBinaryFunctor* binary = dynamic_cast<const AstBinaryFunctor*>(&fun)) {
             visit(*binary->getLHS(), binding);
             binding << getSymbolForBinaryOp(binary->getFunction());
             visit(*binary->getRHS(), binding);
         } else {
             assert(false && "Unsupported functor!");
         }
         extra_literals.push_back(binding.str());
     }
void souffle::detail::BddbddbConverter::visitNegation (const AstNegation & neg, std::ostream & out) inline override private
Definition at line 154 of file BddbddbBackend.cpp.
References souffle::AstNegation::getAtom(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         out << "!";
         visit(*neg.getAtom(), out);
     }
void souffle::detail::BddbddbConverter::visitNode (const AstNode & node, std::ostream &) inline override private
Definition at line 215 of file BddbddbBackend.cpp.
References souffle::toString().
{
         throw UnsupportedConstructException(
                 "Unable to convert the following language construct into bddbddb format: " + toString(node));
     }
void souffle::detail::BddbddbConverter::visitNumberConstant (const AstNumberConstant & num, std::ostream & out) inline override private
Definition at line 170 of file BddbddbBackend.cpp.
{
         out << num;
     }
void souffle::detail::BddbddbConverter::visitProgram (const AstProgram & program, std::ostream & out) inline override private
The entry point for the conversion of a program, converting the basic top-level structure.
Definition at line 48 of file BddbddbBackend.cpp.
References souffle::AstProgram::getRelations(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         // type definition
         out << "N " << std::numeric_limits<RamDomain>::max() << "\n\n";
         // variable order
         int max_attributes = 0;
         for (const auto& rel : program.getRelations()) {
             max_attributes = std::max<int>(max_attributes, rel->getAttributes().size());
         }
         out << ".bddvarorder ";
         for (int i = 0; i < max_attributes; i++) {
             out << "N" << i;
             if (i + 1 != max_attributes) {
                 out << "_";
             }
         }
         out << "\n\n";
         // declarations
         for (const auto& rel : program.getRelations()) {
             // process the relation declaration
             visit(*rel, out);
         }
         out << "\n";
         // rules
         for (const auto& rel : program.getRelations()) {
             for (const auto& clause : rel->getClauses()) {
                 visit(*clause, out);
             }
         }
         out << "\n";
     }
void souffle::detail::BddbddbConverter::visitRelation (const AstRelation & rel, std::ostream & out) inline override private
Converting a relation by creating its declaration.
Definition at line 85 of file BddbddbBackend.cpp.
References souffle::AstRelation::getAttributes(), souffle::AstRelation::getName(), souffle::AstRelation::isInput(), souffle::AstRelation::isOutput(), souffle::join(), and visitRelationIdentifier().
{
         visitRelationIdentifier(rel.getName(), out);
         // make nullary relations single-element relations
         out << "(";
         if (rel.getAttributes().empty()) {
             out << "dummy:N0";
         }
         int i = 0;
         out << join(rel.getAttributes(), ",", [&](std::ostream& out, AstAttribute* cur) {
             out << cur->getAttributeName() << ":N" << (i++);
         });
         out << ")";
         if (rel.isInput()) {
             out << " inputtuples";
         }
         if (rel.isOutput()) {
             out << " outputtuples";
         }
         out << "\n";
     }
void souffle::detail::BddbddbConverter::visitRelationIdentifier (const AstRelationIdentifier & id, std::ostream & out) inline private
Definition at line 211 of file BddbddbBackend.cpp.
References souffle::join().
Referenced by visitAtom(), and visitRelation().
{
         out << join(id.getNames(), "_");
     }
void souffle::detail::BddbddbConverter::visitStringConstant (const AstStringConstant & str, std::ostream & out) inline override private
Definition at line 165 of file BddbddbBackend.cpp.
References souffle::AstConstant::getIndex().
{
         // we dump the index to the output, not the string itself
         out << str.getIndex();
     }
void souffle::detail::BddbddbConverter::visitTypeCast (const AstTypeCast & cast, std::ostream & out) inline override private
Definition at line 174 of file BddbddbBackend.cpp.
References souffle::AstTypeCast::getValue(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         visit(*cast.getValue(), out);
     }
void souffle::detail::BddbddbConverter::visitUnnamedVariable (const AstUnnamedVariable & var, std::ostream & out) inline override private
Definition at line 207 of file BddbddbBackend.cpp.
{
         out << "_";
     }
void souffle::detail::BddbddbConverter::visitVariable (const AstVariable & var, std::ostream & out) inline override private
Definition at line 203 of file BddbddbBackend.cpp.
{
         out << var;
     }
Field Documentation
std::vector<std::string> souffle::detail::BddbddbConverter::extra_literals private
Definition at line 33 of file BddbddbBackend.cpp.
Referenced by visitClause(), and visitFunctor().
int souffle::detail::BddbddbConverter::varCounter private
Definition at line 35 of file BddbddbBackend.cpp.
Referenced by visitFunctor().
The documentation for this class was generated from the following file:
BddbddbBackend.cpp