souffle: souffle::AutoIndex Class Reference
souffle::AutoIndex Class Reference
#include <AutoIndex.h>
Public Types
typedef std::vector< int > LexicographicalOrder
typedef std::vector
< LexicographicalOrder > OrderCollection
Public Member Functions
void addSearch (SearchColumns cols)
add new key to an Index Set
AutoIndex ()
const OrderCollection getAllOrders () const
const LexicographicalOrder getLexOrder (SearchColumns cols) const
const SearchSet & getSearches () const
obtains access to the internally stored keys
bool isSubset (SearchColumns cols) const
check whether number of bits in k is not equal to number of columns in lexicographical order
void setHashmap (bool flag)
Set Hashmap.
void solve ()
map the keys in the key set to lexicographical order
Static Public Member Functions
static SearchColumns toA (SearchColumns b)
convert from a representation of B verticies to A verticies
static SearchColumns toB (SearchColumns a)
convert from a representation of A verticies to B verticies
Protected Types
typedef std::set< SearchColumns > Chain
typedef std::vector< Chain > ChainOrderMap
typedef std::set< SearchColumns > SearchSet
Protected Member Functions
Chain getChain (const SearchColumns umn, const MaxMatching::Matchings &match)
given an unmapped node from set A we follow it from set B until it cannot be matched from B if not mateched from B then umn is a chain
const ChainOrderMap getChainsFromMatching (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all chains from the matching
const SearchSet getUnmatchedKeys (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all nodes which are unmated from A-> B
void insertIndex (std::vector< int > &ids, SearchColumns delta)
insert an index based on the delta
int map (SearchColumns cols) const
maps search columns to an lexicographical order (labeled by a number)
Static Protected Member Functions
static size_t card (SearchColumns cols)
count the number of bits in key
static bool isStrictSubset (SearchColumns a, SearchColumns b)
determine if key a is a strict subset of key b
Protected Attributes
ChainOrderMap chainToOrder
bool isHashmap
MaxMatching matching
OrderCollection orders
SearchSet searches
Detailed Description
Definition at line 35 of file AutoIndex.h.
Member Typedef Documentation
typedef std::set<SearchColumns> souffle::AutoIndex::Chain protected
Definition at line 41 of file AutoIndex.h.
typedef std::vector<Chain> souffle::AutoIndex::ChainOrderMap protected
Definition at line 42 of file AutoIndex.h.
typedef std::vector<int> souffle::AutoIndex::LexicographicalOrder
Definition at line 37 of file AutoIndex.h.
typedef std::vector<LexicographicalOrder> souffle::AutoIndex::OrderCollection
Definition at line 38 of file AutoIndex.h.
typedef std::set<SearchColumns> souffle::AutoIndex::SearchSet protected
Definition at line 43 of file AutoIndex.h.
Constructor & Destructor Documentation
souffle::AutoIndex::AutoIndex () inline
Definition at line 53 of file AutoIndex.h.
 : isHashmap(false) {}
Member Function Documentation
void souffle::AutoIndex::addSearch (SearchColumns cols) inline
add new key to an Index Set
Definition at line 55 of file AutoIndex.h.
References searches.
{
         if (cols != 0) {
             searches.insert(cols);
         }
     }
static size_t souffle::AutoIndex::card (SearchColumns cols) inline static protected
count the number of bits in key
Definition at line 107 of file AutoIndex.h.
Referenced by isSubset(), and solve().
{
         size_t sz = 0, idx = 1;
         for (size_t i = 0; i < sizeof(SearchColumns) * 8; i++) {
             if (idx & cols) {
                 sz++;
             }
             idx *= 2;
         }
         return sz;
     }
const OrderCollection souffle::AutoIndex::getAllOrders () const inline
Definition at line 76 of file AutoIndex.h.
References orders.
{
         return orders;
     }
AutoIndex::Chain souffle::AutoIndex::getChain (const SearchColumns umn, const MaxMatching::Matchings & match) protected
given an unmapped node from set A we follow it from set B until it cannot be matched from B if not mateched from B then umn is a chain
Definition at line 125 of file AutoIndex.cpp.
References toB().
Referenced by getChainsFromMatching().
{
     SearchColumns start = umn;  // start at an unmateched node
     Chain chain;
     // Assume : no circular mappings, i.e. a in A -> b in B -> ........ -> a in A is not allowed.
     // Given this, the loop will terminate
     while (true) {
         MaxMatching::Matchings::const_iterator mit = match.find(toB(start));  // we start from B side
         chain.insert(start);
         if (mit == match.end()) {
             return chain;
         }
         SearchColumns a = mit->second;
         chain.insert(a);
         start = a;
     }
 }
const AutoIndex::ChainOrderMap souffle::AutoIndex::getChainsFromMatching (const MaxMatching::Matchings & match, const SearchSet & nodes) protected
get all chains from the matching
Definition at line 145 of file AutoIndex.cpp.
References ASSERT, chainToOrder, getChain(), and getUnmatchedKeys().
Referenced by solve().
{
     ASSERT(!nodes.empty());
     // Get all unmatched nodes from A
     const SearchSet& umKeys = getUnmatchedKeys(match, nodes);
     // Case: if no unmatched nodes then we have an anti-chain
     if (umKeys.empty()) {
         for (SearchSet::const_iterator nit = nodes.begin(); nit != nodes.end(); ++nit) {
             std::set<SearchColumns> a;
             a.insert(*nit);
             chainToOrder.push_back(a);
             return chainToOrder;
         }
     }
     ASSERT(!umKeys.empty());
     // A worklist of used nodes
     SearchSet usedKeys;
     // Case: nodes < umKeys or if nodes == umKeys then anti chain - this is handled by this loop
     for (SearchSet::iterator it = umKeys.begin(); it != umKeys.end(); ++it) {
         Chain c = getChain(*it, match);
         ASSERT(!c.empty());
         chainToOrder.push_back(c);
     }
     ASSERT(!chainToOrder.empty());
     return chainToOrder;
 }
const LexicographicalOrder souffle::AutoIndex::getLexOrder (SearchColumns cols) const inline
Definition at line 71 of file AutoIndex.h.
References map(), and orders.
{
         int idx = map(cols);
         return orders[idx];
     }
const SearchSet& souffle::AutoIndex::getSearches () const inline
obtains access to the internally stored keys
Definition at line 67 of file AutoIndex.h.
References searches.
{
         return searches;
     }
const SearchSet souffle::AutoIndex::getUnmatchedKeys (const MaxMatching::Matchings & match, const SearchSet & nodes) inline protected
get all nodes which are unmated from A-> B
Definition at line 160 of file AutoIndex.h.
References ASSERT.
Referenced by getChainsFromMatching().
{
         ASSERT(!nodes.empty());
         SearchSet unmatched;
         // For all nodes n such that n is not in match
         for (SearchSet::const_iterator it = nodes.begin(); it != nodes.end(); ++it) {
             if (match.find(*it) == match.end()) {
                 unmatched.insert(*it);
             }
         }
         return unmatched;
     }
void souffle::AutoIndex::insertIndex (std::vector< int > & ids, SearchColumns delta) inline protected
insert an index based on the delta
Definition at line 138 of file AutoIndex.h.
Referenced by solve().
{
         int pos = 0;
         SearchColumns mask = 0;
         while (mask < delta) {
             mask = SearchColumns(1 << (pos));
             SearchColumns result = (delta) & (mask);
             if (result) {
                 ids.push_back(pos);
             }
             pos++;
         }
     }
static bool souffle::AutoIndex::isStrictSubset (SearchColumns a, SearchColumns b) inline static protected
determine if key a is a strict subset of key b
Definition at line 132 of file AutoIndex.h.
Referenced by solve().
{
         SearchColumns tt = static_cast<SearchColumns>(std::numeric_limits<SearchColumns>::max());
         return (~(a) | (b)) == tt && a != b;
     }
bool souffle::AutoIndex::isSubset (SearchColumns cols) const inline
check whether number of bits in k is not equal to number of columns in lexicographical order
Definition at line 82 of file AutoIndex.h.
References card(), map(), and orders.
{
         int idx = map(cols);
         return card(cols) < orders[idx].size();
     }
int souffle::AutoIndex::map (SearchColumns cols) const inline protected
maps search columns to an lexicographical order (labeled by a number)
Definition at line 119 of file AutoIndex.h.
References ASSERT, chainToOrder, and orders.
Referenced by getLexOrder(), isSubset(), and solve().
{
         ASSERT(orders.size() == chainToOrder.size() && "Order and Chain Sizes do not match!!");
         int i = 0;
         for (auto it = chainToOrder.begin(); it != chainToOrder.end(); ++it, ++i) {
             if (it->find(cols) != it->end()) {
                 ASSERT((size_t)i < orders.size());
                 return i;
             }
         }
         abort();
     }
void souffle::AutoIndex::setHashmap (bool flag) inline
Set Hashmap.
Definition at line 62 of file AutoIndex.h.
References isHashmap.
{
         isHashmap = flag;
     }
void souffle::AutoIndex::solve ()
map the keys in the key set to lexicographical order
Definition at line 30 of file AutoIndex.cpp.
References souffle::MaxMatching::addEdge(), ASSERT, souffle::MaxMatching::calculate(), card(), chainToOrder, getChainsFromMatching(), insertIndex(), isHashmap, isStrictSubset(), map(), matching, orders, searches, and toB().
                       {
     if (searches.empty()) {
         return;
     }
     // check whether one of the naive indexers should be used
     // two conditions: either set by environment or relation is a hash map
     static const char ENV_NAIVE_INDEX[] = "SOUFFLE_USE_NAIVE_INDEX";
     if (isHashmap || std::getenv(ENV_NAIVE_INDEX)) {
         static bool first = true;
         // print a warning - only the first time
         if (!isHashmap && first) {
             std::cout << "WARNING: auto index selection disabled, naive indexes are utilized!!\n";
             first = false;
         }
         // every search pattern gets its naive index
         for (SearchColumns cur : searches) {
             // obtain order
             LexicographicalOrder order;
             SearchColumns mask = cur;
             for (int i = 0; mask != 0; i++) {
                 if (!(1 << i & mask)) {
                     continue;
                 }
                 order.push_back(i);
                 // clear bit
                 mask &= ~(1 << i);
             }
             // add new order
             orders.push_back(order);
             // register pseudo chain
             chainToOrder.push_back(Chain());
             chainToOrder.back().insert(cur);
         }
         //      std::cout << "Orders: " << orders << "\n";
         //      std::cout << "Chains: " << chainToOrder << "\n";
         return;
     }
     // Construct the matching poblem
     for (SearchSet::const_iterator it = searches.begin(); it != searches.end(); ++it) {
         // For this node check if other nodes are strict subsets
         for (SearchSet::const_iterator itt = searches.begin(); itt != searches.end(); ++itt) {
             if (isStrictSubset(*it, *itt)) {
                 matching.addEdge(*it, toB(*itt));
             }
         }
     }
     // Perform the Hopcroft-Karp on the graph and receive matchings (mapped A->B and B->A)
     // Assume: alg.calculate is not called on an empty graph
     ASSERT(!searches.empty());
     const MaxMatching::Matchings& matchings = matching.calculate();
     // Extract the chains given the nodes and matchings
     const ChainOrderMap chains = getChainsFromMatching(matchings, searches);
     // Should never get no chains back as we never call calculate on an empty graph
     ASSERT(!chains.empty());
     for (ChainOrderMap::const_iterator it = chains.begin(); it != chains.end(); ++it) {
         std::vector<int> ids;
         SearchColumns initDelta = *(it->begin());
         insertIndex(ids, initDelta);
         for (Chain::iterator iit = it->begin(); next(iit) != it->end(); ++iit) {
             SearchColumns delta = *(next(iit)) - *iit;
             insertIndex(ids, delta);
         }
         ASSERT(!ids.empty());
         orders.push_back(ids);
     }
     // Construct the matching poblem
     for (SearchSet::const_iterator it = searches.begin(); it != searches.end(); ++it) {
         int idx = map(*it);
         size_t l = card(*it);
         SearchColumns k = 0;
         for (size_t i = 0; i < l; i++) {
             k = k + (1 << (orders[idx][i]));
         }
         ASSERT(k == *it && "incorrect lexicographical order");
     }
 }
static SearchColumns souffle::AutoIndex::toA (SearchColumns b) inline static
convert from a representation of B verticies to A verticies
Definition at line 98 of file AutoIndex.h.
{
         SearchColumns msb = 1;
         msb <<= (4 * 8 - 1);
         return (b xor msb);
     }
static SearchColumns souffle::AutoIndex::toB (SearchColumns a) inline static
convert from a representation of A verticies to B verticies
Definition at line 91 of file AutoIndex.h.
Referenced by getChain(), and solve().
{
         SearchColumns msb = 1;
         msb <<= (4 * 8 - 1);
         return (a | msb);
     }
Field Documentation
ChainOrderMap souffle::AutoIndex::chainToOrder protected
Definition at line 47 of file AutoIndex.h.
Referenced by getChainsFromMatching(), map(), and solve().
bool souffle::AutoIndex::isHashmap protected
Definition at line 50 of file AutoIndex.h.
Referenced by setHashmap(), and solve().
MaxMatching souffle::AutoIndex::matching protected
Definition at line 49 of file AutoIndex.h.
Referenced by solve().
OrderCollection souffle::AutoIndex::orders protected
Definition at line 46 of file AutoIndex.h.
Referenced by getAllOrders(), getLexOrder(), isSubset(), map(), and solve().
SearchSet souffle::AutoIndex::searches protected
Definition at line 45 of file AutoIndex.h.
Referenced by addSearch(), getSearches(), and solve().
The documentation for this class was generated from the following files:
AutoIndex.h
AutoIndex.cpp