souffle: souffle::scheduler::BindingState Class Reference
souffle::scheduler::BindingState Class Reference
A model tracing the list of bound variables and estimating the cost of joins by assuming a fixed selectivity of bound values.
#include <RuleScheduler.h>
Public Member Functions
void bind (const Var &var)
bool isBound (const Var &var) const
void print (std::ostream &out) const override
Public Member Functions inherited from souffle::scheduler::State
Cost getCost () const
void incCost (Cost inc)
void setCost (Cost cost)
State ()
virtual ~State ()=default
Private Attributes
std::set< Var > bound
The set of bound variables.
Detailed Description
A model tracing the list of bound variables and estimating the cost of joins by assuming a fixed selectivity of bound values.
Definition at line 406 of file RuleScheduler.h.
Member Function Documentation
void souffle::scheduler::BindingState::bind (const Var & var) inline
Definition at line 411 of file RuleScheduler.h.
References bound.
Referenced by souffle::scheduler::MaxBindingModel::applyTo(), and souffle::scheduler::LogCostModel::applyTo().
{
         bound.insert(var);
     }
bool souffle::scheduler::BindingState::isBound (const Var & var) const inline
Definition at line 415 of file RuleScheduler.h.
References bound.
Referenced by souffle::scheduler::MaxBindingModel::applyTo(), and souffle::scheduler::LogCostModel::applyTo().
{
         return bound.find(var) != bound.end();
     }
void souffle::scheduler::BindingState::print (std::ostream & out) const inline override virtual
Implements souffle::scheduler::State.
Definition at line 419 of file RuleScheduler.h.
References bound, and souffle::scheduler::State::getCost().
{
         out << "State(" << getCost() << "," << bound << ")";
     }
Field Documentation
std::set<Var> souffle::scheduler::BindingState::bound private
The set of bound variables.
Definition at line 408 of file RuleScheduler.h.
Referenced by bind(), isBound(), and print().
The documentation for this class was generated from the following file:
RuleScheduler.h