souffle: souffle::ram::detail::RelationBase< arity, Derived > Struct Template Reference
souffle::ram::detail::RelationBase< arity, Derived > Struct Template Reference
A base class for partially specialized relation templates following below.
#include <CompiledRamRelation.h>
Public Types
typedef Tuple< RamDomain, arity > tuple_type
Public Member Functions
template<typename... Args>
bool contains (Args...args) const
bool contains (const tuple_type &tuple) const
std::string getDescription () const
template<typename... Args>
bool insert (Args...args)
bool insert (const RamDomain *ramDomain)
bool insert (const tuple_type &tuple)
void printHintStatistics (std::ostream &out, const std::string &prefix="") const
Private Member Functions
Derived & asDerived ()
const Derived & asDerived () const
Detailed Description
template<unsigned arity, typename Derived>
struct souffle::ram::detail::RelationBase< arity, Derived >
A base class for partially specialized relation templates following below.
This base class provides generic interfaces and adapters forwarding requests to the most general version offered by the derived classes to save implementation overhead and to unify the interface.
Template Parameters
arity .. the arity of the resulting relation
Derived .. the type of the derived relation
Definition at line 229 of file CompiledRamRelation.h.
Member Typedef Documentation
template<unsigned arity, typename Derived> typedef Tuple<RamDomain, arity> souffle::ram::detail::RelationBase< arity, Derived >::tuple_type
Definition at line 231 of file CompiledRamRelation.h.
Member Function Documentation
template<unsigned arity, typename Derived> Derived& souffle::ram::detail::RelationBase< arity, Derived >::asDerived () inline private
Definition at line 286 of file CompiledRamRelation.h.
{
         return static_cast<Derived&>(*this);
     }
template<unsigned arity, typename Derived> const Derived& souffle::ram::detail::RelationBase< arity, Derived >::asDerived () const inline private
Definition at line 291 of file CompiledRamRelation.h.
{
         return static_cast<const Derived&>(*this);
     }
template<unsigned arity, typename Derived> template<typename... Args> bool souffle::ram::detail::RelationBase< arity, Derived >::contains (Args... args) const inline
Definition at line 236 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::RelationBase< arity, SingleIndexRelation< arity, Index, table_factory > >::contains().
{
         RamDomain data[arity] = {RamDomain(args)...};
         return static_cast<const Derived*>(this)->contains(reinterpret_cast<const tuple_type&>(data));
     }
template<unsigned arity, typename Derived> bool souffle::ram::detail::RelationBase< arity, Derived >::contains (const tuple_type & tuple) const inline
Definition at line 241 of file CompiledRamRelation.h.
{
         typename Derived::operation_context ctxt;
         return static_cast<const Derived*>(this)->contains(tuple, ctxt);
     }
template<unsigned arity, typename Derived> std::string souffle::ram::detail::RelationBase< arity, Derived >::getDescription () const inline
Definition at line 271 of file CompiledRamRelation.h.
{
         std::stringstream out;
         static_cast<const Derived*>(this)->printDescription(out);
         return out.str();
     }
template<unsigned arity, typename Derived> template<typename... Args> bool souffle::ram::detail::RelationBase< arity, Derived >::insert (Args... args) inline
Definition at line 249 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::RelationBase< arity, SingleIndexRelation< arity, Index, table_factory > >::insert().
{
         RamDomain data[arity] = {RamDomain(args)...};
         return static_cast<Derived*>(this)->insert(reinterpret_cast<const tuple_type&>(data));
     }
template<unsigned arity, typename Derived> bool souffle::ram::detail::RelationBase< arity, Derived >::insert (const RamDomain * ramDomain) inline
Definition at line 254 of file CompiledRamRelation.h.
{
         RamDomain data[arity];
         std::copy(ramDomain, ramDomain + arity, data);
         const tuple_type& tuple = reinterpret_cast<const tuple_type&>(data);
         typename Derived::operation_context ctxt;
         return static_cast<Derived*>(this)->insert(tuple, ctxt);
     }
template<unsigned arity, typename Derived> bool souffle::ram::detail::RelationBase< arity, Derived >::insert (const tuple_type & tuple) inline
Definition at line 263 of file CompiledRamRelation.h.
{
         typename Derived::operation_context ctxt;
         return static_cast<Derived*>(this)->insert(tuple, ctxt);
     }
template<unsigned arity, typename Derived> void souffle::ram::detail::RelationBase< arity, Derived >::printHintStatistics (std::ostream & out, const std::string & prefix = "") const inline
Definition at line 280 of file CompiledRamRelation.h.
Referenced by souffle::ram::detail::RelationBase< arity, SingleIndexRelation< arity, Index, table_factory > >::printHintStatistics().
{
         static_cast<const Derived*>(this)->printHintStatistics(out, prefix);
     }
The documentation for this struct was generated from the following file:
CompiledRamRelation.h