souffle: souffle::scheduler::ComputeCostModel Struct Reference
souffle::scheduler::ComputeCostModel Struct Reference
The compute cost model tries to estimate the costs for computing a plan by maintaining estimates for the number of different values variables may be bound to at various stages of the execution of a plan.
#include <RuleScheduler.h>
Public Member Functions
ComputeCostState applyTo (const ComputeCostState &state, const ComputeCostAtom &atom) const override
Obtains the state reached when appending the given atom to a plan resulting in the given state.
Public Member Functions inherited from souffle::scheduler::cost_model< ComputeCostAtom, ComputeCostState >
virtual ComputeCostState getInitState () const
A factory for creating the state to be associated to the empty plan.
virtual ~cost_model ()=default
Additional Inherited Members
Public Types inherited from souffle::scheduler::cost_model< ComputeCostAtom, ComputeCostState >
typedef ComputeCostAtom atom_type
The type of atom to be required within the input problem.
typedef ComputeCostState state_type
The type of state to be associated to plans by this model.
Detailed Description
The compute cost model tries to estimate the costs for computing a plan by maintaining estimates for the number of different values variables may be bound to at various stages of the execution of a plan.
Note: at its current state – which might still provide improvement potential since not thoroughly investigated, this model turned out to be inferior to the simple cost model.
Definition at line 653 of file RuleScheduler.h.
Member Function Documentation
ComputeCostState souffle::scheduler::ComputeCostModel::applyTo (const ComputeCostState & state, const ComputeCostAtom & atom) const inline override virtual
Obtains the state reached when appending the given atom to a plan resulting in the given state.
Implements souffle::scheduler::cost_model< ComputeCostAtom, ComputeCostState >.
Definition at line 654 of file RuleScheduler.h.
References souffle::scheduler::ComputeCostState::bind(), souffle::scheduler::Atom::getArguments(), souffle::RelationStats::getCardinality(), souffle::RelationStats::getEstimatedCardinality(), souffle::scheduler::ComputeCostState::getInnermostIterations(), souffle::scheduler::ComputeCostAtom::getRelationStats(), souffle::scheduler::State::incCost(), souffle::scheduler::ComputeCostState::isBound(), souffle::scheduler::Argument::isConstant(), souffle::scheduler::Argument::isVariable(), and souffle::scheduler::ComputeCostState::setInnermostIterations().
{
         ComputeCostState res = state;
         const RelationStats& stats = atom.getRelationStats();
         const std::vector<Argument>& args = atom.getArguments();
         bool constraint = false;
         // multiplier factor of this loop operation
         auto f = stats.getCardinality();
         for (unsigned i = 0; i < args.size(); i++) {
             const Argument& cur = args[i];
             if (cur.isConstant()) {
                 f = min(f, stats.getEstimatedCardinality(i));
                 constraint = true;
             } else if (cur.isVariable()) {
                 if (state.isBound(cur)) {
                     f = min(f, stats.getEstimatedCardinality(i));
                 } else {
                     res.bind(cur, 1);
                 }
                 constraint = true;
             }
         }
         // compute number of nested iterations
         uint64_t numIterations = (uint64_t)f;
         if (numIterations <= 0) {
             numIterations = 1;
         }
         // costs per iteration
         double iterCost = (!constraint) ? 1 : log(stats.getCardinality());
         // add to cost
         res.incCost(state.getInnermostIterations() * iterCost);
         // increment nested iterators
         res.setInnermostIterations(state.getInnermostIterations() * f);
         // that's it
         return res;
     }
The documentation for this struct was generated from the following file:
RuleScheduler.h