souffle: souffle::scheduler::MaxBindingModel Struct Reference
souffle::scheduler::MaxBindingModel Struct Reference
The cost model estimating the cost of execution plans based on the number of bound/unbound variables in each step.
#include <RuleScheduler.h>
Public Member Functions
BindingState applyTo (const BindingState &state, const Atom &atom) const override
Obtains the state reached when appending the given atom to a plan resulting in the given state.
Public Member Functions inherited from souffle::scheduler::cost_model< Atom, BindingState >
virtual BindingState getInitState () const
A factory for creating the state to be associated to the empty plan.
virtual ~cost_model ()=default
Additional Inherited Members
Public Types inherited from souffle::scheduler::cost_model< Atom, BindingState >
typedef Atom atom_type
The type of atom to be required within the input problem.
typedef BindingState state_type
The type of state to be associated to plans by this model.
Detailed Description
The cost model estimating the cost of execution plans based on the number of bound/unbound variables in each step.
This model has turned out to be sub-optimal when facing chains of atoms. It is here as a reference and not the default.
Definition at line 432 of file RuleScheduler.h.
Member Function Documentation
BindingState souffle::scheduler::MaxBindingModel::applyTo (const BindingState & state, const Atom & atom) const inline override virtual
Obtains the state reached when appending the given atom to a plan resulting in the given state.
Implements souffle::scheduler::cost_model< Atom, BindingState >.
Definition at line 433 of file RuleScheduler.h.
References souffle::scheduler::BindingState::bind(), souffle::scheduler::Atom::getVariables(), souffle::scheduler::State::incCost(), and souffle::scheduler::BindingState::isBound().
{
         BindingState res = state;
         // adding this relation costs 1 unit
         Cost cost = 1;
         // unless there are variables pre-bound
         for (const Var& var : atom.getVariables()) {
             if (state.isBound(var)) {
                 cost *= 0.5;
             }
             res.bind(var);
         }
         // increment costs
         res.incCost(cost);
         // that's it
         return res;
     }
The documentation for this struct was generated from the following file:
RuleScheduler.h