souffle: souffle::scheduler::SimpleComputationalCostModel Struct Reference
souffle::scheduler::SimpleComputationalCostModel Struct Reference
The simple computational model is estimating the number of loop iterations on each level of the computation as well as the costs for each iteration.
#include <RuleScheduler.h>
Public Member Functions
SimpleComputationalCostState applyTo (const SimpleComputationalCostState &state, const SimpleComputationalCostAtom &atom) const override
Obtains the state reached when appending the given atom to a plan resulting in the given state.
Public Member Functions inherited from souffle::scheduler::cost_model< SimpleComputationalCostAtom, SimpleComputationalCostState >
virtual
SimpleComputationalCostState getInitState () const
A factory for creating the state to be associated to the empty plan.
virtual ~cost_model ()=default
Additional Inherited Members
Public Types inherited from souffle::scheduler::cost_model< SimpleComputationalCostAtom, SimpleComputationalCostState >
typedef SimpleComputationalCostAtom atom_type
The type of atom to be required within the input problem.
typedef
SimpleComputationalCostState state_type
The type of state to be associated to plans by this model.
Detailed Description
The simple computational model is estimating the number of loop iterations on each level of the computation as well as the costs for each iteration.
Definition at line 519 of file RuleScheduler.h.
Member Function Documentation
SimpleComputationalCostState souffle::scheduler::SimpleComputationalCostModel::applyTo (const SimpleComputationalCostState & state, const SimpleComputationalCostAtom & atom) const inline override virtual
Obtains the state reached when appending the given atom to a plan resulting in the given state.
Implements souffle::scheduler::cost_model< SimpleComputationalCostAtom, SimpleComputationalCostState >.
Definition at line 521 of file RuleScheduler.h.
References souffle::scheduler::SimpleComputationalCostState::bind(), souffle::scheduler::Atom::getArguments(), souffle::scheduler::SimpleComputationalCostAtom::getCardinality(), souffle::scheduler::SimpleComputationalCostState::getInnermostIterations(), souffle::scheduler::Atom::getNumConstants(), souffle::scheduler::State::incCost(), souffle::scheduler::SimpleComputationalCostState::isBound(), and souffle::scheduler::SimpleComputationalCostState::setInnermostIterations().
{
         SimpleComputationalCostState res = state;
         // keep a record on bound attributes
         bool someAttributsBound = atom.getNumConstants() > 0;
         // compute iterations per application
         Cost numIterations = atom.getCardinality();
         if (numIterations > 0) {
             for (const Argument& arg : atom.getArguments()) {
                 if (arg.isConstant()) {
                     numIterations *= 0.001;  // TODO: improve this value
                     someAttributsBound = true;
                 } else if (arg.isVariable()) {
                     if (state.isBound(arg)) {
                         numIterations *= 0.001;  // TODO: improve this value
                         someAttributsBound = true;
                     } else {
                         res.bind(arg);
                     }
                 }
             }
             // make sure number of iterations is not getting to small
             if (numIterations < 1) {
                 numIterations = 1;
             }
         }
         // compute full computation costs per iteration
         Cost costPerCall = (someAttributsBound) ? log(atom.getCardinality()) : 1;
         // increase total costs
         res.incCost(costPerCall * state.getInnermostIterations());
         // increase number of innermost iterations
         res.setInnermostIterations(res.getInnermostIterations() * numIterations);
         // that's it
         return res;
     }
The documentation for this struct was generated from the following file:
RuleScheduler.h