souffle: souffle::scheduler::Atom Struct Reference
souffle::scheduler::Atom Struct Reference
The base class for atoms to model the input of scheduling problems.
#include <RuleScheduler.h>
Public Member Functions
Atom (int id, const std::vector< Argument > &args)
const std::vector< Argument > & getArguments () const
Obtains the list of (abstracted) arguments exposed by this atom.
unsigned getArity () const
Obtains the arity of the targeted relation.
int getID () const
Obtains the identifier of this atom.
unsigned getNumConstants () const
Obtains the number of constant arguments.
std::vector< Var > getVariables () const
Obtains a list of the variable arguments.
bool operator< (const Atom &other) const
bool operator== (const Atom &other) const
virtual void print (std::ostream &out) const
virtual ~Atom ()=default
Data Fields
std::vector< Argument > args
The list of arguments of this atom.
int id
An ID of this atom, making it unique.
Friends
std::ostream & operator<< (std::ostream &out, const Atom &atom)
Detailed Description
The base class for atoms to model the input of scheduling problems.
Definition at line 133 of file RuleScheduler.h.
Constructor & Destructor Documentation
souffle::scheduler::Atom::Atom (int id, const std::vector< Argument > & args) inline
Definition at line 141 of file RuleScheduler.h.
 : id(id), args(args) {}
virtual souffle::scheduler::Atom::~Atom () virtual default
Member Function Documentation
const std::vector<Argument>& souffle::scheduler::Atom::getArguments () const inline
Obtains the list of (abstracted) arguments exposed by this atom.
Definition at line 151 of file RuleScheduler.h.
Referenced by souffle::scheduler::SimpleComputationalCostModel::applyTo(), souffle::scheduler::ComputeCostModel::applyTo(), souffle::scheduler::LogCostModel::applyTo(), souffle::scheduler::SimpleComputationalCostAtom::print(), and souffle::scheduler::ComputeCostAtom::print().
{
         return args;
     }
unsigned souffle::scheduler::Atom::getArity () const inline
Obtains the arity of the targeted relation.
Definition at line 181 of file RuleScheduler.h.
Referenced by souffle::scheduler::LogCostModel::applyTo().
{
         return args.size();
     }
int souffle::scheduler::Atom::getID () const inline
Obtains the identifier of this atom.
Definition at line 146 of file RuleScheduler.h.
Referenced by souffle::scheduler::SimpleComputationalCostAtom::print(), and souffle::scheduler::ComputeCostAtom::print().
                       {
         return id;
     }
unsigned souffle::scheduler::Atom::getNumConstants () const inline
Obtains the number of constant arguments.
Definition at line 156 of file RuleScheduler.h.
Referenced by souffle::scheduler::SimpleComputationalCostModel::applyTo().
{
         unsigned count = 0;
         for (const auto& cur : args) {
             if (cur.isConstant()) {
                 count++;
             }
         }
         return count;
     }
std::vector<Var> souffle::scheduler::Atom::getVariables () const inline
Obtains a list of the variable arguments.
Definition at line 167 of file RuleScheduler.h.
References souffle::contains().
Referenced by souffle::scheduler::MaxBindingModel::applyTo().
{
         std::vector<Var> res;
         for (const Argument& cur : args) {
             if (cur.isVariable()) {
                 Var v = cur;
                 if (!contains(res, v)) {
                     res.push_back(v);
                 }
             }
         }
         return res;
     }
bool souffle::scheduler::Atom::operator< (const Atom & other) const inline
Definition at line 189 of file RuleScheduler.h.
References id.
{
         return id < other.id;
     }
bool souffle::scheduler::Atom::operator== (const Atom & other) const inline
Definition at line 185 of file RuleScheduler.h.
References id.
{
         return id == other.id;
     }
virtual void souffle::scheduler::Atom::print (std::ostream & out) const inline virtual
Reimplemented in souffle::scheduler::ComputeCostAtom, and souffle::scheduler::SimpleComputationalCostAtom.
Definition at line 193 of file RuleScheduler.h.
{
         out << "<" << id << ">"
             << "( " << args << " )";
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Atom & atom) friend
Definition at line 198 of file RuleScheduler.h.
{
         atom.print(out);
         return out;
     }
Field Documentation
std::vector<Argument> souffle::scheduler::Atom::args
The list of arguments of this atom.
Definition at line 138 of file RuleScheduler.h.
int souffle::scheduler::Atom::id
An ID of this atom, making it unique.
Definition at line 135 of file RuleScheduler.h.
Referenced by operator<(), and operator==().
The documentation for this struct was generated from the following file:
RuleScheduler.h