souffle: souffle::scheduler::LogCostModel Struct Reference
souffle::scheduler::LogCostModel Struct Reference
A model computing the cost of a schedule based on the formula:
#include <RuleScheduler.h>
Public Member Functions
BindingState applyTo (const BindingState &state, const SimpleComputationalCostAtom &atom) const override
Obtains the state reached when appending the given atom to a plan resulting in the given state.
BindingState getInitState () const override
A factory for creating the state to be associated to the empty plan.
Public Member Functions inherited from souffle::scheduler::cost_model< SimpleComputationalCostAtom, BindingState >
virtual ~cost_model ()=default
Additional Inherited Members
Public Types inherited from souffle::scheduler::cost_model< SimpleComputationalCostAtom, BindingState >
typedef SimpleComputationalCostAtom atom_type
The type of atom to be required within the input problem.
typedef BindingState state_type
The type of state to be associated to plans by this model.
Detailed Description
A model computing the cost of a schedule based on the formula:
C = prod_{ a in schedule } (n_a^(f_a/m_a))
where C ... the costs, a ... atoms in a schedule, n_a ... cardinality of relation referenced by atom a f_a ... free arguments of atom a m_a ... arity of relation referenced by atom a
Definition at line 716 of file RuleScheduler.h.
Member Function Documentation
BindingState souffle::scheduler::LogCostModel::applyTo (const BindingState & state, const SimpleComputationalCostAtom & atom) const inline override virtual
Obtains the state reached when appending the given atom to a plan resulting in the given state.
Implements souffle::scheduler::cost_model< SimpleComputationalCostAtom, BindingState >.
Definition at line 723 of file RuleScheduler.h.
References souffle::scheduler::BindingState::bind(), souffle::scheduler::Atom::getArguments(), souffle::scheduler::Atom::getArity(), souffle::scheduler::SimpleComputationalCostAtom::getCardinality(), souffle::scheduler::State::getCost(), souffle::scheduler::BindingState::isBound(), and souffle::scheduler::State::setCost().
{
         BindingState res = state;
         // compute the costs of this step
         double step = pow((double)atom.getCardinality(), (double)1 / (double)atom.getArity());
         double cost = 1;
         for (const auto& cur : atom.getArguments()) {
             if (cur.isConstant()) {
                 // nothing here
             } else if (cur.isVariable()) {
                 if (!state.isBound(cur)) {
                     cost *= step;
                     res.bind(cur);
                 }
             } else {
                 // unbound value => increases cost
                 cost *= step;
             }
         }
         // update costs
         res.setCost(state.getCost() * cost);
         // that's it
         return res;
     }
BindingState souffle::scheduler::LogCostModel::getInitState () const inline override virtual
A factory for creating the state to be associated to the empty plan.
Reimplemented from souffle::scheduler::cost_model< SimpleComputationalCostAtom, BindingState >.
Definition at line 717 of file RuleScheduler.h.
References souffle::scheduler::State::setCost().
{
         BindingState res;
         res.setCost(1);
         return res;
     }
The documentation for this struct was generated from the following file:
RuleScheduler.h